### ISSUE TITLE
Feature Request: Support for changing the author of a Resource

### ISSUE THREAD

**Issue by Devlanda** [modxcms/revolution#13264] opened 2017-01-26 08:29 UTC
Support for changing the author of a Resource. This is now only possible via phpMyAdmin, with Batcher (Extra) or a snippet. In case of a published e.g. blog article or something where you need to change the author, the current way to do that is cumbersome and is not good for user experience.

**Comment by Jako** [comment] 2017-01-26 09:32
Duplicate of #12305

**Closed by Jako** 2017-01-26 09:32 UTC
