### ISSUE TITLE
MODX 2.8.3 modx.mysql.schema.xml not valid XML

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#16073] opened 2022-02-22 20:32 UTC
### Summary
The modx.mysql.schema.xml in MODX 2.8.3 is not valid XML

Validation rules in the following lines contain a `<` character which is not allowed in a rule, according to the XML validator [here](https://www.xmlvalidation.com/). 

 - 376
 - 815
 - 1075
 - 1136
 - 1186

Escaping the character with a backslash doesn't help, but removing it does. 

The ObjectExplorer extra parses the schema file to produce a widely-used reference page on MODX objects at Bob's Guides. OE crashes in 2.8.3 because parsing the file fails. 

This is not an issue in MODX 3, where the `<` characters have been removed from those lines.

The character was introduced in this commit: ef246f1dad3ea121b5bc926d9a057b65f3b903f3

**Comment by JoshuaLuckers** [comment] 2022-02-25 14:48
With the [modx.mysql.schema.xml from the 2.x branch](https://github.com/modxcms/revolution/blob/4e4735d81bc0ad8a35c3f8816b8e033b64c4c5c5/core/model/schema/modx.mysql.schema.xml) (at time of writing) I don't get any errors when I use the validator you mentioned.

Do I miss something?

**Comment by BobRay** [comment] 2022-02-25 18:42
Do those lines have a `<` character in the rule section like this (near the end of the regex):

```
<rule field="name" name="invalid" type="preg_match" rule="/^(?!\s)[a-zA-Z0-9\x2d-\x2f\x7f-\xff-_\s]+(?<!\s)$/" message="chunk_err_invalid_name" />```

Could there have been a silent upgrade to 2.8.3 to remove them?

**Comment by smg6511** [comment] 2022-02-25 21:00
Bob, the rule is correct and is using the html entity for the "<" character in the schema file. The original rule is wrong and must in the end equate to (?<!\s) not (?!\s) because the latter will allow trailing space. It isn't this way in 3.0 yet because my port of the PR that updated this for 2.x hasn't been merged yet.

**Comment by opengeek** [comment] 2022-02-25 21:15
> Bob, the rule is correct and is using the html entity for the "<" character in the schema file. The original rule is wrong and must in the end equate to (?<!\s) not (?!\s) because the latter will allow trailing space. It isn't this way in 3.0 yet because my port of the PR that updated this for 2.x hasn't been merged yet.

Wait, what? What ported PR hasn't been merged?

**Comment by smg6511** [comment] 2022-02-25 21:22
PR #16012, which is a resubmitted partial of my original #15887. I have the rest ready to go when #16012 gets merged ... just need someone else to look at and approve. Note though that the update to the schema file is not in #16012, because that PR only dealt with the Resource part of the equation. That change would be in the forthcoming PR that targets the Element panels (where those changes to the schema file apply).

**Comment by BobRay** [comment] 2022-02-25 21:23
Interesting. 

When I loaded the file content and ran xml_parse() on it, it choked on each of those lines with an error message about the `<` character. When I cut and pasted the file content into the validator, it flagged each of those lines as an error.

When I view the file in PhpStorm, I see the `<` character rather than an entity.

**Comment by JoshuaLuckers** [comment] 2022-03-25 10:08
I'm not sure if this is an issue we still need to fix or if we can close this issue.

**Comment by Jako** [comment] 2022-03-25 13:18
I can't reproduce this issue either.

**Comment by BobRay** [comment] 2022-03-25 17:39
You can close it as far as I'm concerned. I suspect that is was an artifact of cutting and pasting the code at some point.

**Closed as completed** 2022-03-25 17:46 UTC
Labels: bug
