### ISSUE TITLE
Uncaught SyntaxError when editing a specific js-file

### ISSUE THREAD

**Issue by SystemKeeper** [modxcms/revolution#13214] opened 2016-12-08 20:50 UTC
### Summary
When a specific javascript file is accessed through MODXs filebrowser, an "Uncaught SyntaxError" is thrown and the editor won't load.

### Step to reproduce
1. Add the following js-file to "assets/js" (it's named "updater.js" for reference):
```
var Module = (function (parent, $) {
    var api = parent.Updater = parent.Updater || {};

    // Initialisierungsfunktion für jedes Modul
    api.init = function(customOptions) {

    };

    return parent;
}(Module || {}, jQuery));
```
2. In MODX manager select "Files" (the tab next to "Resources" and "Elements")
3. Navigate to "assets/js" and click on "updater.js".

### Observed behavior
MODX shows a blank screen next to the file-tree. The following errors are logged to the console:

![image](https://cloud.githubusercontent.com/assets/1580193/21026984/37f74902-bd8f-11e6-8deb-f6e623b0e693.png)
![image](https://cloud.githubusercontent.com/assets/1580193/21026991/3fa463b0-bd8f-11e6-8cc9-774bfe3286b6.png)
![image](https://cloud.githubusercontent.com/assets/1580193/21026992/42869bc0-bd8f-11e6-8a47-1fea1e7bccdb.png)

### Expected behavior
The file content should be displayed with the ability to edit the file.

### Environment
MODX Revolution 2.5.2-pl (traditional)
PHP 7.0.13

### Remarks
- Happens with and without ACE / CodeMirror Extra
- I've tracked down the issue to javascript code above. Every other file (like "jquery-3.1.1.min.js") works just fine!

**Comment by OptimusCrime** [comment] 2016-12-10 14:13
This looks like the locale issue again. Can you remove the special character from the comment of your javascript file? The ü. See if that fixes that issue.

**Comment by SystemKeeper** [comment] 2016-12-10 14:31
Argh - it never occured to me that the comment could be the problem. Yes you're right, removing the "ü" fixes that issue. Thanks for your help. If this is a known bug, this issue can be closed.

**Comment by OptimusCrime** [comment] 2016-12-10 15:01
Although the location of the problem is different, it has the same nature as #13079 and other related issues as far as I can understand.

This is something that should be dealt with asap.

Thank you for reporting this incident, glad you found a solution,

**Comment by OptimusCrime** [comment] 2016-12-23 18:12
Closing this issue as it is a duplicate of other issue. This, as previously stated, it looks different on the outside, it is caused by the same root problem.

This issue is already referenced in the other issue.

Feel free to comment or reopen if you feel this should not be closed.

@modxbot close

**Closed by OptimusCrime** 2016-12-23 18:12 UTC
