### ISSUE TITLE
500 response error during saving a certain string into content field

### ISSUE THREAD

**Issue by himurovich** [modxcms/revolution#13225] opened 2016-12-22 14:48 UTC
### Summary
Can't save this text into content field: 

> She has been selected in multiple years to the Pennsylvania Super Lawyers list, as well as to The Best Lawyers in America® list under the category of commercial litigation. Susan was also named a 2014 BTI Client Service All-Star, a listing explicitly identified by corporate counsel which is derived from in-depth telephone interviews that determine which attorneys top the charts in client service. 

### Step to reproduce

Create unpublished resource with empty template and without richeditor enabled option, put the text into content field and press "Save" button.

### Observed behavior
I've got  [500 error](http://take.ms/tub49)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 webmaster@XXXXXXXXXX to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<p>Additionally, a 500 Internal Server Error
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<hr>
<address>Apache/2.4.23 (Unix) OpenSSL/0.9.8e-fips-rhel5 mod_bwlimited/1.4 Server at XXXXXXXX Port 80</address>
</body></html>
```

### Expected behavior
Text has to be saved successfully. Btw if I save smaller part of that text it will be OK:

> She has been selected in multiple years to the Pennsylvania Super Lawyers list, as well as to The Best Lawyers in America® list under the category of commercial litigation. Susan was also named a 2014 BTI Client Service All-Star, a listing explicitly identified by corporate counsel which is derived

Also If I try to save any other bigger texts all is also OK. So speech is about that text only.I've removed any suspicious characters ( like ®.. ), didn't help.

### Environment
MODX 2.5.1.-pl, Apache/2.4.23 (Unix) OpenSSL/0.9.8e-fips-rhel5 mod_bwlimited/1.4 Server  Also I know that Firewall is on the server. Testing this issue(saving different parts of texts and searching the cause) and after receiving several 500 response codes i've been blocked so had to change IP address. Maybe some suhosin influence here..don't know exactly.

Sent headers were also attached. There are nothing unusual into error.log
[headers.txt](https://github.com/modxcms/revolution/files/668989/headers.txt)

**Comment by sottwell** [comment] 2016-12-22 14:58
Does sound like a mod_security (suhosin) issue. You would have to have your hosting tech support look at their mod_security logs.

**Comment by sottwell** [comment] 2016-12-22 15:01
By the way, this is more for bugs and issues with MODX itself, you should join the MODX Slack community and get help there. http://modx.org/

**Comment by OptimusCrime** [comment] 2016-12-23 18:09
@himurovich This is very likely caused by mod_security or other apache settings, and not the cause of MODX itself.

I am closing this issue. Feel free to reopen or comment if you have any additional information, or if you feel that my explanation is not correct.

@modxbot close

**Closed by OptimusCrime** 2016-12-23 18:09 UTC
