### ISSUE TITLE
if-then-else output filters break when @ is used in property text

### ISSUE THREAD

**Issue by frischnetz** [modxcms/revolution#11269] opened 2014-04-09 08:22 UTC
When one uses @ inside the text of a tag property inside of an if-then-else-clause, the whole statement breaks and neither the then- nor the else-part is evaluated.

Minimal example: 
Consider the two statements: (use in [[*content]] with minimal template): 

```
A[[*pagetitle:isnot=`Y`:then=`C[[$Z?&mail=`ab.de`]]E`:else=`F`]]B
A[[*pagetitle:isnot=`Y`:then=`C[[$Z?&mail=`ab@de`]]E`:else=`F`]]B
```

I sprinkled some letters for clarity of the output.

No matter what, they should produce identical output (ACEB). But in the second line the whole if-then-else-expession discarded by the renderer, so it only gives AB.

The only difference between the two lines is the @ inside the property. And it does not matter, if the whole then-statement is wrapped inside a chunk, it still breaks:

```
<p>A[[*pagetitle:isnot=`Y`:then=`[[$TEST]]`:else=`F`]]B</p>
where
[[$TEST]] = C[[$Z?&mail=`ab@de`]]E
```

This bug dates back at least till 2.2.4, that is the oldest Revo version I  tested.

A possible workaround is using the [[If]]-Snippet. I found no problems here.

**Comment by opengeek** [comment] 2015-01-13 21:11
@inreti — I tried your proposed fix but I cannot get the conditional logic to return the `else`, only the `then` part of the expression, regardless of the logic.

**Comment by inreti** [comment] 2015-07-12 07:34
Started again working on it.

**Comment by netProphET** [comment] 2017-07-07 13:29
Re-confirmed in 2.5.7. I'm going to give this a shot.

**Comment by gernotebenlechner** [comment] 2017-07-07 13:31
Checking this issue at #modxbughunt if it is still valid with the suggested code (Chunk & Snippet):

```[[*id:gt=`0`:then=`[[AddCharBug? &param=`@`]]`:else=``]]```

as well as 

```[[*id:gt=`0`:then=`[[AddCharBug? &param=`abc@xyz.com`]]`:else=``]]```

as well as 

```[[*id:gt=`0`:then=`[[AddCharBug? &param=`@EVAL`]]`:else=``]]```

just to make sure.

Result: On a fresh 2.5.8-dev install I **could NOT REPRODUCE** if-then-else output filters break when `@` is used in property text.

**Comment by gernotebenlechner** [comment] 2017-07-07 13:37
I've used this small snippet "AddCharBug" for testing:

```
<?php
$output = '<p>'.$param.'</p>';
return $output;
```

**Comment by gernotebenlechner** [comment] 2017-07-07 13:41
No problem in 2.5.7 as well.

**Comment by wuuti** [comment] 2017-07-07 13:51
Let me also check it. Maybe I can provoke it again :-)

**Comment by wuuti** [comment] 2017-07-07 13:59
Well, just checked out the current 2.x branch, and there the error still exists. 
Reproduce with a resource with empty template and the following in the content:
```
[[*id:gt=`0`:then=`
[[AddCharBug? &param=`@`]]
`:else=``]]
```
<img width="417" alt="screen shot 2017-07-07 at 15 58 28" src="https://user-images.githubusercontent.com/2852461/27960867-28dcaa5e-632d-11e7-82b4-9ec51b493f38.png">

So maybe a patch in the 2.5.x branch fixed also this problem. I will try to reproduce it on the patch branch again.

**Comment by gernotebenlechner** [comment] 2017-07-07 14:18
@wuuti I can reproduce the behaviour you desribed at #modxbughunt only when the called snippet doesn't exit.

**Comment by sonicpunk** [comment] 2017-07-07 14:21
@wuuti I can also reproduce this behaviour.  Interesting, Dr. Watson.

**Comment by wuuti** [comment] 2017-07-07 14:22
Ok, we are getting closer again. Reproducable if the snippet does not exist and the parameter contains an @ sign. If the snippet does not exist, and the parameter does _not_ contain an @, then the output is ok (empty). Anyway, the parser should not break and output only half of a snippet tag like above...

**Comment by wuuti** [comment] 2017-07-07 14:31
Building a PR for my (old) solution. #modxbughunt.

**Comment by netProphET** [comment] 2017-07-07 15:53
I didn't notice all the discussion here after I had mentioned that I was going to work on this. I have a solution that solves the original test case. But I have found a more complex test case that I have not solved yet.

So I've solved:
```
 A[[*pagetitle@mypropset:isnot=`Y`:then=`B[[$Z?&mail=`ab@de`]]C`:else=`DE`]]F
```

But created this new test and not solved it yet:
```
A[[*[[*page[[++baz:default=`title`]]]]:isnot=`Y`:then=`B[[$Z?&mail=`ab@de`]]C`:else=`DE`]]F
```

**Comment by gpsietzema** [comment] 2017-07-07 16:06
#modxbughunt #1point to @wuuti @gernotebenlechner @netProphET @sonicpunk

**Comment by alroniks** [comment] 2021-04-10 21:31
I respect all work that was done but based on the fact, that it is a very complex cases, suggested PR was rejected for reasons and modx parser still very limited by functions, I suggest closing it. Please, reopen, or better create a new Proposal how it can be improved.

**Closed by alroniks** 2021-04-10 21:31 UTC
Labels: area-core
