### ISSUE TITLE
2.4.1 Can't restore removed Dashboard Widget

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12683] opened 2015-09-29 21:13 UTC
After removing a widget from the default dashboard, I doesn't show up for me in the list on the dashboard/update panel, even after manually deleting the cache files.  It's still in the DB.

**Comment by christianseel** [comment] 2017-03-03 19:05
Tried to reproduce that with the `Recently added resources` widget in 2.5.5 without luck. Was working as expected and I was able to add back the before removed widget.

@BobRay do you wanna retry and confirm that it's working with (a fresh) 2.5.5, so we can close this?

#modxbughunt

**Comment by OptimusCrime** [comment] 2017-03-06 00:36
Looks like this has been solved? 

Closing it for now. @BobRay please try to reproduce this as well.

@modxbot close

**Closed by OptimusCrime** 2017-03-06 00:36 UTC

**Comment by BobRay** [comment] 2017-03-07 19:42
I'll take Christian's word for it. ;)
