### ISSUE TITLE
Forgot Password mail

### ISSUE THREAD

**Issue by Gallenkamp** [modxcms/revolution#9506] opened 2013-02-08 22:39 UTC
gallenkamp created Redmine issue ID 9506

Hi there,

please consider making a link ouot of the URL in the "forgot password" function. That should be an improvement on "UI" or what the one hip word / category or that case may be :)

Cheers,

Guido

**Comment by Gallenkamp** [comment] 2015-01-14 16:26
The issue is that you cant log out of the manager if javascript is broken. And is if broken fairly often when some node cant handle compression or some server doesnt like the 777 instead of 755 folder permissions.
In one sentence: "A logout function must not rely on javascript"

**Comment by OptimusCrime** [comment] 2015-07-13 15:37
This is a duplicate of #8837

@modxbot close

**Closed by OptimusCrime** 2015-07-13 15:37 UTC
Labels: bug
