### ISSUE TITLE
Adding & populating image TV causes HTTP ERROR 500

### ISSUE THREAD

**Issue by CamilleBeaute** [modxcms/revolution#16211] opened 2022-06-22 04:38 UTC
### Summary

When populating and image TV then trying to view the page, the page never loads and an HTTP ERROR 500 error appears.

### Step to reproduce

1. Create a TV with input type "image"
2. Add TV to a template
3. Apply the template to a resource in the file tree
4. Add an image to the image TV
5. Save & View the resource

### Observed behavior
Page never loads and an HTTP ERROR 500 error appears

### Expected behavior
Page should load with correct image path from TV

### Environment
MODX version: MODX Revolution 3.0.1-pl (traditional)
mysql version: 5.6.41-84.1
browser: Chrome

**Comment by halftrainedharry** [comment] 2022-06-22 14:08
I can't reproduce this.

Can you check the PHP error log (_not_ the error log in MODX) to see what the actual error message is?

**Comment by CamilleBeaute** [comment] 2022-06-22 14:31
Hi - yes, below is the error from the PHP error log:

`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home4/blahblahpath/public_html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php on line 1052`

The section of the file mentioned above includes the following:

```
case 'array' :
if (is_string($value)) {
$value= unserialize($value);
}
break;
```

Line 152 specifically is: `$value= unserialize($value);`

**Comment by halftrainedharry** [comment] 2022-06-22 14:39
There has been a similar issue in the MODX forum:
https://community.modx.com/t/modx-revo-3-error-500-if-i-try-to-set-tv-at-any-template/5371

The problem was a bug in the extra _pdoTools_.

**Comment by CamilleBeaute** [comment] 2022-06-22 14:50
Thank you! This does look like what I'm experiencing. I will follow up with them. Thanks!

**Comment by JoshuaLuckers** [comment] 2022-06-23 06:40
Thanks for taking time to help MODX and report this issue. Since this is an issue in `pdoTools` I'm going to close this issue.

**Closed as completed by JoshuaLuckers** 2022-06-23 06:40 UTC
Labels: bug
