### ISSUE TITLE
[3.x] UI elements bug

### ISSUE THREAD

**Issue by CrazyBoy49z** [modxcms/revolution#14958] opened 2020-01-17 14:05 UTC
### Summary

![image](https://user-images.githubusercontent.com/3448603/72617988-d7d66c00-3942-11ea-8882-cac9342ff1a8.png)

### Step to reproduce
Create "Template Variables", open created Template Variables in browser

I test after upgrade MODX 2.7.2 to MODX 3.0.0-alpha1

**Comment by Mark-H** [comment] 2020-01-17 14:22
If you mean the scrollbar overlapping the tree contents, then this is a duplicate of #14375 which has been fixed in #14917 for alpha2 (planned for the 28th).

**Closed as completed by Mark-H** 2020-01-17 14:22 UTC
