### ISSUE TITLE
TV (image) with Media Sources in different contexts don't get set untill manually done so

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#9799] opened 2013-04-08 14:18 UTC
ReSpawN created Redmine issue ID 9799

This subject is just effin' brilliant. 

The problem is as follows: we've got a new contexts using the exact same TV as the root web context, but it couldn't parse the header image correctly, which was a Image TV with a linked Media Source.
I fixed it by simply double clicking the Source portion in the grid under [Media Sources] and thus re-saving the TV. :) I suspect junction links aren't duplicated when duplicating a context.

**Comment by GulomovCreative** [comment] 2019-01-16 10:18
I can confirm on 2.7.0-pl

The path is correctly inserted during the page rendering, but the file source is not taken when the image is loaded into the Media Manager. The problem is solved by re-saving TV.

**Comment by Mark-H** [comment] 2019-01-16 11:31
Closing as duplicate of #9058.

**Closed by Mark-H** 2019-01-16 11:31 UTC
Labels: bug
