### ISSUE TITLE
Weird effects with nested items (cached, uncached)

### ISSUE THREAD

**Issue by pixelive** [modxcms/revolution#13250] opened 2017-01-12 10:05 UTC
### Summary
Weird effects with nested items. Although the use cases are a bit weird and probably give wrong results, it should not give broken results like it does now.

### Step to reproduce
I simplified the cases a bit.

**Case A**
Create a chunk called 'rowChunk' with the following content:
```
[[+rows]]
```

Create a chunk called 'equalChunk' with the following content:
```
[[!++site_url:notempty=`<p class="success">[[!++site_url]]</p>`]]
```

Put this in your template:
```
[[$rowChunk?
&rows=`[[$equalChunk]]`
]]
```

**Case B**
Create a chunk called 'rowChunk' with the following content:
```
[[+rows]]
```

Create a chunk called 'longChunk' with the following content:
```
[[!longSnippet? &value=`Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. 
Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. 
Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. 
Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. 
Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. 
Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper 
ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing 
sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. 
Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. 
Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,
quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, 
nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante 
ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. 
Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a,
consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum
volutpat pretium libero. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Nullam nulla eros, ultricies sit amet, nonummy id,
imperdiet feugiat, pede. Sed lectus. Donec mollis hendrerit risus. Phasellus nec sem in justo pellentesque facilisis. Etiam imperdiet
imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non,
euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu.
Phasellus accumsan cursus velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam`]]
```

Create a snippet called 'longSnippet' with the following content:
```
<?php
$value = $modx->getOption('value', $scriptProperties, '');

return $value;
```

Put this in your template:
```
[[$rowChunk?
&rows=`[[$longChunk]]`
]]
```

### Observed behavior

**Case A**
It shows no output at all, but if I remove 'class="success"' it works. Making the !$rowChunk or the !$equalChunk uncached also works. But the case as described breaks.

**Case B** 
It shows the following:
```
Sed aliquam`]]`
```

So not the full string as given.

Making the !$rowChunk or the !$longChunk uncached works. But the case as described breaks.

### Expected behavior

**Case A**
Showing the Site URL.

**Case B** 
Show the given string.

### Environment

- MODX: Tried multiple versions (2.5.0, 2.5.1, 2.5.2, 2.5.4).
- Nginx
- Mysql: Ver 15.1 Distrib 10.0.28-MariaDB

I tried multiple encodings and collations.

**Comment by Jako** [comment] 2017-01-12 11:06
I have noticed something similar with long parameter values lately. Maybe it is a regex limitation. I could bypass it with the mosquito syntax in that installation, but thats not possible everywhere.

```
[[$rowChunk?
&rows=`[[$longChunk]]`
]]
```
vs
```
[[[[$rowChunk?
&rows=`$longChunk`
]]]]
```

**Comment by Bruno17** [comment] 2017-01-15 07:31
I'm doing it this way:

```
[[$rowChunk?
&rows=`$longChunk`
]]
```
and use a placeholder inside the rowChunk like:

```
[[[[+rows]]]]
```

**Comment by OptimusCrime** [comment] 2017-01-15 13:00
@Bruno17 Is that syntax working? I thought the two combinations @Jako posted were the ones that work?

Also @Jako I am pretty sure this has nothing to do with regex. The templates are parsed using a lexer/tokenizer, as far as I know.

**Comment by Bruno17** [comment] 2017-01-15 13:08
@OptimusCrime Sure, you pass only the value '$longChunk' into the placeholder [[+rows]], which results in [[$longChunk]] inside the chunk and gets parsed, when the chunk-code is parsed. That's much better than trying to pass the whole long chunk-code into the placeholder. At some point the code in between nested MODX - tags gets to long and breaks the whole thing.

**Comment by OptimusCrime** [comment] 2017-01-15 13:11
Oh. I've never done it like that. Interesting.

**Comment by mrhaw** [comment] 2017-01-16 18:01
What if you set this in your php.ini

```
;PCRE library backtracking limit.
pcre.backtrack_limit=200000
```

**Comment by pixelive** [comment] 2017-01-19 11:07
@mrhaw does not seem to work :(

**Comment by umnic** [comment] 2017-03-03 10:10
A real world use-case which is affected by this issue:

Using [Content Blocks](https://www.modmore.com/contentblocks/) together with [Formit](https://docs.modx.com/extras/revo/formit) Snippet in a Content Blocks field (in the corresponding field template tab or in a called chunk).
The uncached Formit Snippet call works fine, as long as you do not use a property in the snippet call which has equal signs in its value string (e.g. the fieldnames property used by the FormItSaveForm Hook).
If you use equal signs, the whole page returns blank.

**Comment by umnic** [comment] 2017-04-18 09:49
Using one of the following characters in the snippet input properties strings seem to break the output:

 =,?,&

**Comment by christianseel** [comment] 2017-07-07 12:11
# Bug Bounty: 1.000 EUR
**SEDA.digital is putting a bounty on this issue of _1.000 EUR_ as part of the MODX Bug Hunt in Munich, Germany!**

You got time until Friday, July 14th 2017 to submit your PR, which needs to solve the issue. Once the PR is accepted and merged you'll get the prize!

**Comment by jpdevries** [comment] 2017-07-07 12:14
And for those accustomed to silly 🇺🇸 units that is one thousand Euros!

**Comment by Flowan** [comment] 2017-07-07 13:43
Confirmed this bug in 2.5.x I'm going to try and fix this today.

**Comment by bezumkin** [comment] 2017-07-07 17:46
A little description for my PR.

**Case A** happend because
```
[[$rowChunk?&rows=`[[$equalChunk]]`]]
```
wil unwrap into
```
[[$rowChunk?&rows=`[[!++site_url:notempty=`<span class="success">[[!++site_url]]</span>`]]`]]
```
And then uncached call will be bypassed, but cached will be rendered as empty.

**Case B** has the same source but the problem is in `;` sign. When uncached element gets inside parameter of other element it must be parsed as parameter string. And it will stuck [here](https://github.com/modxcms/revolution/blob/a2c0f793a366ed78bd04d758358a5e6d7cbe149e/core/model/modx/modparser.class.php#L334) - this old code will just split the whole string at `;`.

Both cases solved by my PR - uncached elements should be not called inside cached. But now it will work, with warning in system log.

**Comment by goldsky** [comment] 2017-07-07 17:50
A little description for my PR.
It doesn't care about the caching.
This example is using chunk as property.
It fixes which part is the outer token of the nested tokens (backticks).

**Comment by goldsky** [comment] 2017-07-24 10:15
Any updates on this?
The bounty was hot :)

**Comment by sonicpunk** [comment] 2017-09-14 09:16
No solution has been integrated into the next release, unfortunately.  

Please integrators take a look at this. Maybe one of the solutions can make it into the next release? @Jako @Jako @Mark-H @opengeek @rtripault @pixelchutes @markwillis82 @netProphET

**Comment by zaigham** [comment] 2017-11-05 13:19
So who won the bounty? 🍿

**Comment by sonicpunk** [comment] 2017-11-06 07:47
We are evaluating the issue to determine who won and will be posting the results here. Stay tuned!

**Comment by sonicpunk** [comment] 2017-11-06 09:56
Upon evaluation, @bezumkin's solution ended up being merged, so congratulations!!! We will be contacting you about getting your prize!

**Comment by gpsietzema** [comment] 2017-11-06 10:04
@modxbot close

**Closed by gpsietzema** 2017-11-06 10:04 UTC
Labels: bounty
