### ISSUE TITLE
Upgrade to MODx3 problematic; how to back it out?

### ISSUE THREAD

**Issue by LarsCarlin** [modxcms/revolution#16215] opened 2022-06-28 01:26 UTC
Been running MODx for years, no issues. All upgrades work fine and I upgraded to 2.8.4 before upgrading to 3.0.1. 
However, 3.0.1 has so many errors and issues, I'm thinking it's just best to go back to 2.8.4. I saved a copy of all files and data bases. But first, where do I start to look to solve the 3.0 issues?
1. Upgrade did not throw any errors. Yes, PHP ver is 8.1.
2. Logging into MODx yields this error list:
   /homepages/12/d279960588/htdocs/core/src/Revolution/Processors/Workspace/Packages/GetList.php:218
    MODX\Revolution\Processors\Workspace\Packages\GetList->checkForUpdates(object, Array ( ) ) in /homepages/12/d279960588/htdocs/manager/controllers/default/dashboard/widget.updates.php:78
    modDashboardWidgetUpdates->render() in /homepages/12/d279960588/htdocs/core/src/Revolution/modDashboardWidgetInterface.php:81
    MODX\Revolution\modDashboardWidgetInterface->process() in /homepages/12/d279960588/htdocs/core/src/Revolution/modDashboardWidget.php:134
    MODX\Revolution\modDashboardWidget->getContent(object) in /homepages/12/d279960588/htdocs/core/src/Revolution/modDashboard.php:122
    MODX\Revolution\modDashboard->render(object, object) in /homepages/12/d279960588/htdocs/manager/controllers/default/welcome.class.php:109
    WelcomeManagerController->process(Array ( ) ) in /homepages/12/d279960588/htdocs/core/src/Revolution/modManagerController.php:178
    MODX\Revolution\modManagerController->render() in /homepages/12/d279960588/htdocs/core/src/Revolution/modManagerResponse.php:114
    MODX\Revolution\modManagerResponse->outputContent(Array ( ) ) in /homepages/12/d279960588/htdocs/core/src/Revolution/modManagerRequest.php:173
    MODX\Revolution\modManagerRequest->prepareResponse() in /homepages/12/d279960588/htdocs/core/src/Revolution/modManagerRequest.php:143
    MODX\Revolution\modManagerRequest->handleRequest() in /homepages/12/d279960588/htdocs/manager/index.php:60

4. The Package Manager does not work at all.  Searching localling for installed packages just gives 2 spinning windows saying: "Checking for Updates" and "Loading"

Any tips on going BACK to the last version 2?

**Comment by JoshuaLuckers** [comment] 2022-06-28 11:46
> 2. Logging into MODx yields this error list:

Can you share the error message as well, it only shows the stacktrace of the error/warning but not the actual message itself. 

> 3. The Package Manager does not work at all.

Are there any errors in the MODX error log and/or browser console?

**Comment by zaigham** [comment] 2022-06-28 14:20
> Any tips on going BACK to the last version 2?

Restore from backup? 😅

**Comment by Mark-H** [comment] 2022-06-28 14:24
I suspect that's the error that is resolved by updating the UpgradeMODX or Updater packages, but I haven't heard of that breaking the package manager itself. Just the dashboard.

**Comment by BobRay** [comment] 2022-06-30 05:59
As far as I know, the current version of UpgradeMODX doesn't cause any problems as long as you manually clear the core/cache directory after upgrading to MODX 3. I've upgraded several sites from 2.8.3 to MODX  3.0.0 with no problems.

**Comment by LarsCarlin** [comment] 2022-06-30 14:39
Yes, I follow all procedures carefully, I keep detailed notes on all changes, I've been updating MODx since before 2.x and had no troubles. Yes, I manually clear out the cache. Our main PCs all all Linux based, same as the servers.

Upgrading to 3 is a disaster. I can log in but that's it. Website runs but I can't access it via CMS. And the worst part, not sure why. MODx is throwing so many errors it's not worth tracing them. It's the "Limbo" condition warned about in the documentation, but it never identifies the culprit.
I'll try a clear install of 2.8.4 in a separate dir and maybe also 3.
Thanks for your reply.
Larry Carlin

**Comment by BobRay** [comment] 2022-06-30 19:08
There are a few other things you might want to try first. 

Check the network tab and console tab in Chrome Dev tools (Ctrl-shift-i) while trying to use that Manager.

If there's no clue there, see if you can go directly to a specific manager page after logging in, like 

```
http://yoursite.com/manager/?a=resource/update&id=1
```

If that works, your problem is with the MODX dashboard. You can remove widgets from dashboards in the modx_dashboard_widget_placement table in the DB. Just delete any record there that's on the default dashboard (usually 1). The two "feed" widgets (widgets 1 and 2) are often a problem. You could also delete all the records in that table. That doesn't delete the widgets, it just takes them off any dashboard. If that fixes things, you can put the widgets back one by one in the Manager until you find the culprit.

If that doesn't work, another thing to try would be to disable all plugins in the modx_site_plugins table in the DB.

As far as backing out, no one has yet tried this, but if UpgradeMODX will run, you can set the settings_version system setting back to 2.8.3-pl in the modx_system_settings table in the DB.  Then you can "upgrade" to MODX 2.8.4 in UGM. You'll have a bunch of extra MODX 3 files left over but the Manager may work again. I wouldn't try this unless you're planning to trash the site and go to a backup. In that case you have nothing to lose. If you do try it, let us know if it worked.

**Comment by wshawn** [comment] 2022-07-27 15:44
I had similar issues with MODX3 upgrades. Hopefully you made a backup just before the upgrade which is counter-modx as I can not recall any issues in 12 years doing upgrades. If you have a backup, move the broken install to another location and just reinstall the backup. If you are on a hosting provider ask them for a restore of a weekly or monthly backup. If they are using JetBackup it might or might not work.  Some of my sites I have moved to Drupal 9, others I am going to do a clean rebuild in MODX3.

**Comment by LarsCarlin** [comment] 2022-07-27 16:28
Yes, that is what I did. In the end, I had the latest 2.x version running. But NOT 3.x.

At that point I did a risk-reward analysis and decided it wasn't worth the effort to continue with MODx. Was a dedicated user for almost 10 years but I could no longer afford the overhead. I liked the platform, but in the end I needed a cost-effective business solution.
Maybe I'll play with it out of programming interest and see if I can get a clean MODx 3.0.1 install.
Thanks for your feedback,
Larry Carlin

**Comment by JoshuaLuckers** [comment] 2022-07-27 16:41
MODX Revolution 3.0 is a major version release, we tried to retain as much compatibility with version 2. 
However there are quite a number of changes in Revolution 3 that break compatibility or alter how things work.

There is always a balance to be kept between breaking changes that cleanup technical debt, and not breaking things unnecessarily but we can’t promise that nothing breaks.

2.x will continue to be supported for the forseeable future with patch releases until you can safely make the transition to 3.x.

**Comment by Mark-H** [comment] 2022-07-27 17:22
Sadly you never did post the actual error message (the "list of errors" you posted is the stack trace, not the error itself, which sadly means we can only guess as to what was happening), so we don't have the opportunity to improve the upgrade experience from this report.

As you indicate you've reverted back to 2.x, I'll close this issue, but please do reopen if you get back to trying MODX 3 on your environment so we can investigate further and resolve the problem for future users.

Thanks.

**Closed as completed by Mark-H** 2022-07-27 17:22 UTC

**Comment by LarsCarlin** [comment] 2022-07-27 17:29
The errors were numerous. Bottom line, it installed and the website ran, but I could not log in and that took me 3 days to fix. But from within the manager I had no access to anything. Tried every fix I could think of and finally gave up.

Larry

**Comment by Mark-H** [comment] 2022-07-27 18:16
Well, to reiterate my point, include the "numerous errors" in future reports. We absolutely need that information. We're all happy to help to make the MODX3 upgrade as smooth as possible for a major upgrade, but are limited to what you provide. 

As a rule of thumb: if you get stuck with a problem for more than an hour, post **all details**. Perhaps we've seen it or can interpret it better because we know where it may come from. That way we can help you get to the root cause, and get that resolved much more quickly than you going at it alone for 3 days before giving up. 

Help people help you.

**Comment by ghost** [comment] 2022-10-13 08:27
Same here: after updating to MODX3 the Installer is broken and shows a spinner saying 'Checkin for package updates'. It won't proceed.

**Comment by JoshuaLuckers** [comment] 2022-10-13 08:49
@gerbenb I'm sorry to hear you're having issues as well. We would love to help figure out what's causing this issue.
- Are there any errors in the error log (MODX error log and PHP error log)?
- What version of PHP are you using?
- What's the error in the console of your browser?

**Comment by ghost** [comment] 2022-10-13 08:53
[2022-10-13 10:13:35] (ERROR @ /var/www/vhosts/website.com/httpdocs/core/components/minifyx/model/minifyx/minifyx.class.php : 357) [MinifyX] No file specified; make sure you are using the correct .htaccess rules.
[2022-10-13 10:13:39] (ERROR @ /var/www/vhosts/website.com/httpdocs/core/components/minifyx/model/minifyx/minifyx.class.php : 357) [MinifyX] No file specified; make sure you are using the correct .htaccess rules.
[2022-10-13 10:13:41] (ERROR @ /var/www/vhosts/website.com/httpdocs/core/components/minifyx/model/minifyx/minifyx.class.php : 357) [MinifyX] No file specified; make sure you are using the correct .htaccess rules.
[2022-10-13 10:13:46] (ERROR @ /var/www/vhosts/website.com/httpdocs/core/components/minifyx/model/minifyx/minifyx.class.php : 357) [MinifyX] No file specified; make sure you are using the correct .htaccess rules.
[2022-10-13 10:13:51] (ERROR @ /var/www/vhosts/website.com/httpdocs/core/components/minifyx/model/minifyx/minifyx.class.php : 357) [MinifyX] No file specified; make sure you are using the correct .htaccess rules.
[2022-10-13 10:14:01] (ERROR in MODX\Revolution\Transport\modTransportProvider::latest @ /var/www/vhosts/website.com/httpdocs/core/src/Revolution/Transport/modTransportProvider.php : 264) Could not load updates for minifyx-1.7.1-pl: The requested package is not available from mod<b>more</b>.
[2022-10-13 10:15:17] (ERROR in MODX\Revolution\Transport\modTransportProvider::latest @ /var/www/vhosts/website.com/httpdocs/core/src/Revolution/Transport/modTransportProvider.php : 264) Could not load updates for minifyx-1.7.1-pl: The requested package is not available from mod<b>more</b>.
[2022-10-13 10:15:38] (ERROR in MODX\Revolution\Transport\modTransportProvider::latest @ /var/www/vhosts/website.com/httpdocs/core/src/Revolution/Transport/modTransportProvider.php : 264) Could not load updates for minifyx-1.7.1-pl: The requested package is not available from mod<b>more</b>.

PHP 8.0.3

There are no actual console errors, except:
Privacy Badger failed to set navigator.globalPrivacyControl, probably because another extension set it in an incompatible way first.

**Comment by ghost** [comment] 2022-10-13 08:59
I can see in SiteDash there are two extra's that have an update available:
minifyx-1.7.1-pl
modDevTools v1.2.1-pl

They both happen to be installed through provider modstore.pro.

Updating them through SiteDash says:
Received error when checking for updates: provider_err_connect

**Comment by ghost** [comment] 2022-10-13 09:04
I managed to download and install them in the Package Installer with the green button 'Download extra's. I think this is not an update, but just a new installation of these extra's; there was no classic update/setup-proces. I'm not sure if actions from my side are needed now after installing these packages or if everything is 'fine'.

The Installer now shows all of the Packages again.

**Comment by Jako** [comment] 2022-10-14 08:46
Both extras are updated on the MODX extras but not on modstore.pro. It should help to change the transport provider for both extras. MinifyX has some breaking changes between 1.7.1 and 2.x - some parts are removed. See https://github.com/Jako/MinifyX/blob/master/core/components/minifyx/docs/changelog.md

**Comment by ghost** [comment] 2022-10-14 14:45
Yeah, but when the manager won't load, selecting a different provider is difficult 😒.
So far the updating to MODX 3 results in several problems accros the different sites. I think only 1 went well.

**Comment by BobRay** [comment] 2022-10-15 03:09
If you have access to the DB, you can add a provider in the `modx_transport_providers` table, then make a note of its ID and use that for the `provider` field in the `modx_transport_packages` table.
