### ISSUE TITLE
Manager top bar dropdowns getting in the way of Save

### ISSUE THREAD

**Issue by jimbob72** [modxcms/revolution#12402] opened 2015-03-31 13:34 UTC
Having made lots of changes to an asset/element etc. I drag my cursor up to the top right to Save. But in my haste I over drag, hit the Cog or User name button in the top bar, and just as I'm clicking, the drop down appears and instead of Saving my item I click on Edit Account or System Settings - thereby losing all the changes I've just made.

Maybe I am too hasty in the way I drag my mouse and click, but this happens A LOT and it is extremely frustrating. Any chance the top bar Cog and User buttons could be moved next to the other top bar buttons (Extras, Manage etc.)?

**Comment by pixelchutes** [comment] 2015-04-01 05:26
Closing as duplicate of #12062 - available for further discussion there.

**Closed by pixelchutes** 2015-04-01 05:26 UTC
