### ISSUE TITLE
File upload window display/function without page refresh

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12286] opened 2015-01-21 15:39 UTC
When you use the file manager to upload a file then go and select the same file to upload again, the file upload box will not display the file.  One must refresh the page in its entirety to re-upload the same file.

**Comment by pixelchutes** [comment] 2015-01-23 03:22
Dupe of #12128, fixed. (MODX v2.3.3-dev)

**Closed by pixelchutes** 2015-01-23 03:22 UTC
