### ISSUE TITLE
Forgot your login can be used to determine valid usernames

### ISSUE THREAD

**Issue by islandsins** [modxcms/revolution#13427] opened 2017-04-19 14:49 UTC
### Summary
The Forgot your Login feature presents different messages depending on whether the username or email address you provide is a valid account or not.  This enables an attacker to determine if a username is valid or not which could assist them in the early stages.

### Step to reproduce
Go to the manager login page
Click 'Forgot your login'
Enter an invalid username and click 'Send Activation Email'
Note the message confirming account does not exist 'User not found with that email or username. Please try again.'
Enter a valid username and click 'Send Activation Email'
Note the message confirming username is valid 'Password Reset Activation email sent. Please check your inbox.'

### Observed behavior
Messages shown 'User not found with that email or username. Please try again.' and 'Password Reset Activation email sent. Please check your inbox.' which allows determining valid accounts.

### Expected behavior
The software should not confirm or deny the existence of an account, and instead provide the same message in both cases, eg something like 'If there is a valid account associated with the username or email provided you will shortly receive a password reset email'.  Whilst this is a little less user friendly it does prevent confirming valid accounts which could then be subject to attempts to obtain the correct password.

### Environment
MODX 2.5.6

**Comment by mrhaw** [comment] 2017-04-19 16:56
Good report! See this issue already open https://github.com/modxcms/revolution/issues/13408

**Comment by Mark-H** [comment] 2017-04-19 19:52
Closing as dupe of #13408 as @mrhaw mentioned. Interesting how this has been around for years, and over the span of two short weeks it gets reported twice :D

**Closed by Mark-H** 2017-04-19 19:52 UTC

**Comment by islandsins** [comment] 2017-04-20 07:52
Apologies for not spotting it was already reported, not sure how I missed it.
