### ISSUE TITLE
$options parameter in modx::getChildIds not fully supported

### ISSUE THREAD

**Issue by skybluesofa** [modxcms/revolution#12536] opened 2015-08-07 16:51 UTC
The modx::getChildIds() method doesn't seem to fully support the 3rd parameter, $options. It only seems to support a 'context' element in that array.

**Comment by Mark-H** [comment] 2015-08-07 20:55
What are you looking to have supported? I think context is indeed the only option currently in there.

**Comment by skybluesofa** [comment] 2015-08-08 13:24
I was looking for a way to filter all descendants of a certain resource. I assumed the $options parameter would allow me to send a query object to filter the results.

Perhaps I just need to use a pdo query instead? Being new(er) to modx, I'm not quite sure how all the pieces fit together yet.

**Comment by Mark-H** [comment] 2015-08-11 20:31
getChildIds doesn't accept an xPDOQuery or PDO stuff unfortunately - it's just a quick (cached) way to get a tree of children under a certain resource. You can do more filtering with it after that, I have in the past created a new query that used the IDs from getChildIds to restrict the search to only those.

**Comment by OptimusCrime** [comment] 2016-04-26 23:48
Looks like this is by design. Closing this. Feel free to reopen or comment if you have further thoughts or feedback.

@modxbot close

**Closed by OptimusCrime** 2016-04-26 23:48 UTC
