### ISSUE TITLE
Combine update scripts

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15220] opened 2020-08-30 12:57 UTC
### Summary
In the process of working with PR, update scripts are created that affect the same entities, for example, TV or System Settings:
https://github.com/modxcms/revolution/tree/3.x/setup/includes/upgrades/common

I think, before the 3.x branch is released, it makes sense **to combine the update scripts for the entities and remake them according to the template**. For example, for System Preferences it will become:
- `3.0.0-create-system-settings.php`
- `3.0.0-update-system-settings.php`
- `3.0.0-delete-system-settings.php`

And for other entities, simplify scripts in a similar way.

### Why is it needed?
Work with update scripts will be simplified.
And they won't be created indefinitely for each PR :)

**Comment by alroniks** [comment] 2020-08-31 06:16
These updater scripts are kind of migrations. Migrations best practices already described and tested on thousands of projects, so no need to reinvent the wheel. 

You as a developer always to be sure that your application will work after your changes, if changes touche the database, you should provide the way how to achieve the state after your changes. The application always should be stable, whenever you do. 

Every migration should be atomic and simple, which will give a chance to developer revert changes and rollback migration, of you combine all in one place it becomes a headache in case any unexpected behavior.

I vote against such an approach.

**Comment by Ruslan-Aleev** [comment] 2020-08-31 07:22
You do not quite understand me. I meant to combine exactly similar scripts.
For example, https://github.com/modxcms/revolution/blob/3.x/setup/includes/upgrades/common/3.0.0-update-upload_files-upload_images.php and https://github.com/modxcms/revolution/blob/3.x/setup/includes/upgrades/common/3.0.0-update-upload_files-woff2.php
Those, as a result there will be one migration script with a common array of settings keys, instead of 2 migration scripts.
Naturally, merge should be done only where it makes sense, and not all files should be merged into one.

**Comment by alroniks** [comment] 2020-08-31 07:26
In this case, it makes sense, but it should be fixed in a small pull request, no need to review all existing scripts. They are pretty simple and work, no need to spend time on it when we have other things to do, which are more important.

**Comment by Ruslan-Aleev** [comment] 2020-08-31 07:29
> no need to spend time on it when we have other things to do, which are more important.

That's why I indicated this issue as "Feature request", not a very important question.

**Comment by theboxer** [comment] 2020-09-23 13:16
I don't think I agree. Those upgrade scripts are linked with other changes to the repo, to the PR and possible also to an issue.
I think they are fine as they are right now. You wouldn't go and start merging migrations together because they seemed to be related.

**Comment by alroniks** [comment] 2021-03-30 21:59
Closed as won't fix.

**Closed as completed by alroniks** 2021-03-30 21:59 UTC
