### ISSUE TITLE
Cache clear every time

### ISSUE THREAD

**Issue by play2web** [modxcms/revolution#13092] opened 2016-08-18 12:59 UTC
### Summary

Complete cache is cleared even checkbox for emty cache is unchecked
### Step to reproduce

Try to create new resource, when tou save it, cache is cleared
### Observed behavior

How it behaved after following steps above.
### Expected behavior

When you create new resource, when empty cache is unchecked, do not delete cache
### Environment

MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by gpsietzema** [comment] 2016-10-25 09:43
@play2web I was unable to reproduce this. Are you aware of the Resource-setting "Empty cache" default back to "checked" if you re-open a resource? Please check my attached video.
[modx-13092.zip](https://github.com/modxcms/revolution/files/550203/modx-13092.zip)

**Comment by Mark-H** [comment] 2017-02-09 18:03
Closing as not reproducable. Feel free to provide more information if it's still accurate.

**Closed by Mark-H** 2017-02-09 18:03 UTC
