### ISSUE TITLE
MODX 2.4.0 reverses handling of OnBeforeManagerLogin and OnBeforeWebLogin

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12620] opened 2015-08-31 03:58 UTC
In 2.3.6 and earlier, returning array(true) from  a plugin attached to these events passes the user and allows the login.  In 2.4.0, you have to return false, '', or array(false) to pass the user.

This breaks the Captcha plugin (people using Captcha can't log in after upgrading). It will break any other plugin that rejects users using those events. I've patched Captcha for this, but I had to do a version check and I'm not sure if this change was intended or not.

I don't know whether to release the new version of Capta because it will be broken if the change is reverted. Please advise.

**Comment by rtripault** [comment] 2015-08-31 04:53
Duplicate of #12595, so closing in favor the mentioned issue.

Feel free to comment/reopen if needed.
Thanks

**Closed by rtripault** 2015-08-31 04:53 UTC
