### ISSUE TITLE
Dragging of files and folders in Files tab in left bar does not work in MODX 2.8.4-pl

### ISSUE THREAD

**Issue by deJaya** [modxcms/revolution#16194] opened 2022-05-24 08:45 UTC
### Summary
When attempting to drag files or folders in the Files tab, the UI suggests that the move will be successful, but it fails.

### Step to reproduce
In MODX 2.8.4-pl, in the left column, use the Files tab to drag files or folders into new locations.

### Observed behavior
A green + will appear when you drag and hover over an acceptable folder. However, on release, the tree will refresh [collapsed] and the move has not taken place.

### Expected behavior
The file or folder should be moved to the new location.

### Environment
MODX 2.8.4-pl PHP 8.1.6

**Comment by Ruslan-Aleev** [comment] 2022-05-25 12:15
I confirm there is a bug:

![dd_tree](https://user-images.githubusercontent.com/12523676/170259593-af95e156-1f1b-4a4b-aecf-16372ce30237.gif)

**Comment by smg6511** [comment] 2022-06-03 04:04
This is actually caused by the changes from PR #16071. That needs to be reverted.

**Comment by JoshuaLuckers** [comment] 2022-08-11 07:00
The PR solving this issue has been merged, therefore I'm closing this issue. Thanks for reporting and help make MODX better.

**Closed as completed by JoshuaLuckers** 2022-08-11 07:00 UTC
Labels: bug
