### ISSUE TITLE
TV default value isn't getting saved

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#12386] opened 2015-03-12 13:54 UTC
I have a TV (type Listbox Multiselect) set to have a default value, and that default value shows up in the editing when when I have the resource open. But when I save the resource, the default value does not get saved into the database. Shouldn't that be what happens? Otherwise there is no way to search for resources that have that value.

Revo 2.3.3

**Comment by pixelchutes** [comment] 2015-03-13 04:34
The behavior you've described is by design for all TV types with a default value.

The flipside to the this problem is that if you want/need to *change* the default value down the road, then you'd end up having a bunch of stale records previously relying on the original fallback value that then would all need updating to remain in sync.

**Comment by rainbowtiger** [comment] 2015-03-13 12:48
Yes, the problem you describe occurred to me, but the fact remains that you can't search for the default value. If you're using a multiselect listbox, you can select the default value and a second value, in which case the default value WILL get saved into the database. If you then change the resource and delete just the second value, the entire TV record gets deleted rather than leave the default value in. What if you want to change the default value to a different one, having that affect all future entries, but have all records currently entered retain the old one, since they were saved that way? You're out of luck. It seems a far better idea to save the default value specifically, since it would be an easy matter to globally replace that default value in the TV data table if you wanted to change it to something else and have all current entries change as well.

**Comment by pixelchutes** [comment] 2015-03-14 16:58
Exactly! I wonder if there are any other implications that decided the original solution? Still, doesn't mean it can't be changed for the next version of MODX. Seems having the entry in the database would be more consistent.

**Comment by alroniks** [comment] 2021-04-01 20:17
I am closing this one as we have a detailed and more common issue that covers more cases. Move discussion here please https://github.com/modxcms/revolution/issues/14945 if you want.

**Closed by alroniks** 2021-04-01 20:17 UTC
