### ISSUE TITLE
Can no longer drag files to other folders in the Files tree in 2.8.4

### ISSUE THREAD

**Issue by pmacswebteam** [modxcms/revolution#16306] opened 2022-11-23 18:07 UTC
### Summary
Can no longer drag files to other folders in the Files tree. 

We are seeing the same issue that was reported in #15694 except that we are seeing it after upgrading from 2.8.3 to 2.8.4.

### Step to reproduce
Upload a file. Attempt to drag it into another folder.

### Observed behavior
The tree collapses and refreshes and the file does not appear in the desired folder, it remains where it was.

### Expected behavior
The file should be moved to the folder it was dragged to.

### Environment

Observed on sites upgraded from 2.8.3 to 2.8.4. PHP 7.3. Apache with MySql 10.4.15-MariaDB. Seen in Chrome and Firefox.

**Comment by halftrainedharry** [comment] 2022-11-24 09:45
It's seems, the cause of the problem is, that the request parameters for the paths are urlencoded (`myfolder%2Fmyfile.jpg` instead of `myfolder/myfile.jpg`).

---

Can you try changing lines 29 and 31 here

https://github.com/modxcms/revolution/blob/f08c189d05053d5a6cd10b6b0f4028434147071b/core/model/modx/processors/browser/directory/sort.class.php#L29-L31

to
```
$from = rawurldecode($this->getProperty('from'));
```
and
```
$to = rawurldecode($this->getProperty('to'));
```
respectively, and check if that works?

**Comment by smg6511** [comment] 2022-11-24 17:01
This is fixed in the forthcoming release for 2.8.5. See PR #16202.

**Comment by pmacswebteam** [comment] 2022-11-28 15:53
Looks like I've created duplicate issue. Sorry about that!

Thanks @halftrainedharry the change you described seems to fix the problem we are having for now.

**Comment by Ibochkarev** [comment] 2022-11-28 17:31
Fixed https://github.com/modxcms/revolution/pull/16202

**Closed as completed by Ibochkarev** 2022-11-28 17:31 UTC
