### ISSUE TITLE
[3.x] Static file field showing by default when creating an element.

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#16096] opened 2022-03-19 05:48 UTC
### Summary
When opening the create element page (applies to all types), the static file field is visible even before the "is static" checkbox is checked.

![Screenshot 2022-03-19 at 13-41-31 Create Snippet MODX Revolution](https://user-images.githubusercontent.com/5160368/159108893-22222fc8-042c-4df5-9e4e-7e9439660e65.png)

### Step to reproduce
Open a create new snippet/chunk/plugin page.

### Observed behavior
Toggling the is static checkbox behaves correctly, it's just the initial page load. I assume it's not set to hidden by default.

### Expected behavior
It should be hidden until the is static checkbox is clicked.

### Environment
Latest 3.x branch

**Comment by smg6511** [comment] 2022-03-20 16:49
This will be taken care of for all Element panels via a set of PRs that will be submitted soon. They will match the look and behavior of the TV panel. My base PR for this (#16012) is very close to getting merged; this contains the base methods and the Resource panel implementation. The Elements implementation is ready and will be submitted after that.

**Comment by Ruslan-Aleev** [comment] 2022-03-20 17:20
I can't reproduce the bug. Don't see the field by default (MODX 3 with latest commits).

**Comment by muzzwood** [comment] 2022-03-21 04:04
@smg6511 Ah I see! The TV panel looks fantastic. 💯

**Comment by JoshuaLuckers** [comment] 2022-03-25 10:07
With the latest nightly the static file field is still visible for me.

**Comment by Ruslan-Aleev** [comment] 2022-03-25 10:13
@JoshuaLuckers I checked via git-console, not sure if nightly builds are up to date.

**Comment by JoshuaLuckers** [comment] 2022-03-25 10:21
@Ruslan-Aleev it's an up-to-date nightly (published yesterday by Jason). 

I also tried with the most recent source and the field is still there as well.

**Comment by Ruslan-Aleev** [comment] 2022-03-25 10:32
Yes, my mistake, updated everything, including `composer update` - now I have a problem too.

**Comment by Ruslan-Aleev** [comment] 2022-03-25 10:47
@smg6511 Can you fix this bug? Because it appeared after edits in https://github.com/modxcms/revolution/pull/16082.
The https://github.com/modxcms/revolution/pull/16012 also don't fix this bug (or I missed something. Although I have updated everything including composer update)
And waiting for a correction in a new PR after merging another PR is not productive, as it seems to me.
This would be useful to fix before the release of MODX 3, which is just around the corner :)

**Comment by smg6511** [comment] 2022-03-25 15:12
I'm on it guys. That just didn't get caught in the review of #16082. @Ruslan-Aleev - This bug has no direct relation to #16012, but the UI changes its follow-up PRs make (that match the TV panel UI) happen to side-step it; that's not the solution though and I see now that I look again why it's happening. Easy fix coming...

**Comment by Ibochkarev** [comment] 2022-03-28 19:54
Fixed #16102

**Closed as completed** 2022-03-28 19:55 UTC
Labels: bug
