### ISSUE TITLE
Unknown column 'modContentType.icon' in 'field list'

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15509] opened 2021-03-07 09:34 UTC
### Summary
After upgrading from version 2.8.1 to nightly build modx-3.0.0-alpha3-20210301 errors appear in the error log

### Step to reproduce
Install a clean build of version 2.8.1 before the nightly build modx-3.0.0-alpha3-20210301 and check for errors in the error log. Before upgrading, set the system setting log_level to 4

### Observed behavior
``` shell
[2021-03-07 12:21:57] (ERROR @ /home/s25444/www/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 227) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'modContentType.icon' in 'field list'
)

[2021-03-07 12:21:57] (FATAL) The requested resource has no valid content type specified.
```

### Expected behavior
There should be no errors or warnings

### Related issue(s)/PR(s)
NA

### Environment
modx-3.0.0-alpha3-20210301, PHP Version 7.3.24-3

**Comment by Mark-H** [comment] 2021-03-08 17:35
Hmm, did you no errors during the install? There is a migration for modContentType.icon so it's weird that's not there.

**Comment by Mark-H** [comment] 2021-03-08 17:39
Duplicate of #15504

**Comment by Ibochkarev** [comment] 2021-03-08 17:40
> Hmm, did you no errors during the install? There is a migration for modContentType.icon so it's weird that's not there.

I will repeat the upgrade tomorrow from a clean 2.8.1 to a nightly build 3.0

**Closed as completed by Mark-H** 2021-03-08 17:39 UTC
