### ISSUE TITLE
Error Log view

### ISSUE THREAD

**Issue by osabate** [modxcms/revolution#12743] opened 2015-10-30 22:17 UTC
Utilize full height or allow manual resizing. Otherwise text feels cramped in the text box, forcing too much scrolling.

![screen shot 2015-10-30 at 3 16 50 pm](https://cloud.githubusercontent.com/assets/1790449/10859281/507d416c-7f19-11e5-99f9-181405bc9fbf.png)

**Comment by rtripault** [comment] 2015-10-31 13:07
FWIW, duplicate of #5942.
All in all, PR sent to fix that behavior

**Closed by rtripault** 2015-10-31 13:07 UTC
