### ISSUE TITLE
Use double quotes in pagetitle row

### ISSUE THREAD

**Issue by JiminikJilis** [modxcms/revolution#13678] opened 2017-11-06 12:45 UTC
### Summary
If you use double quotes in field pagetitle, then when you edit the resource, there is a JavaScript error: Uncaught SyntaxError: Unexpected identifier

2.6.*: https://github.com/modxcms/revolution/blob/bfb083cdd6800f7f5b90dcae266a95b51c2ffae9/manager/controllers/default/resource/update.class.php#L45

2.5.* (absent 'pagetitle'):
https://github.com/modxcms/revolution/blob/bf1c301bdea4fdb8d08a8783e073cdf1ba6ef094/manager/controllers/default/resource/update.class.php#L45

### Environment
2.6.0

**Comment by Jako** [comment] 2017-11-06 12:51
Duplicate of #13664. Fixed with #13669.

**Closed by Jako** 2017-11-06 12:51 UTC
