### ISSUE TITLE
User extended fileds not displayed in tree

### ISSUE THREAD

**Issue by neverfan** [modxcms/revolution#10189] opened 2013-09-10 22:39 UTC
neverfan created Redmine issue ID 10189

User extended fileds not displayed in tree when edit user data in admin panel.

How to reproduce:
1)Open any user
2)Open tab with extended fields
3)Create field with any name and set value on russian language, value must be have more 15 charcters and one of the following symbols (space, "-","=","+", etc), example: "????????????? ??" or "?????????????-??"
4)Save user data
5)Reload (F5) user edit page
6)Open tab with extended fields and look at tree

ps: If look on config.data in MODx.orm.Tree (manager/assets/modext/widgets/core/modx.orm.js) i see object field "text" with "null" value returned.

**Comment by bezumkin** [comment] 2018-04-09 13:09
![screen shot 2018-04-09 at 15 08 09](https://user-images.githubusercontent.com/1257284/38499458-e61db208-3c07-11e8-83d2-936a65a8d2f1.png)

I see no problem here anymore.
Maybe it was related to old PHP version because of JSON encode\decode for extended user fields.

Tested on MODX 3.0-dev and PHP from 5.6 to 7.2

**Comment by OptimusCrime** [comment] 2018-04-10 08:55
I suggest closing it then.

**Comment by alroniks** [comment] 2018-07-19 14:39
Tested also on 2.7.0-dev, not reproducible. So closing.

**Closed by alroniks** 2018-07-19 14:39 UTC
Labels: bug
