### ISSUE TITLE
Saving Issue

### ISSUE THREAD

**Issue by EkoOne** [modxcms/revolution#12722] opened 2015-10-15 05:11 UTC
Revo 2.4.2

This may very well be specific only to my installation and not a bug. Regardless, I would appreciate some insight, if possible.

After updating to 2.4.2 from 2.4.1 I'm having a problem saving certain types of fields. Specifically I can't save Property Set fields or certain System Settings.

When saving a Property Set text field the page hangs in the middle of the refresh. The "Loading..." icon appears but that's where it stops until I manually refresh the browser window which discards any changes.

In System Settings when changing the value of a picker the page jumps upwards cutting off the MODX menu bar but the change is not saved. It too hangs in the process of saving changes.

I've run through the entire upgrade process several times with no change. I've also repaired the db tables and cleared the cache. Everything was working fine with 2.4.1.

I'm at a loss and really need to get this resolved.

**Comment by sottwell** [comment] 2015-10-15 09:17
This may be an everything-is-a-nail viewpoint, but I suspect mod_security. See if you can have your hosting provider take a look at their mod_security logs. A new ruleset is making the rounds, and causing all kinds of weird problems with saving different things.

**Comment by whitebyte** [comment] 2015-10-15 12:04
@ImXiiro there was a property set bug in 2.4.0 and 2.4.1 (#12580) Fixed in 2.4.2 but there is a chance you database was already corrupted before the update.

**Comment by ImXiiro** [comment] 2015-10-15 14:38
@sottwell I will contact the host. Is there something specific they should be looking for regarding the mod_security logs or would a problem be plainly obvious?

@whitebyte If you're right is there a way to manually fix it or am I stuck?

I'm just guessing but...the host allows for switching PHP versions (currently 5.6 w/ default module settings) so is it possible that a needed module is disabled and that's causing the problem? Although there were no errors when updating.

**Comment by whitebyte** [comment] 2015-10-15 14:59
@ImXiiro first thing to do is to check if this bug occurs on fresh install.

**Comment by ImXiiro** [comment] 2015-10-15 22:21
@sottwell You are a sharp cookie. The client's cPanel allows for disabling mod_security which I did and I'm now able to save. Woo-hoo! Of course I can't leave it off.

I haven't yet asked the host to check the mod_security logs but given that disabling it works does this in fact mean the problem is on the server end or could it still be a MODX issue?

**Comment by whitebyte** [comment] 2015-10-16 09:01
https://rtfm.modx.com/revolution/2.x/getting-started/installation/basic-installation/installation-on-a-server-running-modsecurity

**Comment by ImXiiro** [comment] 2015-10-16 20:27
@whitebyte Thanks for the link, very interesting. Since I'm dealing with a client site on a shared server I'm not sure their host will take kindly to my poking around at this level. I'm reluctant to attempt something that could adversely affect their hosting account.

@sottwell The host confirmed there are a "few" rules being tripped. They can't (or won't) disable specific rules. It's either all on or all off.

**Comment by adamwintle** [comment] 2016-01-13 22:32
I think this is a server-specific issue and not actually a core MODX issue, plus the link above about mod_security looks like a good one. I'm going to close this for now, if this actually turns out to be a core MODX bug we can reopen the issue. @modxbot close

**Closed by adamwintle** 2016-01-13 22:32 UTC
