### ISSUE TITLE
Nightly build update dublicate colum errors

### ISSUE THREAD

**Issue by crystaldaking** [modxcms/revolution#15585] opened 2021-03-24 12:40 UTC
### Summary
When updating the build using the "classic" method using setup, there are errors

<img width="883" alt="Снимок экрана 2021-03-24 в 13 09 12" src="https://user-images.githubusercontent.com/25440397/112311826-2ace5080-8cb7-11eb-8554-8a5393004c4e.png">

### Step to reproduce
Install the March 9 version of MODX 3 and update with the latest available build

### Observed behavior
System updates occur with errors

### Expected behavior
The database is updated correctly

### Environment
MODX 3 Nightly (23 March build) , nginx (latest), mysql 5.7, microsoft edge, php 7.4

**Comment by Mark-H** [comment] 2021-03-24 12:44
Unless you're experiencing issues where the database columns are **not** created or something behaves out of the ordinary after the setup, those errors are expected and completely safe to ignore. You're bound to get those when repeating an install or when installing alpha (and possibly even beta/rc versions) because most migrations are bound to the version number (i.e. 3.0.0) and not the specific release (i.e. 3.0.0-alpha1). 

Will also definitely happen with nightlies. It's nothing to worry about.

**Comment by Mark-H** [comment] 2021-03-24 12:46
Closing as duplicate of #15462

**Closed as completed by Mark-H** 2021-03-24 12:46 UTC
