### ISSUE TITLE
Actions are ignoring the haslayout parameter

### ISSUE THREAD

**Issue by fireproofsocks** [modxcms/revolution#773] opened 2014-01-03 17:54 UTC
When building custom manager pages (CMPs), an action and menu item are added so that manage users can navigate to the custom manager page.

The problem is that on the custom pages, the MODX manager JS and CSS and HTML *always* load, no matter what the setting of "haslayout" -- in fact in 2.2.10, the "Has Layout" checkbox is missing (it's been AWOL for a few versions).  

This is problematic because as we know, the MODX manager is bloated with sooooo much JS.  I've had to resort to putting a controller file in assets/ so I can be sure that my custom Ajax calls don't trigger MODX trying to load up its army of Ext JS demons.

So the solution is here:

1. Restore the "Has Layout" checkbox to the add/edit action forms.
2. Make sure that ONLY the action output appears on pages that omit the MODX layout.

**Comment by OptimusCrime** [comment] 2016-08-09 06:28
The `haslayout` which was the original issue reported here was deprecated in 2.2.0 and is by design. https://github.com/modxcms/revolution/commit/16cf6ae6ba191406e6cdc240602c724d61bdb14f

I'm in favor of closing this as no documentation for 2.3 extra development mentions this options and the issue should be resolved.

Feel free to reopen this issue or comment if you feel otherwise.

@modxbot close

**Closed by OptimusCrime** 2016-08-09 06:28 UTC
