### ISSUE TITLE
[feature] Add a link to the site from the site name in top

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14218] opened 2018-12-26 18:35 UTC
### Summary
1) In the top on the site name it makes sense to hang a link to go to the site, I think.
The feature is not very useful, but reduces the number of clicks to go to the site **twice :)** and simplifies the menu settings a bit in the permission settings.
```
.site_name a {
color: #5ABCE5;
padding: 0;
line-height: normal;
}
```

![site_title_2](https://user-images.githubusercontent.com/12523676/50454032-4cb4bd80-095e-11e9-80dd-30cd8ba94a17.png)

2) If the site name does not fit into the area, then a tip appears with the full name, but there is also a title attribute with the same name. The title attribute, in my opinion, is not needed.

![site_title_1](https://user-images.githubusercontent.com/12523676/50454030-4cb4bd80-095e-11e9-9839-5ef14ae452b6.png)

**Comment by JoshuaLuckers** [comment] 2018-12-28 14:49
It would be nice to include this in MODX 3.

**Comment by Ruslan-Aleev** [comment] 2018-12-28 15:28
@JoshuaLuckers In my opinion, this can be implemented in 2.7.x, too. The changes are not fundamental, also with PR - https://github.com/modxcms/revolution/pull/14217 :)

**Comment by Ruslan-Aleev** [comment] 2018-12-28 15:37
@JoshuaLuckers By the way, where is the name of the site in MODX3?

![modx3_site_name](https://user-images.githubusercontent.com/12523676/50520135-0b481d80-0ad8-11e9-979e-fab33f6635cd.png)

**Comment by JoshuaLuckers** [comment] 2018-12-28 15:43
The changes you propose are a new feature and not a bug fix. The current behaviour of displaying the site name in the manager is not broken and works as intended.
In my opinion 2.7.x releases should contain bug fixes only and PR #14217 is in my opinion a bug fix therefore it should be included in 2.7.x.

> @JoshuaLuckers By the way, where is the name of the site in MODX3?
> 
> ![modx3_site_name](https://user-images.githubusercontent.com/12523676/50520135-0b481d80-0ad8-11e9-979e-fab33f6635cd.png)

The arrow in your screenshot points to the site name.

**Comment by Ruslan-Aleev** [comment] 2018-12-28 15:53
There is a standard version name in the project, right? Did not think about it, you can share information about numbering.

As I understand it, the logic is this:
2.x.x. - bug fixes,
2.x.0. - new features, right?

If yes, then MODX3 will be after which version, 2.7.5, 2.8.5 or 2.9.5?

**Comment by JoshuaLuckers** [comment] 2018-12-28 17:57
More info about the "numbering": [Semantic Versioning](https://semver.org).

2.7.x is the last release for 2.x.

**Comment by Ruslan-Aleev** [comment] 2018-12-28 19:12
Yes, thanks for the information, now clearer. But still, it seems to me, changes like this issue are not functional.
This is how to fix the css style - code changed, but not fundamental :)

**Comment by alroniks** [comment] 2018-12-29 08:07
@Ruslan-Aleev Rules are pretty simple and clear: all features and enhancements should go to 3.x, 2.x only for bugfixes of the current version. 
> If yes, then MODX3 will be after which version, 2.7.5, 2.8.5 or 2.9.5?

Usually, it works as you described, but there was made the decision make 2.7 last release of 2.x.

**Comment by Mark-H** [comment] 2018-12-29 11:48
I added this into #14225

**Comment by JoshuaLuckers** [comment] 2019-01-09 19:26
I'm closing this because PR #14225 is merged.

**Closed as completed by JoshuaLuckers** 2019-01-09 19:26 UTC
Labels: type-frontend, proposal
