### ISSUE TITLE
Deleting user using API `$modx->user->remove()` throws error

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12434] opened 2015-05-12 04:30 UTC
### Summary
Deleting user using API `$modx->user->remove()` throws error

### Step to reproduce
`$modx->user->remove()`

### Observed behavior
```
[2015-05-12 11:23:58] (ERROR @ /modx-revo-test/www/assets/components/test/conn/w.php) Could not get table class for class: modAccess
[2015-05-12 11:23:58] (ERROR @ /modx-revo-test/www/assets/components/test/conn/w.php) Could not get table name for class: modAccess
[2015-05-12 11:23:58] (ERROR @ /modx-revo-test/www/assets/components/test/conn/w.php) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `modAccess` WHERE `modAccess`.`principal` = 4' at line 1
)
```
User & profile are deleted, though.

### Expected behavior
Exit clean.

### Environment
```php
$v= array ();
$v['version']= '2'; // Current version.
$v['major_version']= '3'; // Current major version.
$v['minor_version']= '3'; // Current minor version.
$v['patch_level']= 'pl'; // Current patch level.
$v['code_name']= 'Revolution'; // Current codename.
$v['distro']= '@sdk@';
```

**Comment by pixelchutes** [comment] 2015-05-14 00:52
Closing as duplicate of #11276

**Closed by pixelchutes** 2015-05-14 00:52 UTC
