### ISSUE TITLE
Attempts to Save Resources & Elements

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12062] opened 2014-10-15 21:37 UTC
Is it just me or has anyone else had this user interface experience with the 2.3 manager version?  I have my resource, template variable or  whatever all configured, move my mouse cursor up to the corner to press save and go a little too far and accidentally trigger the Edit Account drop down from above losing all my changes.

**Comment by pyrographics** [comment] 2015-01-26 18:03
I think I'll post here every time I screw up 5 minutes of work because of this. ;)

**Comment by Ruslan-Aleev** [comment] 2019-02-12 21:36
Probably should close this issue.
In the MODX3 menu is located on the left.

**Comment by Jako** [comment] 2019-02-12 22:07
Duplicate of #12887 which was fixed with https://github.com/modxcms/revolution/commit/79ed131f1b163a71270964a3d6ff687d25b3f2bf

**Closed by Jako** 2019-02-12 22:07 UTC
Labels: area-ux/ui, bug
