### ISSUE TITLE
Issue when Creating Static Resource

### ISSUE THREAD

**Issue by CamilleBeaute** [modxcms/revolution#12431] opened 2015-05-06 16:13 UTC
When creating a static resource, the "Content Type" setting used to change automatically to accommodate for PDFs, however, now it defaults to HTML and causes the following to display:

![screen shot 2015-05-06 at 12 12 27 pm](https://cloud.githubusercontent.com/assets/7905823/7497573/51cace4c-f3e9-11e4-964f-479bf1e1a53e.png)

**Comment by OptimusCrime** [comment] 2015-05-08 20:39
The issue is that the content type does not switch to pdf by itself? Never knew it it did that by default. Can anyone confirm?

**Comment by pixelchutes** [comment] 2015-05-09 04:25
I cannot say I knew it did that either, I've always had to manually set... Can you provide a version of MODX where you know this to have been the case, and also the version you're testing against now?

**Comment by OptimusCrime** [comment] 2015-06-09 22:51
Suggest closing

**Closed** 2015-06-10 09:48 UTC
