### ISSUE TITLE
Chunk process issue

### ISSUE THREAD

**Issue by nsuomine** [modxcms/revolution#16121] opened 2022-04-05 08:55 UTC
### Summary
Chunk processing returns wrong results, maybe from cache?

### Step to reproduce
*$nav= $modx->newObject('modChunk')->process($properties, $tpl);*

The above code line is from getPage snippet that got broken when I upgraded to Modx3. It seems that the above line returns the previous result even though the parametre $tpl has changed. Is the result coming from a cache?

### Expected behavior
The chunk should be processed, not returning a result from cache.

**Comment by halftrainedharry** [comment] 2022-04-05 12:09
I assume you are talking about the page navigation of the extra _getPage_ (that isn't correct in MODX3).

As far as I can tell, the chunks were also cached in MODX 2.x.
But now in MODX3 the tags (`$this->_tag`) that are used as the cache key are different than in version 2 and they somehow sometimes have the same value for different calls. (I don't know why, though.)

https://github.com/modxcms/revolution/blob/8a0d67de4438395a6e82261ddd896dd0e745eeda/core/src/Revolution/modElement.php#L373-L375

The easiest solution to fix the problem quickly is probably to change the code of the _getPage_ extra and set `$chunk->setCacheable(false);`

**Comment by nsuomine** [comment] 2022-04-05 12:20
Yes, I was referring to the extra _getPage_. 

The pagination buttons got broken after MODX upgade from 2.8.3 to 3.0. The same pagination buttons are repeated so the content must come from the cache. 

I will turn getPage's cache off.  The snippet has already this setting so I think a code change is not needed. Of course, it would be nice to get cache working.

**Comment by halftrainedharry** [comment] 2022-04-05 13:45
> I will turn getPage's cache off. The snippet has already this setting

Do you mean the property `cache`?
```
[[!getPage? &cache=`1` ... ]]
```
I don't think this property affects the elementCache (`$this->xpdo->elementCache` ) that causes the issue at all.

**Comment by opengeek** [comment] 2022-04-05 14:24
> I assume you are talking about the page navigation of the extra _getPage_ (that isn't correct in MODX3).
> 
> As far as I can tell, the chunks were also cached in MODX 2.x. But now in MODX3 the tags (`$this->_tag`) that are used as the cache key are different than in version 2 and they somehow sometimes have the same value for different calls. (I don't know why, though.)
> 
> https://github.com/modxcms/revolution/blob/8a0d67de4438395a6e82261ddd896dd0e745eeda/core/src/Revolution/modElement.php#L373-L375
> 
> The easiest solution to fix the problem quickly is probably to change the code of the _getPage_ extra and set `$chunk->setCacheable(false);`

This is a pretty significant BC break in my opinion, and should probably be fixed in the core. Do you know what has changed?

**Comment by nsuomine** [comment] 2022-04-05 14:27
> > I will turn getPage's cache off. The snippet has already this setting
> 
> Do you mean the property `cache`?
> 

Yes I meant and you were right. It didn't help.

I made this workaround to getPage code now:

```
$chunk = $modx->newObject('modChunk');
$chunk->setCacheable(false);
$nav = $chunk->process($properties, $tpl);
```
Now getPage works normally.

**Comment by opengeek** [comment] 2022-04-05 14:37
I see the issue. Your tpl's need to have non-cacheable placeholders in MODX 3.x. For example, instead of ```[[+first]][[+prev]][[+pages]][[+next]][[+last]]``` you should have ```[[!+first]][[!+prev]][[!+pages]][[!+next]][[!+last]]```. I have a feeling this kind of issue is going to pop up in way more places than just getPage.

**Comment by nsuomine** [comment] 2022-04-05 15:53
> I see the issue. Your tpl's need to have non-cacheable placeholders in MODX 3.x. For example, instead of `[[+first]][[+prev]][[+pages]][[+next]][[+last]]` you should have `[[!+first]][[!+prev]][[!+pages]][[!+next]][[!+last]]`. I have a feeling this kind of issue is going to pop up in way more places than just getPage.

I tried this. It didn't work.

**Comment by opengeek** [comment] 2022-04-05 16:03
Yeah, I guess the problem is deeper than that. I'll have an update for getPage out later today with the fix. I will investigate why it is a problem in 3.x but not 2.x.

**Comment by halftrainedharry** [comment] 2022-04-05 17:31
I think the difference between 2.x and 3.x is how _array properties_ are handled in the function `getTag()`.
In 3.x it serializes the array

https://github.com/modxcms/revolution/blob/8a0d67de4438395a6e82261ddd896dd0e745eeda/core/src/Revolution/modElement.php#L289-L290

in 2.x it always generates a random number.
https://github.com/modxcms/revolution/blob/111d2d2060db14c05be332a63afcacf58b964563/core/model/modx/modelement.class.php#L234

There is one _array property_ (with the page number) in this processing of the chunk.
Because the page number can be the same for different calls (first page, the previous page (if you are on page 2) and page 1), it creates a unique value in 2.x but generates the same value in 3.x (and therefore the identical tag).

**Comment by opengeek** [comment] 2022-04-05 18:28
> I think the difference between 2.x and 3.x is how _array properties_ are handled in the function `getTag()`. In 3.x it serializes the array
> 
> https://github.com/modxcms/revolution/blob/8a0d67de4438395a6e82261ddd896dd0e745eeda/core/src/Revolution/modElement.php#L289-L290
> 
> in 2.x it always generates a random number.
> 
> https://github.com/modxcms/revolution/blob/111d2d2060db14c05be332a63afcacf58b964563/core/model/modx/modelement.class.php#L234
> 
> There is one _array property_ (with the page number) in this processing of the chunk. Because the page number can be the same for different calls (first page, the previous page (if you are on page 2) and page 1), it creates a unique value in 2.x but generates the same value in 3.x (and therefore the identical tag).

Great find @halftrainedharry! That was a change with a serious unintended consequence. 🤔

**Comment by Esger** [comment] 2022-04-06 09:42
After upgrading from 2.8.3 to 3.0 this didn't work anymore:
`[[*id:is=`[[++site_start]]`:then=`
        [[!pdoResources?
                ....
        ]]`
]]`

Following @opengeek suggestion, making it non-cachable it works again.
`[[!*id:is=`[[++site_start]]`:then=`
        [[!pdoResources?
                ....
        ]]`
]]`

**Comment by opengeek** [comment] 2022-04-06 20:52
This turned out to be a very specific issue with cached chunks being returned by getPage because the tag signature was the same. Resolving it involved making sure the unique chunk tpls being processed in getPage were given a name property so that they generated a unique tag signature in the cache despite having the same hash value of serialized properties.

See https://github.com/opengeek/getPage/pull/36 for the solution.

**Comment by opengeek** [comment] 2022-04-06 20:57
Actually, to avoid this type of problem in other places, I'm going to create a PR to generate a unique tag signature if an element with an empty name value is processed. I'll keep this open and associate it with that solution.

**Closed as completed** 2022-04-13 15:38 UTC
Labels: bug
