### ISSUE TITLE
FC's new name don't work for hidemenu

### ISSUE THREAD

**Issue by Realetive** [modxcms/revolution#13053] opened 2016-06-12 04:21 UTC
### Summary
If setup new label name for hidemenu field, this isn't use. If this setup for published it's ok.

### Step to reproduce
Create new Form Customization rule and try to setup new label name for hidemenu. 

### Observed behavior
Nothing to changes.

### Expected behavior
Checkbox label need to equal new label name from CMP

### Environment
MODX v2.5.0-pl

**Comment by Jako** [comment] 2016-06-12 07:17
I think you mean FC (Form Customization) instead of CMP (Custom Manager Page).

**Comment by Realetive** [comment] 2016-06-12 07:19
@Jako sorry, yes, you are right.

**Comment by Mark-H** [comment] 2016-06-12 13:28
Dupe of #12890 and fixed in #13025 for 2.5.1

**Closed by Mark-H** 2016-06-12 13:28 UTC

**Comment by Realetive** [comment] 2016-06-12 16:55
Many thanks @Mark-H . Good news.
