### ISSUE TITLE
directory Path place holder in Dutch Manager Translation broken

### ISSUE THREAD

**Issue by Noloony** [modxcms/revolution#13087] opened 2016-08-01 14:47 UTC
### Summary

The place holder for the file path when uploading a file is incorrect in dutch translation of revo 2.5.0-pl, the place holder got translated its showing [[+pad]] instead of the file path
### Step to reproduce
- Set manager language to **nl** in system settings
- Go to file in the left had menu, or open the media browser
- Right click in the left side menu and select upload file or use the Upload button to start uploading a file
### Observed behavior
- The titel of the modal box shows a the placeholder [[+pad]] instead of the directory path
### Expected behavior

[[+pad]] should show the path to the directory your uploading to
### Environment

MODX revo 2.5.0-pl
![bug](https://cloud.githubusercontent.com/assets/3015729/17297816/8dda648c-5807-11e6-9d38-ca381ff650be.jpg)

**Comment by Mark-H** [comment] 2016-08-01 14:48
This should be addressed via http://translate.modx.com/

**Comment by sdrenth** [comment] 2017-03-03 14:27
I'm going to try and fix this today.

**Comment by sdrenth** [comment] 2017-03-03 14:29
@Mark-H Tested it and cannot reproduce this issue. It seems this issue has already been fixed and this issue can now be closed.

Tested with:
MODX Revolution 2.6.0-dev

#modxbughunt

**Comment by rtripault** [comment] 2017-03-03 15:18
So closing...

Feel free to comment/reopen if needed.
Thanks

**Closed by rtripault** 2017-03-03 15:18 UTC
