### ISSUE TITLE
MODX Rev 2.7.0-pl Error when viewing "Show details" in "Package Management"

### ISSUE THREAD

**Issue by auditor8880** [modxcms/revolution#14219] opened 2018-12-26 19:50 UTC
MODX Revolution 2.7.0-pl

Found an error in the transition "Show details" of any package in the "Package Management" error flies to the log:

```
[2018-12-25 04:01:35] (ERROR @ /.................../public_html/core/xpdo/om/xpdoobject.class.php : 240) 
Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'transport.modTransportProvider' in 'where clause'
)
```

Occurs in all packages, by the example of Ace by reference:

`....../?a=workspaces/package/view&signature=ace-1.6.5-pl&package_name=Ace`

In my opinion, I met the same or a similar error even with some actions in the admin panel.

Tell me who knows how to fix?

**Comment by JoshuaLuckers** [comment] 2018-12-26 20:11
Please try to run the setup procedure and see if that solves the issue.

**Comment by auditor8880** [comment] 2018-12-26 22:17
Reinstalled on 2 paragraph "Update an existing installation - Update your files and database.".

When installing, everything is "OK". After installation in the "Installation Report" it is written:
"The kernel installation was successful. Click Continue to complete.".

However, in the "Show warnings" error:
```
Table update error for class modResource
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'alias_visible'
)
```
 
Tell me, is this a dangerous mistake?

The manager still has the same error:
```
/public_html/core/xpdo/om/xpdoobject.class.php: 240)
Error 42S22 executing statement:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'transport.modTransportProvider' in 'where clause'
)
```

Reinstalling does not help.

**Comment by JoshuaLuckers** [comment] 2018-12-26 22:45
I can’t test this myself right now. Please provide some mower information about your setup like PHP version and database software/version

**Comment by auditor8880** [comment] 2018-12-26 23:11
Data from phpinfo();
PHP Version 7.1.25
----------------

Data from phpMyAdmin
--------------
Database server
     Server: Localhost via UNIX socket
     Server Type: MariaDB
     Server connection: SSL not used Documentation
     Server version: 10.2.20-MariaDB - MariaDB Server
     Protocol Version: 10
     User: ******* @ localhost
     Server Encoding: UTF-8 Unicode (utf8)

Web server
     cpsrvd 11.76.0.14
     Database Client Version: libmysql - 5.1.73
     PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
     PHP Version: 7.2.7

phpMyAdmin
     Version Information: 4.8.3

**Comment by JoshuaLuckers** [comment] 2018-12-27 16:59
Thanks, I was able to reproduce this issue. The manager does work fine (for me), only an error is logged.

**Comment by auditor8880** [comment] 2018-12-27 17:46
I have been here recently, I have not figured out how everything works.
Tell me, what does "dded this to the v2.7.1 milestone" mean?

How to fix this error?

**Comment by ghost** [comment] 2018-12-27 17:54
This is the place for reporting bugs or requesting new features or improvements, it's not intended to be for help. Go the the forums or the appropriate Slack channel for help requests.

When something is added to a milestone, it means that the fix will be done in that version. In this case, it means that a fix for this should be ready to be added to version 2.7.1. Sometimes these things turn out to be more complicated than originally thought, and may not actually make it into the proposed version.

**Comment by ghost** [comment] 2018-12-27 17:56
You can fix the problem by manually adding the alias_visible field to the site_content table using a mySQL client like phpMyAdmin, 
```  `alias_visible` tinyint(1) UNSIGNED NOT NULL DEFAULT '1',```

The actual command would be ```ALTER TABLE  `modx_site_content` ADD  `alias_visible` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT  '1' AFTER  `alias` ;```

**Comment by JoshuaLuckers** [comment] 2018-12-27 17:59
Hi @auditor8880, thanks for taking time to report this issue. If the manager does work properly there is no need to do something, we will try our best to fix this issue and release it in the next update.

**Comment by auditor8880** [comment] 2018-12-27 19:50
> You can fix the problem by manually adding the alias_visible field to the site_content table using a mySQL client like phpMyAdmin ...

The fact is that the alias_visible field is already in the site_content table.
![alias_visible](https://user-images.githubusercontent.com/44309571/50492675-10e72a00-0a2a-11e9-8c2a-d13f691ba5a4.png)


`Duplicate column name 'alias_visible'`
That is, there is a column, and MODX tried to add again, but it did not work. I think this is also a mistake for correction.

**Comment by Jako** [comment] 2018-12-27 21:17
@sottwell He has no issue with the `alias_visible` column. There is some database upgrade script that runs every time on some installations (I could not catch that one yet) that tries to create that column, even if it does exist.

He has an issue with `Unknown column 'transport.modTransportProvider' in 'where clause'` thats generated in the error log during showing the details of a package.

**Comment by auditor8880** [comment] 2018-12-28 16:44
**JoshuaLuckers, thank you!**

Here it helped:
https://github.com/modxcms/revolution/pull/14222/files

There is no error now.

Also, the list of all packages was quickly displayed. Previously, downloading the list of packages waited for 5-10 seconds minimum.

JoshuaLuckers, tell me, does this fix affect the speed of displaying the list of all packages?

**Comment by JoshuaLuckers** [comment] 2018-12-28 18:00
I don't think the changes I made are related to the speed of the listing. I believe the list results are cached.

**Comment by alroniks** [comment] 2018-12-29 20:20
PR is merged. Closing the issue.
@auditor8880 Thank you for posting the issue. It helped us make MODX better a bit. This updates will be delivered with the nearest release.

**Closed as completed by alroniks** 2018-12-29 20:20 UTC
Labels: bug, area-core
