### ISSUE TITLE
s3 Media Browser Tree Latency

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12392] opened 2015-03-20 20:49 UTC
The s3 bucket media source directory tree is frustratingly slow loading.  I installed the same bucket on a cPanel server and MODXcloud, both routinely fail to load the file tree.  

The network console shows that the connector does not load within 30 seconds and fails.

It appears the more files in a bucket the longer it takes to load the tree to the point where it times out and becomes unusable.  Not sure if there is a good solution to this.

**Comment by mbutsko** [comment] 2015-07-27 14:17
Having the same issue. Did you ever find a resolution?

**Comment by pyrographics** [comment] 2015-07-27 14:19
No, I have not, we just cleaned the folder and told the client to organize their files into subfolders.  Still not ideal. I think it may also has something to do with the size of the files

**Comment by Mark-H** [comment] 2015-07-27 16:00
There might be some optimization possibilities in the core media source, but the most part of the delay is to the best of my knowledge latency from S3...

**Comment by rthrash** [comment] 2016-04-25 14:07
We did a bit of research on this recently, and it would seem that the slowdowns using the older API code from Amazon may be the cause of the performance degradation. As an anecdotal aside, we had been using an older version of the AWS SDK in MODX Cloud. When we updated to the current version it was much, much faster. 

Anyone have experience with Media Sources that could take a stab at updating the library used?

**Comment by Mark-H** [comment] 2016-07-25 23:34
Another reason to update the AWS SDK is that some regions (e.g. Frankfurt) require authorization v4, while the current version only supports up to v3.

**Comment by markwillis82** [comment] 2016-09-03 19:22
I've been using the S3 media source the past week and had these issues with some of our buckets. There are 2 issues i've spotted due to speed:

1) The getimagesize() function has to download the image to work out how big to make a thumbnail ... this doesn't work well when a folder is recursed (alot of files have to download) https://github.com/modxcms/revolution/blob/2.x/core/model/modx/sources/mods3mediasource.class.php#L398 ... We removed this from the opencloud media source as it's terribly slow

2) The isBinary() check has to read every file to determine if it's a binary file or not. https://github.com/modxcms/revolution/blob/2.x/core/model/modx/sources/mods3mediasource.class.php#L1078 We just put a "return true" at the top of the function and the media tree and browser are pretty much instant now.

When I get some free time I'll push these changes back into repo. Just don't have the time at the moment.

**Comment by Mark-H** [comment] 2016-09-03 22:29
Improvements to the core source are welcome, though just FYI there has been some work by @theboxer on a completely new S3 media source as an extra. That can be found here: https://github.com/modxcms/aws-s3-media-source

**Comment by markwillis82** [comment] 2016-09-04 12:16
Interesting. Looks like the same function calls exist in there also. So maybe worth porting improvements to both versions

**Comment by rthrash** [comment] 2016-09-04 14:12
It would be worth submitting PRs to both I think. What are the potential breaking changes from those changes Mark?

For reference, the new one is based on the latest AWS SDK and will work globally. The old on will fail to auth in some European locations. The goal in the future will be for any media source to be an Extra, fully optional, to make it easier to maintain and innovate without fear of triggering Semver breakages.

**Comment by markwillis82** [comment] 2016-09-05 06:01
@rthrash without the "getimagesize" the thumbnails aren't kept in aspect ratio and uses the default  sizes.

The isBinary i'm yet to see what purpose this serves within MODX so will get back to you.

**Comment by Mark-H** [comment] 2017-02-09 17:10
Any chance of an update @markwillis82? Your tweaks sound promising.

**Comment by alroniks** [comment] 2021-04-01 20:34
In 3.x [flysystem](https://github.com/thephpleague/flysystem) wrapper uses, also SDK updated. I tested and seems it works. So, I am closing but feel free to reopen.

**Closed by alroniks** 2021-04-01 20:34 UTC
