### ISSUE TITLE
PageTitles with " in it weren't be able to edit

### ISSUE THREAD

**Issue by HMoellendorf** [modxcms/revolution#13708] opened 2017-11-28 17:27 UTC
What does it do?

Solved a bug when trying editing pages with " in pagetitle

Why is it needed?

Pages with " in title weren't be able to edit.
Atttached the solved file.

I added only addslashes() to the pageTitle: line.
[modx-2.6.0-pl-corrected-file.zip](https://github.com/modxcms/revolution/files/1510963/modx-2.6.0-pl-corrected-file.zip)

**Comment by labr1005** [comment] 2017-11-28 17:31
Duplicate of #13664. Fixed with #13669.

**Closed** 2017-11-28 18:49 UTC
