### ISSUE TITLE
Cannot regenerate session id - session is not active

### ISSUE THREAD

**Issue by Erdem-Ozyalcin** [modxcms/revolution#13742] opened 2018-01-25 09:07 UTC
When i login for a front end page (not for mgr) i get this error message in my error log.
[2018-01-25 10:00:43] (ERROR @ /paas/c0176/www/core/model/modx/moduser.class.php : 355) PHP warning: session_regenerate_id(): Cannot regenerate session id - session is not active

What can this mean?

I am using modxcloud modx 2.6.1 and php 7.1
and for to login pluggin i use login 1.9.4

**Comment by sottwell** [comment] 2018-01-25 09:14
This would be better if asked in the forums or on Slack
https://forums.modx.com/board/304/revolution-2-6
https://modx.org/

**Comment by OptimusCrime** [comment] 2018-01-25 09:16
This does not seem to be an issue with the MODX core? You are using a extra (that has its own repository), and the error is a general PHP error caused by calling `session_regenerate_id` before `session_start` (as far as I know). We would then need to see the actual code here to reproduce it, which is not provided.

Either ask in the forums, like @sottwell suggested, or open a new issue in the Login repository with all the relevant code we need to reproduce the error.

**Comment by Mark-H** [comment] 2018-01-29 23:31
Little hard to help with no feedback, but aside from the earlier comments, could also be related to having disabled sessions and still trying to use them. 

I'm going to mark this issue as closed as it isn't in the form of a proper bug report, but if I'm mistaken please feel free to reopen.

**Comment by BobRay** [comment] 2019-05-17 20:45
I'm getting this exact error suddenly (but on line 362 -- the session_regenerate_id line). I'm logging a user in in code. Here's the relevant modUser class code:

```
 public function addSessionContext($context) {
        if (!$this->xpdo->startSession()) {
            $this->xpdo->log(xPDO::LOG_LEVEL_ERROR, "Attempt to start a session failed", '', __METHOD__, __FILE__, __LINE__);
            return;
        }
        if (!empty($context)) {
            $this->getSessionContexts();
            session_regenerate_id(true);
```

startSession() is working, and getSessionContexts() is not throwing an error -- debugging code indicates that the context is 'web' and the user is active, so I don't see how this could not be working.  Maybe it's a server issue.

**Comment by azeller** [comment] 2020-07-27 09:53
Did anybody ever get a hold of this? And if so, how did you solve it? I "broke in" by logging in with a little script that starts a manager session - no questions asked. However, after clearing cache, sessions and updating the system it was really hard to reproduce what actually solved it. Now, years later I am facing the same issue and I can see that this is still open.

Any news from anybody on this? Or at least a workaround?

**Comment by JoshuaLuckers** [comment] 2020-07-27 10:00
Am I safe to say that this happens when you "broke in" using a login script?

**Comment by azeller** [comment] 2020-07-27 10:02
The breaking in part did only happen after nothing else worked. So no, this wasn't the cause, if that's the question. It was part of the solution, not part of the problem.

**Comment by azeller** [comment] 2020-07-27 10:25
Alright, I could log back in now. Maybe this helps. It didn't solve anything in the process but I think this happened because of anonymous sessions and disabled sessions in a context (web!) , when they were supposed to be ignoring the mgr context. So this was a **context setting**, not a system setting.

I **deleted** the setting:
`delete modx_context_setting where modx_context_setting.key='session_enabled';`

I also enabled anonymous_sessions through the db. This was **the only** setting that had been changed the night before to speed things up I guess? I have no idea, I didn't change it myself.

None of those worked, so I deleted (rm -rf) {core}/cache/mgr {core}/cache/system_settings

After this, I could log back in. Maybe this helps.

MODX 2.7.1 + PHP 7.3.20

**Closed** 2020-07-27 13:33 UTC

**Comment by pbowyer** [comment] 2022-03-15 12:46
Thanks for sharing @azeller. I had this happen today to a MODX 2.8.1-pl site running on MODX Cloud. 10 days ago I'd disabled anonymous sessions and today no one could log in (no one had tried for over a week, so I don't know when exactly it stopped working).

Your instructions fixed it 👍 - re-enable anonymous sessions, delete the whole cache folder, and Manager login worked again. I will try disabling anonymous sessions again in future and see if it breaks.

**Comment by rthrash** [comment] 2023-04-22 20:27
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/login-fails-silently-seems-to-be-a-session-problem/6654/6
