### ISSUE TITLE
$modx->getOption(...) returns database login and password

### ISSUE THREAD

**Issue by vasyahuyasa** [modxcms/revolution#12653] opened 2015-09-16 12:47 UTC
$modx->getOption(...) returns database login and password.
How to reproduce:
create snippet with content:
```
<?php
$u = $modx->getOption("username", $scriptPropeties);
$p = $modx->getOption("password", $scriptPropeties);
return "username: $u password:$p";
```
$scriptPropeties (or any other array) should not contain $scriptPropeties['username'] and $scriptPropeties['password'] elements.

**Comment by sottwell** [comment] 2015-09-16 12:51
In many cases that information is necessary. If you can't trust your coders with database access information (which they can get from the config.inc.php file easily enough if they have that kind of Manager access) then you have bigger problems.

**Comment by Mark-H** [comment] 2015-09-16 12:52
Those elements are not in $scriptProperties, but $modx->getOption also searches "up the chain", so you're getting global options there. 

In the manager `MODx.config` array, those elements (and a couple of others) are filtered out to not leak that information client-side. Server-side though, you could already just include the config file if you're after those, so I'm not sure of the benefit of trying to filter that?

**Comment by pixelchutes** [comment] 2015-09-16 13:08
You appear to have a typo `$scriptPropeties` is missing the 2nd "r". However, like Mark said, it's designed with fallback support to User/Context/System Settings.

**Comment by vasyahuyasa** [comment] 2015-09-16 14:17
Actualy, i get that issue when i was trying process data from $_POST like that:
```
$username = $modx->getOption('username', $_POST);
if(isset($username)) {
    ...
}
```
If $_POST['username'] is not defined in HTML form i was expect $modx->getOption('username', $_POST) return NULL, but it returns database connection user name, so it is confuse me.

**Comment by pixelchutes** [comment] 2015-09-16 16:58
That definitely is confusing, especially when a provided fallback value *(3rd argument)* does not get used.

**Comment by OptimusCrime** [comment] 2015-09-16 18:40
This is NOT an issue. There is no way to hide this propperly. Simply remove access to creating snippets to users that can not be trusted.

I for one say wontfix on this.

**Comment by sottwell** [comment] 2015-09-16 18:44
What's the advantage of using getOption() for POST values? Could the options tree search be stopped by providing a default of '' (empty string)?

**Comment by vasyahuyasa** [comment] 2015-09-16 19:52
Problem not only in getOption() for $_POST, for example you can pass to snippet "username" property like that:
```
[[!mySnippet? &username=`[[+name]]`]]
```
mySnippet:
```
<?php
$username = $modx->getOption('username', $scriptProperties);
if(isset($username)) {
...
}
```
If [[+name]] for some reason will be empty then in snippet after call getOption() method $username variable will contain database login, it is very confusing because MODX developing documentation show thet getOption() should be used for get snippet properties,  but there no any word that some properties names can be dangerous to use.

**Comment by vasyahuyasa** [comment] 2015-09-17 05:23
I was wrong in my previous comment
 ```
[[!mySnippet? &username=`[[+name]]]]
```
works as expected, but issue still open if property name not defined like that: `[[!mySnippet]]`.

**Comment by sottwell** [comment] 2015-09-17 05:26
All kinds of problems can be caused by sloppy PHP programming. It's incumbent on the programmer to practice proper programming protocols to promote security.

**Comment by OptimusCrime** [comment] 2015-09-17 10:13
+1

**Closed** 2015-09-22 08:58 UTC
