### ISSUE TITLE
For TV with the input type "Date" does not work setting "Allow Blank" [bug]

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14179] opened 2018-12-04 21:16 UTC
### Summary
For some reason, the "Allow Blank" settings does not work for TV with date input type, the resource is saved in any case.

p.s. By the way, is it planned in MODX3 "Allow Blank" for all types of TV? (https://github.com/modxcms/revolution/issues/6521)

MODX 2.7

**Comment by JoshuaLuckers** [comment] 2018-12-05 07:33
Because it's a duplicate of #12302 I'm closing this issue.

@modxbot close

**Closed as completed** 2018-12-05 07:33 UTC
