### ISSUE TITLE
MODX3 PHP Fatal error: Cannot declare class modTemplateVarInputRenderText

### ISSUE THREAD

**Issue by jolichter** [modxcms/revolution#16402] opened 2023-02-26 11:04 UTC
#### PHP Fatal error: Cannot declare class modTemplateVarInputRenderText, because the name is already in use

I think this issue refer to to the old issue [16329](https://github.com/modxcms/revolution/issues/16329), but my SQL database looks OK, 'modTemplateVar' has been replaced by 'MODX\Revolution\modTemplateVar'.

This upgrade was to another similar MODX 2.8.4-pl via UpgradeMODX to 3.0.0-pl and then to 3.0.3-pl (core/cache cleaned).
When I try to edit a resource which use Text TVs, I get a blank screen. The browser console reveals:

GET https://myDomain.tld/manager/?a=resource/update&id=281
Status: 500 Internal Server Error
Version: HTTP/2
Transferred: 371 B (0 B size)
Referrer Policy: strict-origin-when-cross-origin
Request Priority: Highest

### PHP Error Log:
[proxy_fcgi:error] [pid 3292968] [client xx.xxx.xxx.xx:x] AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class modTemplateVarInputRenderText, because the name is already in use in /var/www/vhosts/myServer.tld//httpdocs/modx/core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/text.class.php on line 0', referer: https://myDomain.tld/manager/?a=element/tv/update&id=383

### Step to reproduce
- Create a TV with input type Text
- Add TV to a template
- Edit a resource in menu tree (which use this template)
- MODX Manager crashes (blank page)

### Observed behavior
I am currently using 3 contexts (web, web3 and web4) and this error only occurs with the web4 context.

### Expected behavior
As workaround I modified the `text.class.php` (as mentioned [here](https://github.com/modxcms/revolution/issues/16329#issuecomment-1345623376)) and the website works as expected: no PHP Error or MODX Log Error.

### Environment
- MODX 3.0.3-pl
- PHP 8.1.16
- MariaDB 10.3.38
- TinyMCE RTE 2.0.9-pl
- FormIt 5.0.1-pl
- pdoTools 3.0.1-pl
- pThumb 2.3.3-pl
- Resizer 1.0.2-beta
- UpgradeMODX 2.3.3-pl

**Comment by Mark-H** [comment] 2023-02-26 15:25
I believe this error happens when there is a TV configured that cannot be found; that loads the text tv as a fallback but that may already be loaded and cause the error. The text tv itself is fine.

So what other TVs types are you using that may not be available after upgrading? 

The root cause is the logic loading the TVs, not sure if that's something we can fix easily.

**Comment by jolichter** [comment] 2023-02-26 22:38
Oops, that was the right tip: "So what other TVs types are you using that may not be available after upgrading?"

I found an old custom TV-input-type with jQuery as Datepicker. If I deactivate this or switch to Input Type `Text` everything works. I'll modify or remove it for MODX 3.

Anyway, thanks a lot Mark!

btw: It would be nice if in the future there would be a suitable message in the MODX Error Log?

**Comment by jolichter** [comment] 2023-02-26 22:39
Oops, that was the right tip: "So what other TVs types are you using that may not be available after upgrading?"

I found an old custom TV-input-type with jQuery as Datepicker. If I deactivate this or switch to Input Type `Text` everything works. I'll modify or remove it for MODX 3.

Anyway, thanks a lot Mark!

btw: It would be nice if in the future there would be a suitable message in the MODX Error Log?

**Comment by jolichter** [comment] 2023-02-26 22:40
Oops, that was the right tip: "So what other TVs types are you using that may not be available after upgrading?"

I found an old custom TV-input-type with jQuery as Datepicker. If I deactivate this or switch to Input Type `Text` everything works. I'll modify or remove it for MODX 3.

Anyway, thanks a lot Mark!

btw: It would be nice if in the future there would be a suitable message in the MODX Error Log?

**Comment by Mark-H** [comment] 2023-02-27 02:02
I'm not actually able of reproducing this on purpose, which would be helpful in coming up with a fix. What was the type that was broken for you?

**Comment by jolichter** [comment] 2023-02-27 08:13
Sorry, I'll try to explain it better. This probably won't happen often (maybe when MODX 4 comes out ;-). But I hope you can reproduce this:

In MODX 2 I had created a custom TV-input-type with jQuery Datepicker ([Link](http://keith-wood.name/datepick.html)) and stored it in:
`core/model/modx/processors/element/tv/renders/mgr/input/datepicker-multiple.class.php`

Since this path no longer exists, I suspect it was removed during the update to MODX 3? Maybe the new path is (not tested):
`core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/`

In my calendar resource this custom TV was included and since it was no longer available, as you mentioned it tried to load the Text TV as a fallback. But it works only with the previously mentioned fix in `text.class.php`.

My problem was that the PHP error message confused me (PHP Fatal error: Cannot declare class modTemplateVarInputRenderText), because I assumed that a Text TV was the cause.

Now that I know this happened because of the fallback, I found my mistake.

Therefore my question: In this case a MODX Error Log would be fine? e.g.: TV xxxxxx does not exist, fallback to Text TV.

**Comment by smg6511** [comment] 2023-02-27 14:54
I've run into this issue when developing one of my other PRs. If I remember correctly, it doesn't really matter what type the TV was, all that has to happen is for you to have at least one regular Text type TV in your template and one TV type that is missing for some reason.

**Comment by Mark-H** [comment] 2023-02-27 15:51
Yeah, I've seen this issue before, but when I create a TV on the latest 3.x, then change the type to a fake one in the database, _it doesn't actually break_. And yeah I do have a different text TV enabled on the same resource as well.

Maybe it actually needs an invalid TV class? 

> Therefore my question: In this case a MODX Error Log would be fine? e.g.: TV xxxxxx does not exist, fallback to Text TV.

Yes, that's why I'm trying to purposely break it on my development install, to see if I can get it to just log an error. :P

**Comment by halftrainedharry** [comment] 2023-02-27 21:33
The order is important. The TV with the wrong type has to be processed first, before the correct Text TV, to generate the error.
Otherwise the `class_exists` of the fallback prevents that the file is included twice.

https://github.com/modxcms/revolution/blob/e7607a239218ba855dbd60805948e34119f913c5/core/src/Revolution/modTemplateVar.php#L487-L489

**Comment by JoshuaLuckers** [comment] 2023-03-21 11:42
I can confirm this issue. Steps to reproduce:
- Make sure you have a Template without TV's assigned to it.
- First create a TV with a valid Input type and assign it to the template.
- Create a second TV with Input Typ `text` and assign it to the template.
- Create a new resource with this Template
- Editing it works like expected
- Now adjust the first Template Variable via the database and give it an invalid input type.
- Edit the resource again
- Error:

> Fatal error: Cannot declare class modTemplateVarInputRenderText, because the name is already in use in /Users/joshua/Projects/modx-3x/core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/text.class.php on line 0

**Closed as completed** 2023-10-03 17:39 UTC
Labels: bug
