### ISSUE TITLE
Need to add/fix support for caching json in system/context settings

### ISSUE THREAD

**Issue by enminc** [modxcms/revolution#11235] opened 2014-03-26 00:35 UTC
See my post here

http://forums.modx.com/thread/89766/modcachemanager-class-php-bug-maybe#dis-post-493583

Need to add support to allows for json to be saved and properly cached when used as a system and/or context settings. Currently the preg_match_all kills the json string.

My solution of adding a json check is probably not the most ideal or elegant but it works. 

Maybe a simple (but not simple to me solution) would be to adjust the regex to match when { is not followed by a " . This would allow for json to pass through and not match while allowing {base_url} to match

if (!json_decode($v) && preg_match_all('~{(.*?)}~', $v, $matches, PREG_SET_ORDER)) {

**Comment by pixelive** [comment] 2017-03-03 13:13
Tried JSON in both system settings as context settings and it both works. (and cached as well)

Duplicate of #11611

**Comment by rtripault** [comment] 2017-03-03 13:27
So closing.

Feel free to comment/reopen if needed.
Thanks

**Closed by rtripault** 2017-03-03 13:27 UTC
