### ISSUE TITLE
MODX 3 changelog format changes

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#15564] opened 2021-03-18 22:20 UTC
### Summary
When intalling an extra where the changelog is a text file, line breaks are no longer applied to to the list of updates, which appears as a solid paragraph.

### Step to reproduce
Install UpgradeModx and look at the changelog during installation.

**Comment by BobRay** [comment] 2021-03-18 22:23
The changelog looks as it should in Package Pananager "View Details."

**Comment by Jako** [comment] 2021-03-18 22:42
The problem is: markdown and plain text are not replaceable with each other. MODX 3 uses markdown for the description/changelog and text files with missing line feeds have some issues in markdown. I suggest closing this as wontfix.

**Comment by BobRay** [comment] 2021-03-19 20:54
Wouldn't that mean that the rendering system used in Package Manager's "View Details" would be different than the one used during installation of extras?

**Comment by Jako** [comment] 2021-04-09 06:24
> Wouldn't that mean that the rendering system used in Package Manager's "View Details" would be different than the one used during installation of extras?

Yes, that part ("View Details") is currently not changed and has to be changed.

**Comment by alroniks** [comment] 2021-04-24 23:14
Closing as discussed. Issue related to View Details formatting still is open.

**Closed as completed by alroniks** 2021-04-24 23:14 UTC
Labels: type-frontend, bug, area-packages
