### ISSUE TITLE
Could not load class: modPhpThumb from modphpthumb in MODX 3.0.2

### ISSUE THREAD

**Issue by abelafonte** [modxcms/revolution#16339] opened 2022-12-25 13:49 UTC
### Summary
None of the phpThumb plugins are working in MODX 3.0.2. Including phpthumbof, phpthumbsup, pThumb.

### Step to reproduce
Install any phpThumb Extras and attempt to use Snippet as an Output Modifier with familiar syntax such as ``` article-image:phpthumbof=`w=370&h=270&zc=1` ```

### Observed behavior
```
Could not load class: modPhpThumb from modphpthumb
[phpThumbOf] Could not load modPhpThumb class in plugin.
```

### Expected behavior
Images should be resized, cropped or otherwise manipulated according to features listed in phpThumb official documentation.

### Environment
MODX 3.0.2 / Apache / PHP 7.4.33 / MySQL 5.7.40

**Comment by halftrainedharry** [comment] 2022-12-25 16:06
I can't reproduce this. I tested _pThumb_ 2.3.3-pl (MODX 3.0.2 | PHP 7.4) and that works correctly.

Also, if you can see the thumbnails in the MODX manager (for example under "Media" -> "Media Browser"), then _modPhpThumb_ works correctly.

If there is a problem with one of the extras, then you should probably create an issue in the extra's Github repository.

**Comment by JoshuaLuckers** [comment] 2022-12-26 11:15
Thanks for taking time to report this issue and help make MODX better.

Additional to what @halftrainedharry said about the thumbnails in the manager:
Is this a clean install of MODX 3.0.2 or did you upgrade from 2.x?

**Comment by abelafonte** [comment] 2022-12-26 22:54
Hmm, ok. Thanks, guys!  Yes, manager instances of phpThumb are working correctly such as the media browser.

As of right now, it's affecting any and all Extras that attempt to use the modPhpThumb class.  So, it doesn't appear to be the Extras themselves.

@JoshuaLuckers this is a clean install of 3.0.2.  I am about to do a new install of 3.0.2 for a separate project. I will see if it suffers from the same issues.  

I'll do some additional digging and report back.

**Comment by abelafonte** [comment] 2022-12-26 23:00
Thanks to @halftrainedharry's note, I was able to get past this issue.  I had to completely uninstall phpthumbof and then reinstalled pThumb. Everything works as expected now.

**Comment by abelafonte** [comment] 2022-12-26 23:34
Just to clarify the solution for anyone who encounters it: I tried using phpthumbof and phpthumbsup with MODX 3.0.2 and they both fail to generate thumbnails successfully.

pThumb works using the ```:phpthumbof``` filter. But for best results, make sure that you have completely uninstalled other forks of phpthumbof before installing pThumb.

**Comment by JoshuaLuckers** [comment] 2023-01-08 11:21
Thank you for taking the time to share the solution @abelafonte.

Since there is a solution I'm going to close this issue.

**Closed as completed by JoshuaLuckers** 2023-01-08 11:21 UTC
Labels: bug
