### ISSUE TITLE
Cannot re-run setup after install in MODX3

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#14628] opened 2019-06-28 14:14 UTC
### Summary
Cannot re-run setup after install in MODX3. This problem occurred after the big refactor PR has been merged, so my guess would be that it is related to that.

![Screenshot 2019-06-28 at 16 00 41](https://user-images.githubusercontent.com/7802465/60348479-e87fbe80-99bf-11e9-8a8b-9249528760b2.png)

If I dump `$install->runner->getResults();`these are the results:
```
array(3) {
  [0]=>
  array(2) {
    ["class"]=>
    string(7) "success"
    ["msg"]=>
    string(51) "
Config file successfully written.

"
  }
  [1]=>
  array(2) {
    ["class"]=>
    string(7) "success"
    ["msg"]=>
    string(63) "
Config file permissions successfully updated.

"
  }
  [2]=>
  array(2) {
    ["class"]=>
    string(6) "failed"
    ["msg"]=>
    string(21) "
"
  }
}
```

### Step to reproduce
- Clean install MODX 3 and run setup
- After succesfully running the setup, rerun the setup and choose "Upgrade Existing Install" and complete setup

### Observed behavior
After rerunning the installer I see the message: "Errors were encountered during core installation. Please review the installation results below, correct the problems and proceed as directed."

### Expected behavior
I expect the setup to finish succesfully.

### Environment
MODX 3

**Comment by alroniks** [comment] 2019-06-28 14:17
I fixed it already in https://github.com/modxcms/revolution/pull/14507
Only need to merge

**Comment by Ibochkarev** [comment] 2019-06-28 14:17
I can reproduce this bug. Thanks

**Comment by JoshuaLuckers** [comment] 2019-06-28 15:33
I'm closing this issue since re-running setup is possible thanks to PR #14507 being merged.

**Closed as completed by JoshuaLuckers** 2019-06-28 15:33 UTC
Labels: bug
