### ISSUE TITLE
getElementSources (manager/controllers) unescaped reserved word

### ISSUE THREAD

**Issue by ttyiav** [modxcms/revolution#9903] opened 2013-05-03 20:47 UTC
ttyiav created Redmine issue ID 9903

Hello,
Unable to edit TV-MediaSource bindings on MSSQL based installations because of unescaped reserved words in 
\manager\controllers\default\element\tv\update.class.php
Function getElementSources(), lines 126 and 128. The function fails to retrieve the list of media sources and thus the manager can not edit TV-MS bindings because they are not shown on screen.

@        $c->leftJoin('sources.modMediaSourceElement','SourceElements',array(
            'SourceElements.object' => $this->tv->get('id'),
            'SourceElements.object_class' => $this->tv->_class,
            'SourceElements.context_key = *******_modContext.key**_****_'--------,--------
        ));
        $c->leftJoin('sources.modMediaSource','Source','SourceElements.source = ***_***_Source.id**_*****');@

I found it in 2.2.5, but the issue persist in 2.2.7.

I corrected it like this

@        $c->leftJoin('sources.modMediaSourceElement','SourceElements',array(
            'SourceElements.object' => $this->tv->get('id'),
            'SourceElements.object_class' => $this->tv->_class,
            'SourceElements.context_key = modContext.' . $this->modx->escape('key')
        ));
        $c->leftJoin('sources.modMediaSource','Source','SourceElements.source = Source.' . $this->modx->escape('id'));@

**Comment by pbowyer** [comment] 2017-03-03 17:40
The code for this hasn't been fixed, and the problem looks slightly wider than discussed above.

However... xPDO may well have sorted this in the 3.75 years since the issue was reported. I don't have MSSQL to test against, so leaving as #open and #confirmed for our resident MSSQL users to test.

#modxbughunt

**Comment by alroniks** [comment] 2021-04-03 22:51
We are going to drop support of MSSQL, so it closed as `wontfix`.

**Closed by alroniks** 2021-04-03 22:51 UTC
Labels: area-core, bug
