### ISSUE TITLE
 Resource List TV parent field not working

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#14207] opened 2018-12-19 17:34 UTC
### Summary
When configuring the resource select TV to only display resources from a specific parent it shows all resources in all contexts

### Step to reproduce
Create Resource List TV, set parent field to a valid value, assign to Template, try and select.

Tried on Multicontext sites as well.

### Observed behavior
Lists all resources

### Expected behavior
List only parent resources

### Environment
Multicontext site, MODX 2.7 , PHP 7.2, LiquidWeb Cloudsites. Also present in single context site on php 5.6 server.

**Comment by ghost** [comment] 2018-12-19 17:57
I can confirm this bug. 

Looking at forum posts for several years, it looks like this never worked as expected.

![screen shot 2018-12-19 at 19 58 31](https://user-images.githubusercontent.com/1073780/50238613-93d40900-03c8-11e9-9ad9-55b104b1ffd2.png)


![screen shot 2018-12-19 at 19 58 08](https://user-images.githubusercontent.com/1073780/50238627-9a628080-03c8-11e9-9112-4834fa864c1a.png)

**Comment by neoneddy** [comment] 2018-12-19 18:47
I'm pretty sure at one point it did work.  I used it in an area where I'm sure my client would have made a fit of having to scroll through 200 items.

**Comment by ghost** [comment] 2018-12-19 18:55
Could be; I never used it, I usually used one of Sepia River's methods.

**Comment by neoneddy** [comment] 2018-12-19 18:56
I probably do as well ( a listbox with a query building the resources list) But in this case I needed the context awareness.

**Comment by Jako** [comment] 2018-12-19 20:55
You could try https://modx.com/extras/package/superboxselect.

**Comment by Jako** [comment] 2018-12-20 06:44
Fixing this right would create a BC, so this has to wait until 3.x

**Comment by alroniks** [comment] 2019-02-05 14:44
Related PR was merged. So I am closing it, but feel free to reopen if needed.

**Closed as completed by alroniks** 2019-02-05 14:44 UTC
Labels: bug, area-core

**Comment by neoneddy** [comment] 2019-02-05 15:36
Thanks everyone
