### ISSUE TITLE
Can't launch installation : "SyntaxError: expected expression, got '<'"

### ISSUE THREAD

**Issue by Spheerys** [modxcms/revolution#13852] opened 2018-04-06 15:21 UTC
### Summary
I can't launch the installation of the dev version : I'm  blocked after the dabase configuration screen

### Step to reproduce
Following all steps of this tutorial : How to reproduce the issue, including custom code if needed.

### Observed behavior
On the database configuration screen, I can't test the information with the link "→ Test the connection to the database and see collations".
With browser js console, I can see this error : 
`SyntaxError: expected expression, got '<'`

### Expected behavior
I should go to the user creation screen.

### Environment
Last MODX 3.0 github version (April 6th 18 at 5pm)
Apache 2.4.7
MySQL 5.5.59
Firefox 59.0.2

**Comment by Mark-H** [comment] 2018-07-04 13:46
That error suggests a PHP error being rendered as HTML in an ajax request, rather than it being properly formatted JSON. Often caused by a fatal error.

Could be an old PHP version (< 5.5), not having executed `composer install` or the transport build. 

This issue by itself does not provide enough information for a fix, so I'll close it, but if you're still having issues, the forum or slack may be a better way to get help identifying the specific problem.

**Closed as completed by Mark-H** 2018-07-04 13:46 UTC

**Comment by Spheerys** [comment] 2018-07-04 13:50
OK thanks Mark.
Just for information, I have just tested the regular MODX3 package and the issue is still there.

**Comment by Mark-H** [comment] 2018-07-04 15:59
Use your browser console to look at the raw response coming from the ajax request. That probably contains an error message that will point to a cause (hopefully).
