### ISSUE TITLE
Template Variable's "Default Value" UI and description does not match the actual behavior

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14945] opened 2020-01-07 13:17 UTC
### Summary

The UI/description regarding the "Default Value" for Template Variable's is confusing and creates wrong expectations of its behavior.

### Observed behavior
The value of the input field whose label is "Default Value" is used to set the default_text field for the modTemplateVar object.

When getting the value of a template variable for a resource it return the raw value of the template variable in context of the specified resource.
When no value is found the default_text for the template variable is returned.
 
### Current UI/Description 
The input field for the `default_text` can be found under the "Input Options" tab.

> Here you can edit the input options for the Template Variable, specific to the type of input render that you select.

The input field for `default_text` is labelled as "Default Value", under this field there is also a description/help text:

> The default value will be stored if the user does not specify a value. 

### Related issue(s)/PR(s)
- #14773
- #12386
- #9897
- #1852 
- probably more

**Comment by Ruslan-Aleev** [comment] 2020-07-06 11:19
Related with https://github.com/modxcms/revolution/issues/15143

**Comment by smg6511** [comment] 2024-08-16 01:43
Guys, I think we should close this issue, even though it's still relevant for the 2.x branch. This, among other things, was pretty thoroughly covered in a major refactor of the Elements editing panels for 3.x. IMO it's not worth replicating that work for 2.x since it's our legacy platform and the issue is not an operational bug. Do you agree?

**Closed as completed** 2024-08-16 08:28 UTC
Labels: type-frontend, bug
