### ISSUE TITLE
modElement getTag function raises fatal error

### ISSUE THREAD

**Issue by raffy99** [modxcms/revolution#15172] opened 2020-07-29 11:01 UTC
### Step to reproduce
create plugin which is invoked on "OnBeforeEmptyTrash" and "OnEmptyTrash" and returns empty string. now delete one or more resources and purge them in the trash manager.

### Observed behavior
The trash purge processor invokes events "OnBeforeEmptyTrash" and "OnEmptyTrash". if a plugin is triggered by the event, the parameters will pass through as properties to the getTag-function of modElement. My example plugin only returns empty string. "invokeEvent" function of modx calls the process function of modScript which calls parent process function and thats modElement. modElement process function calls the getTag function, which raises the error:
PHP Fatal error: Uncaught PDOException: You cannot serialize or unserialize PDO instances

### Expected behavior
no errors to expect

### Related issue(s)/PR(s)
#14689

### Environment
MODX 3.x

**Comment by JoshuaLuckers** [comment] 2021-08-31 07:26
@opengeek is this still on your radar?

**Comment by opengeek** [comment] 2021-08-31 12:59
I'm not sure why this was assigned to me. The summer of 2020 was a rough time. But to answer your question, no, it's not on my radar.

**Comment by raffy99** [comment] 2021-08-31 13:06
This is related, isn't it? https://github.com/modxcms/revolution/pull/15166#issuecomment-664666031

**Comment by JoshuaLuckers** [comment] 2021-09-01 07:07
> I'm not sure why this was assigned to me. The summer of 2020 was a rough time. But to answer your question, no, it's not on my radar.

You assigned it to yourself, most likely because the issue is caused by changes you made in PR #14689.
It's trying to serialize an array, however when this array has elements that can't be serialized it throws an Exception. 

```
$propTemp[$key] = $key . '=`' . (is_array($value) ? md5(serialize($value)) : md5(uniqid(rand(), true))) . '`';
```

We could fix it by using a try/catch block. If we catch an exception we don't serialize `$value`.

**Comment by opengeek** [comment] 2021-09-01 13:02
There's another PR that addressed/addresses this. I thought it was already merged, but I guess not. And though technically I am on the blame for that change, it was from another contributor. I just assigned it to myself because no one else was around that summer. 😂

**Comment by opengeek** [comment] 2021-09-01 13:19
#15467

**Comment by JoshuaLuckers** [comment] 2021-09-05 12:50
@opengeek I made a new PR with some improvements over #15467

**Closed as completed** 2021-10-01 19:39 UTC
Labels: bug, area-core
