### ISSUE TITLE
When updating multiple extras, setup options window title shows the previously updated extra

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#13879] opened 2018-04-26 08:04 UTC
### Summary
While updating extras, I noticed if two extras with setup options were updated consecutively, the second extra's setup options window has the title of the previous extra's setup options window. The actual contents of the setup options window was correct though.
I noticed that if I refreshed the page between updating extras, this did not occur.

### Step to reproduce
Try updating multiple extras with a setup options window consecutively.

### Observed behavior
The setup options window did not have the correct title. It was the title of the previously updated extra.

### Expected behavior
The setup options window for each extra should have its own title.

### Environment
MODX 2.6.3 PHP 7.1 Apache MySQL

**Comment by ghost** [comment] 2018-04-26 09:25
I thought that was fixed several releases ago. https://github.com/modxcms/revolution/pull/13557

**Comment by Jako** [comment] 2018-04-26 10:00
It is just the title of that window that does not change.

`this.win.title` has to be modified in the else branch there, if I am right.

**Comment by muzzwood** [comment] 2018-04-26 11:43
Yeah this is just the title. That older bug would try to reinstall the previous extra.

**Comment by Jako** [comment] 2018-10-18 21:35
This is some special issue caused by some javascript, that runs i.e. in STERC extras. The title is not changing by default. But it can be fixed.

**Comment by alroniks** [comment] 2018-11-05 08:54
Closed as related PR is merged.

**Closed as completed by alroniks** 2018-11-05 08:54 UTC
