### ISSUE TITLE
404 and 403 page response status 200 ОК

### ISSUE THREAD

**Issue by nuykon** [modxcms/revolution#13862] opened 2018-04-11 11:18 UTC
Pages marked in the settings as 403 and 404 give the code 200
We have to close them from indexing in the robots.txt file, although it would be more logical to give the appropriate codes in the header.

Modx Revo 2.6.2

**Comment by jonleverrier** [comment] 2018-04-19 13:35
@nuykon I can't reproduce this issue on my installation of MODX 2.6.2. See screen shot of a page not found (it's generating a 404 not 200);

<img width="702" alt="screen shot 2018-04-19 at 15 33 12" src="https://user-images.githubusercontent.com/2373940/38994640-392a733c-43e7-11e8-9335-5dc0fe54caf0.png">

**Comment by gpsietzema** [comment] 2018-04-19 13:37
Same here. I kind of remember this issue existed some time ago, but don't have this on my current installations.

**Comment by JoshuaLuckers** [comment] 2018-11-20 14:33
@nuykon are you able to reproduce this in 2.7.0-dev?

**Comment by Ibochkarev** [comment] 2019-02-10 04:10
@nuykon Please give feedback. Is it relevant?

**Comment by OptimusCrime** [comment] 2019-02-11 17:16
Close this?

**Comment by Jako** [comment] 2019-02-11 17:29
Closing this due to lack of feedback. Please reopen the issue, if it is still relevant.

**Closed as completed by Jako** 2019-02-11 17:29 UTC
Labels: area-core
