### ISSUE TITLE
tv will not be deleted if delete from categories in left menu

### ISSUE THREAD

**Issue by Extrabash** [modxcms/revolution#16487] opened 2023-10-22 13:04 UTC
### Summary
Try to delete a tv, by clicking right mouse - delete, in left menu  in categories.
Will throw - cant find processor 'element/c/remove'

### Step to reproduce
Try to delete a tv, by clicking right mouse - delete, in left menu  in categories.

### Observed behavior
Will throw - cant find processor 'element/c/remove'

### Expected behavior
To delete a tv.

### Environment
MODX version 2.8.5

**Comment by halftrainedharry** [comment] 2023-10-22 16:33
> by clicking right mouse - delete, in left menu in categories.

By this, do you mean the option displayed in the image below?

![modx_manager_element_tv_delete](https://github.com/modxcms/revolution/assets/85392304/f60ca52e-7b04-47f0-889c-5d789413b7f8)

If 'yes', then I can't reproduce the issue. Deleting a TV works fine when I test it.

**Comment by halftrainedharry** [comment] 2023-10-22 16:49
OK sorry, I now see what you meant.

The issue occurs in the **vertical tab "Categories"** when trying to remove a TV.

![modx_manager_element_categories_delete](https://github.com/modxcms/revolution/assets/85392304/9900cf45-bdd9-438e-8a71-75e00bd19c2b)

The same error is also shown for other elements like snippets or templates.

**Comment by rthrash** [comment] 2023-10-24 22:25
Awesome work @halftrainedharry and @smg6511 … thanks!

**Comment by smg6511** [comment] 2023-10-24 22:55
@halftrainedharry - I assume, since you closed this PR, you want me to apply the changes I made for my 3.x PR for 2.x as well. Let me know if that's the case or if you're working on it.

**Closed as completed** 2024-03-25 15:02 UTC
Labels: bug
