### ISSUE TITLE
Media Source and access permissions

### ISSUE THREAD

**Issue by Kidokyfe** [modxcms/revolution#12212] opened 2014-12-14 19:19 UTC
Hello,
If I don't have sudo, but am in the administrators group. I do not see the source files with a minimal role "Super User - 0" and politics "Media Source Admin" Although I am in the administrators group.
![default](https://cloud.githubusercontent.com/assets/6079787/5428705/757e3cba-8400-11e4-954d-ad3df4ce99ef.PNG)

**Comment by alroniks** [comment] 2021-03-31 21:45
I am closing it because it does not have enough information to reproduce, also the comment (in Russian) said, that it can not be reproduced. Feel free to reopen.

**Closed by alroniks** 2021-03-31 21:45 UTC
