### ISSUE TITLE
Errors on [friendly_urls_strict = Yes] + [container_suffix = empty] + request non-existent page

### ISSUE THREAD

**Issue by cyrax-02** [modxcms/revolution#12307] opened 2015-01-29 10:19 UTC
I've encountered the following errors. If set simultaneously follow settings:
1) [friendly_urls = Yes]
2) [friendly_urls_strict = Yes]
3) [container_suffix =''](empty)

and then request non-existent page (uri) is followed by two warnings in modx logs:
1) '' isn't a valid integer and may not be passed to makeUrl
2) Attempted to redirect to an empty URL

At the same time page 404 is loaded normally.
# 

This problem is localized in modRequest::_cleanResourceIdentifier() method. Here need impove condition
[if ($found === false && !empty ($containerSuffix)) { ...]
to
[if($found === false) { if(!empty ($containerSuffix)) { ... ]

or in code fragment
[if ($this->modx->getOption('friendly_urls_strict', null, false)) { ...]
add condition
[... && ($found !== false) ...]

P.S. Sorry for my english...

**Comment by cyrax-02** [comment] 2015-01-29 10:23
This problem occur in modx revo 2.3.2

**Comment by syts88** [comment] 2017-03-03 09:50
I'm going to try and fix/test this today. #modxbughunt

**Comment by syts88** [comment] 2017-03-03 10:08
Cannot reproduce this bug. Tested on Modx 2.5.5. 

Steps i took where;

- Changed system settings to the values as defined in the start post of this issue
- Cleared error log
- Went to a non-existent page.

**Behaviour**
Got redirected to the homepage which is set as mine error page. The error log stays empty. So it seems to be fixed in MODX Revo 2.5.5

#modxbughunt

**Comment by rtripault** [comment] 2017-03-03 10:10
So closing.
Please feel free to comment/reopen if needed.

Thanks

**Closed by rtripault** 2017-03-03 10:10 UTC
