### ISSUE TITLE
Error Page Fallback

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#14107] opened 2018-10-10 04:59 UTC
### Summary
Not having a defined error page causes a site to collapse

### Step to reproduce
Set the error page to a non resource match value

### Observed behavior
Site times out on 404 of simple things, e.g. favicon.ico

### Expected behavior
If error page undefined or id doesn't exist should 404 and return site_start 

### Related Issues
#13659

**Comment by JoshuaLuckers** [comment] 2018-10-10 06:32
Thanks for reporting this issue.

I'm able to reproduce it with an error message:
> Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /path/to/modx/core/xpdo/om/xpdoquery.class.php on line 843

There is an infinite redirect between `$modX->sendErrorPage( )` and `$modX->sendForward( )` when the error_page points to a non-existing resource.

**Comment by jonleverrier** [comment] 2018-10-12 09:17
I can reproduce this issue too. 

However, if I have missing assets like a favicon, the page still loads. It only times out if I load a page that doesn't exist (because the `error_page` doesn't exist).

**Comment by Jako** [comment] 2018-10-15 13:29
The fix was merged.

**Closed as completed by Jako** 2018-10-15 13:29 UTC
