### ISSUE TITLE
Modx crashes during installation if the server pasword includes a '

### ISSUE THREAD

**Issue by HadashiBlacksky** [modxcms/revolution#14043] opened 2018-08-12 15:52 UTC
### Summary
I think Modx crashes are being caused by symbols such as ' in the server password and I have found evidence online that this issue has been around for several years. This seems like a very simple thing that should be fixed.

### Step to reproduce
Put a ' mark in your server password.

### Observed behavior
Gave an error when trying to install Modx

### Environment
MODX version latest, apache 2.2.34, mysql version 5.6.32-78.1, browser Firefox

**Comment by Mark-H** [comment] 2018-08-12 16:37
This was fixed in 2.3.6 as far as I know with #12528 - are you 100% sure this behavior is reproducible in 2.6.5?

**Comment by JoshuaLuckers** [comment] 2018-08-18 11:55
@HadashiBlacksky we would love to know if you are able to reproduce this in the latest version of MODX. If it's still present in the latest release it would be really helpful if you could post the error message you get. 

Thank you for helping make MODX better.

**Comment by JoshuaLuckers** [comment] 2018-09-04 06:45
I'm closing this issue because we have not received any response. Feel free to reopen this issue when additional info is provided.

@modxbot close

**Closed as completed** 2018-09-04 06:45 UTC
