### ISSUE TITLE
Feature Request: Add createdon createdby,etc to chunk,snippet and plugin tables

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13258] opened 2017-01-20 11:47 UTC
Today I had a look at a compromised modx installation. Two plugins had been added to the installation causing pharmacy links to appear on the homepage.

The get to the root of problems like this, It would be very helpful to store information in the effected tables for all elements (plugins, chunks, tvs, templates and snippets):

* createdon
* createdby
* editedon
* editedby

For plugins it would also be useful to add
* disabledon
* disabledby 

I see the following advantages for this feature:

* It would make it easier to understand the context of changes to important parts of a MODX installation. 
* It would also be consistent with the way resources are treated.

Regards,

pepebe

**Comment by sottwell** [comment] 2017-01-20 13:50
Did you check the manager actions log? They'll tell you who worked with what element and what action was performed on it and when.

![screen shot 2017-01-20 at 15 50 06](https://cloud.githubusercontent.com/assets/1073780/22151768/2c4e03ec-df28-11e6-9661-b5429f795d53.png)

**Comment by pepebe** [comment] 2017-01-21 10:47
@sottwell,
I'm aware about this. It seems that either the manager actions logs was limited to about 100 entries in prior versions (2.2.x), or the attacker removed all relevant data from the manager log.

I think consistent use of important data is always a good thing. It can help to solve minor problems in day to day work and in edge cases it might give an extra hint to understand important details.

**Comment by rtripault** [comment] 2017-03-03 08:44
Closing as duplicate of #2027 #modxbughunt

**Closed by rtripault** 2017-03-03 08:44 UTC
Labels: area-core, enhancement, state/accepting-pull-request
