### ISSUE TITLE
Invalid path for the unzipped file on MODX Revo 2.8.4

### ISSUE THREAD

**Issue by chrisdindev** [modxcms/revolution#16253] opened 2022-08-24 06:30 UTC
On MODX Revo 2.8.4-pl, please help, am getting this error when unzipping file via tree manager or media browser.

Invalid path for the unzipped file.: C:/xampp_new/htdocs/creative-studio/assets/themes%2Fth01%2Farsha.zip (having this symbol on path makes the error I believe. %2F) though I tried replicating it on 2.8.3 unzipping files has no issue.

![image](https://user-images.githubusercontent.com/67990103/186346725-5f3ea26e-38b6-4037-9c30-f66b9d7d4048.png)

**Comment by halftrainedharry** [comment] 2022-08-24 08:02
This seems to be a duplicate of the issue #16188

**Comment by chrisdindev** [comment] 2022-08-24 08:05
> This seems to be a duplicate of the issue #16188

Thank you, I've been searching for the same issue. Thanks for this info.

**Comment by Ibochkarev** [comment] 2022-08-24 08:24
Fixed https://github.com/modxcms/revolution/pull/16202

**Closed as completed by Ibochkarev** 2022-08-24 08:24 UTC
Labels: bug
