### ISSUE TITLE
Complete deletion of one resource

### ISSUE THREAD

**Issue by sartatpdev999** [modxcms/revolution#13625] opened 2017-10-04 07:38 UTC
### Summary
There is no way to completely remove **only one** resource. A user can destroy all softly removed resources by clicking on trash icon. But it's unavailable to completely remove **only one** resource from resource tree.

### Step to reproduce
Add an item to context menu with the function (callable by right-clicking on a resource in the resource tree) of complete deletion of a resource.

### Environment
MODX Revolution 2.5.8-pl

**Comment by OptimusCrime** [comment] 2017-10-04 08:17
Duplicate of #13617

@modxbot close

**Closed by OptimusCrime** 2017-10-04 08:17 UTC

**Comment by Jako** [comment] 2017-10-04 08:22
I don't think that a change in that part makes much sense: At home I am sometimes happy to rescue single things from trash but not to take one thing from trash to the ‚real trash‘. Trash is a trash and not a temporary store.

**Comment by OptimusCrime** [comment] 2017-10-04 08:28
And I agree with @Jako. This has been up for discussion countless times. I like the system as it is today. Nothing should ever be marked for deletion unless it really can be deleted. This means that every time you empty the trash can you removed everything that was supposed to be deleted. If we introduce a "delete permanently" feature, we differentiate between deleting and "deleting harder". However, with the inclusion of the trash overview before emptying the trash, people will hopefully get a better overview of which resources are deleted. I like that.

**Comment by Alroniks** [comment] 2017-10-04 09:34
Added my five cents. I also like how it implemented now and it isn't required to change this behavior. For solving the issue with granular permanent deleting make sense to create a very simple extra "Trash Manager" like it works on Windows or macOS (Bin).

**Comment by OptimusCrime** [comment] 2017-10-04 10:18
If I get the time, I'll see if I can write a extra like this really fast. Perhaps this would be enough to keep it out of the core itself.
