### ISSUE TITLE
Enable using snippets in listbox TV input option values

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#14956] opened 2020-01-16 15:38 UTC
### Summary
@<span></span>EVAL binding is being dropped, so we can do longer do this:

@<span></span>EVAL return $modx->runSnippet('mySnippet')

### Why is it needed?
We need a way to continue to use snippets to create custom input lists. We can use @<span></span>CHUNK and then put a snippet in the chunk, but why use two steps?

### Suggested solution(s)
Create a "@<span></span>SNIPPET" binding for input values.

@<span></span>SNIPPET mySnippet

**Comment by Bruno17** [comment] 2020-01-16 15:56
duplicate of #14074

**Comment by SnowCreative** [comment] 2020-01-16 16:20
Ah. I though maybe someone would have submitted this request before, but you can't search for "@<span></span>SNIPPET" in the github search box

**Closed as completed** 2020-01-16 17:09 UTC
