### ISSUE TITLE
Function/feature terminology mismatch on Plugins

### ISSUE THREAD

**Issue by nitrojane** [modxcms/revolution#12900] opened 2016-02-11 01:35 UTC
Plugins - using the shortcut menu (right-click) the user has the option of Activating or Deactivating the plugin whereas on the Create/edit plugin page the user has the option to check Plugin Disabled or not. Need to standardize terminology if they're the same function.

**Comment by whitebyte** [comment] 2016-02-16 13:14
Duplicate of  #9523

**Comment by nitrojane** [comment] 2016-02-16 15:56
I wasn't reading for comprehension obviously - didn't see the other issues that are related. Should I close this?

**Closed** 2018-11-08 12:17 UTC
Labels: area-ux/ui, enhancement, state/accepting-pull-request
