### ISSUE TITLE
No way to undo publishedon setting in Create/Edit Resource panel

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12630] opened 2015-09-04 05:49 UTC
If you accidentally select a Published On time and date (meaning to set pub_date). There's no way to return it to an empty state. You can blank it out, but when you save the resource, it reverts to the accidental setting.

This may prevent publication on the pub_date setting. If it doesn't it's not a big deal, but it should be possible to blank it out.

**Comment by OptimusCrime** [comment] 2017-03-03 18:03
I am able to clear the content of these input fields. Closing as fixed :)

@modxbot close

**Comment by OptimusCrime** [comment] 2017-03-03 18:03
@modxbot close

**Closed by OptimusCrime** 2017-03-03 18:03 UTC

**Comment by BobRay** [comment] 2017-03-04 20:13
This is still pretty funky. 

Try this:

1. Set the publish_default System Setting to No
2. Create a new document and give it a pagetitle and alias
3. Confirm that the Published checkbox is empty
4. On the Settings Tab, set the Published Date field to 10 minutes in the future
5. Save the resource 

Published Date is emptied and Published On is set -- This seems wrong to me, since publication shouldn't have occurred yet.

Now (before the pub_date has been reached), blank out the the Published On date and reload.
The resource will be published, even though you did your best to cancel the publication.

**Comment by OptimusCrime** [comment] 2017-03-05 13:49
Are you sure? I am unable to reproduce this. If I chose a date in the future (having published checked) and I reload, then published is removed and the published date is still present. Are you sure the webserver is using the same timezone as you?

**Comment by BobRay** [comment] 2017-03-09 05:15
My bad. By setting a pub_date 10 minutes in the future, the interval was below the granularity of the publication algorithm, so the resource got published as soon as I saved it.

Go ahead and close this.

**Comment by OptimusCrime** [comment] 2017-03-09 11:24
Ah. That makes sense. Thank you for investigating :)
