### ISSUE TITLE
Possibility to log insufficient credentials

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13766] opened 2018-02-09 12:50 UTC
### Summary
Possibility to log insufficient credentials

### Step to reproduce
At the moment it is quite impossible to notice which ACL credential is missing, when something does not work in the backend. The requested missing credential should be logged when a system setting is active.

### Environment
MODX 2.6.x and below

**Comment by bezumkin** [comment] 2018-02-09 14:20
https://github.com/modxcms/revolution/issues/12693

I believe it should be logged right now on debug level. There will be a lot of messages, but it very useful anyway.

**Comment by wuuti** [comment] 2018-02-10 18:13
Yeah, you will definetely end up with a lot of messages there, and its kind of hard to see which actual permission is missing, but at least all the checked permissions are logged then and you get an idea of which might be the one causing the problems.

**Comment by Mark-H** [comment] 2018-02-11 16:21
Closing as duplicate of #12693 (for which I've updated the title to make it easier to find when search for ACLs)

**Closed by Mark-H** 2018-02-11 16:21 UTC
