### ISSUE TITLE
MODX 3: Dashboard - Buttons not full width. Bug or by design?

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13964] opened 2018-07-03 13:44 UTC
### Summary
The new dashboard buttons don't appear to be full width, which looks odd when comparing this block of content to the other full width content on the same page. I appreciate this may be by design.

![screen shot 2018-07-03 at 15 31 08](https://user-images.githubusercontent.com/2373940/42222739-4812a2aa-7ed6-11e8-9275-4307ec125bf8.png)

### Step to reproduce
Login to the manager and view the dashboard buttons.

### Observed behavior
Notice how the buttons are not full width compared to the rest of the content on the page.

### Expected behavior
For the buttons to go full width, like the working demo below:

![modx3_dashboard_buttonbug](https://user-images.githubusercontent.com/2373940/42223101-3cceb900-7ed7-11e8-8763-970e824c43b4.gif)

### Fix

```
.dashboard-buttons {
    display: flex;
    /* flex-wrap: wrap; */
    justify-content: center;
    width: calc(100% + 1rem);
    margin: -1rem 0 0 -1rem;
    flex-wrap: nowrap;
}
```
```
.dashboard-buttons .dashboard-button {
    display: flex;
    align-items: center;
    background-color: #FFF;
    border-radius: 3px;
    box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.1);
    margin: 1rem 0 0 1rem;
    padding: 20px;
    text-decoration: none;
    color: #53595F;
    /* max-width: 185px; */
    justify-content: flex-end;
    flex-grow: 1;
}
```
```
.dashboard-buttons .dashboard-button-wrapper {
    flex-grow: 1;
    margin-left: 10px;
}
```

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by muzzwood** [comment] 2018-07-04 02:35
I remember seeing a mock-up of the dashboard buttons looking differently (much better) and had just assumed this was a temporary solution to build the functionality while waiting for the final design to be applied.
Anyone know?

**Comment by jonleverrier** [comment] 2018-07-18 17:41
Can anybody confirm if this needs fixing. Perhaps @gpsietzema or @Mark-H . If so, i'll send in a PR.

**Comment by alroniks** [comment] 2018-07-28 08:37
I would like to fix it too. Maybe it's by design, but in this case it's a bad design. 
@jonleverrier If you could provide a PR, it would be nice to see what's better in the result and after just merge it.

**Comment by jonleverrier** [comment] 2018-07-29 08:45
@Alroniks Thanks for confirming. I'll submit a PR when I get back from holiday shortly.

**Comment by alroniks** [comment] 2018-11-05 12:32
Fixed. PR is merged.

**Closed as completed by alroniks** 2018-11-05 12:32 UTC
Labels: type-frontend, bug
