### ISSUE TITLE
Absent Snippet Logging

### ISSUE THREAD

**Issue by amdbuilder** [modxcms/revolution#12694] opened 2015-10-02 20:21 UTC
### Summary
Log attempts to use non-existant snippets

### Step to reproduce
Attempt to use a snippet that isn't installed.

### Observed behavior
https://twitter.com/sepiariver/status/646834408788393984

### Expected behavior
Indicate the snippet being called and the location of that call if possible (ie: resource id, chunk name, template name) in the MODX Error Log

### Environment
Any Version

**Comment by whitebyte** [comment] 2015-10-02 21:07
#12467

**Comment by OptimusCrime** [comment] 2016-04-20 00:22
Duplicate of #12467. Closing in favor of issue with more comments.

@modxbot close

**Closed by OptimusCrime** 2016-04-20 00:22 UTC
