### ISSUE TITLE
Smarty Compiler: Syntax error - MODX 2.8.0

### ISSUE THREAD

**Issue by ishryal** [modxcms/revolution#15306] opened 2020-10-21 04:41 UTC
Recently updated MODX from 2.7.3 to 2.8.0, and came across a PHP critical error when the manager attempted to parse the manager/templates/default/element/tv/renders/input/url.tpl file:

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/manager/templates/default/element/tv/renders/input/url.tpl"  on line 42 ",listeners: {'keydown': {fn:MODx.fireResourceFormChange, scope:this}}"  - Unexpected ": ", expected one of: "}" <-- 
  thrown in /home2/valiant1/core/model/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 42

I managed to get it to work again by placing a space before the 'keydown' text:

,listeners: { 'keydown': { fn:MODx.fireResourceFormChange, scope:this}}

I noticed that most of the other input TPL files had this same fix, or used {literal} to escape that line of code.

**Comment by Ibochkarev** [comment] 2020-10-21 04:49
@ishryal Thanks

This is fixed in PR #15279

@modxbot close

**Closed as completed by Ibochkarev** 2020-10-21 04:49 UTC

**Comment by opengeek** [comment] 2020-10-21 04:50
This is a duplicate of #15288. This is fixed in #15279 and will be available in 2.8.1 shortly.
