### ISSUE TITLE
Installer Button Text

### ISSUE THREAD

**Issue by EkoOne** [modxcms/revolution#13081] opened 2016-07-22 17:08 UTC
The problem with off-center button text persists in 2.5.1. Here's the original 2.5.0 issue, https://github.com/modxcms/revolution/issues/13048

![installer-button](https://cloud.githubusercontent.com/assets/1754223/17064920/b6d5e948-5004-11e6-99b6-44139c5fadd1.png)

**Comment by pixelchutes** [comment] 2016-07-22 17:21
@EkoOne one suggestion would be to try clearing your browser cache, or test in alternate browser, if necessary?

I have personally seen this be resolved in `2.5.1`, so ruling out your local cache would be a good first step at understanding why you're still experiencing this.

**Comment by EkoOne** [comment] 2016-07-22 20:44
@pixelchutes I already tried everything you suggested before (re)posting the issue, but the result was the same.

Unless my server is _aggressively_ caching (a possibility, I suppose) then I don't know what else could be causing the problem.

**Comment by pixelchutes** [comment] 2016-07-22 21:03
What means of installation did you use for 2.5.1? Git? Traditional or Advanced download?

Also, what are your system settings currently for the `compress_css`? Does toggling have any effect?

**Comment by Jako** [comment] 2016-07-22 21:14
It was fixed in #13078 and #13057. so maybe a Proxy or something else could serve the old versions of both changed scripts.

**Comment by EkoOne** [comment] 2016-07-22 21:19
@pixelchutes I used the Traditional dist.

Both "compress" settings are disabled. Turning them both on has no effect.

If you guys say it was fixed then I believe you. Clearly I have gremlins. Thankfully it's a benign problem for me.

**Comment by Jako** [comment] 2016-07-22 21:58
Maybe the files are not updated for some reason. Please check if the changes of both commits are in the uploaded files. And please check if they are changed in the 2.5.1 download. That could help to locate your current issue.

**Comment by pixelchutes** [comment] 2016-08-15 22:44
Appears to be a localized issue, perhaps try re-installing to ensure necessary updated css/js files are correct and in place? Considering resolved, cannot reproduce.

**Closed by pixelchutes** 2016-08-15 22:44 UTC
