### ISSUE TITLE
When have more than 20 template variables got 20 browsers refreshes

### ISSUE THREAD

**Issue by Codenator81** [modxcms/revolution#12450] opened 2015-05-20 09:16 UTC
When I add on 2.3.2 many template variables got browser refreshes. It is language design problem?
extjs problem? Can we rebuild template variable to make it more powerful?

**Comment by OptimusCrime** [comment] 2015-06-09 22:44
Unless there is more information here I suggest closing. I have no idea what the issue is here.

**Comment by rthrash** [comment] 2015-06-09 22:46
Can you provide more details on how to reproduce this @Codenator81? Thanks!

**Comment by Codenator81** [comment] 2015-06-10 00:39
There issue not about 20 TV but about browser refreshes as many time as TV is in document. If u look in browser tab when navigate to document and open TV tab there something like refreshes. Just my client complain about this and I reproduse

**Comment by OptimusCrime** [comment] 2015-06-10 00:40
I am pretty sure those are ajax calls?

**Comment by Codenator81** [comment] 2015-06-10 05:44
yes

**Comment by OptimusCrime** [comment] 2015-06-10 11:08
Well...I think that is intended behavior. I can't understand what is wrong with those ajax calls?

**Comment by TheBoxer** [comment] 2015-06-16 13:22
I don't really understand the problem here... 

Data for TVs are not fetch via AJAX, but from Resource controller.

**Comment by OptimusCrime** [comment] 2015-06-16 15:22
Me neither

**Closed** 2015-06-16 17:21 UTC
