### ISSUE TITLE
[BUG] Error warning "Code 200 OK" because of lacking permission in "Content Editor" policy

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#13505] opened 2017-07-07 10:57 UTC
### Summary
When a user with "Content Editor" policy wants to open an resource, he gets an error warning but can work on. So he's able to work on but the error modal is annoying.

<img width="795" alt="view_template_problem" src="https://user-images.githubusercontent.com/458619/27955101-7555847e-6313-11e7-8369-55924a6b5d5f.png">

### Step to reproduce
Use a (fresh) install, create a user for the contexts "mgr,web" with role "member" and policy "Content Editor". Open the default resource "Home (1)" and watch.

### Observed behavior
See "Steps to reproduce".

### Expected behavior
See nothing. ;-) This can be achieved by giving the "Content Editor" the permission "view_template" which should be default in the ACL.

<img width="531" alt="view_template_solution" src="https://user-images.githubusercontent.com/458619/27955116-894503a6-6313-11e7-8d16-48532c0f4107.png">

### Environment
Any.

**Comment by gernotebenlechner** [comment] 2017-07-07 10:58
already working on that at #modxbughunt

**Comment by Mark-H** [comment] 2017-07-07 11:35
Dupe of #13243 (and a few others I think).

**Closed by Mark-H** 2017-07-07 11:35 UTC

**Comment by gpsietzema** [comment] 2017-07-07 12:25
#modxbughunt #1point @gernotebenlechner

**Comment by gpsietzema** [comment] 2017-07-07 15:46
#modxbughunt #1point to @Mark-H
