### ISSUE TITLE
Make Installer always top menu item

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#11694] opened 2014-07-15 21:02 UTC
Screenshot: http://sepiariver.co/1nF7Xav

The "Installer" is arguably the most important or at least it's different enough from the installed components that it should some how be demarcated.

**Comment by Alroniks** [comment] 2017-02-09 19:34
@OptimusCrime I agreed with @argnist It should be fixed. In top menu we have dropdown, but I hope in future versions it will the simple link to installer, but now Intaller should be first always to avoid confusing users.

**Comment by sottwell** [comment] 2017-02-09 20:05
I know this came up some time ago, I thought it got fixed? Is this a regression?

**Comment by sebastian-marinescu** [comment] 2019-03-12 10:18
I just wanted to open a new feature-request about this and then this showed up in the suggestions. 

So yeah, this is still very annoying. I find myself very often "searching" for this entry... 
Then I go to the menu-management and drag it up. After some updates to extras, I have to search again, because it is again on a completely different position. 

I've just tested via phpmyadmin to give the installer-entry a menuindex of `-1`, but that doesn't seem to work. So I thought I'd give it a position of `100` - so it always sticks to the bottom - that get's changed when dragging around another menu-entry, because then all entries all of a sudden get a numbered menuindex. But at least on new entries this would still be at the bottom. 

So how about this as a workaround?

**Comment by sebastian-marinescu** [comment] 2019-03-12 10:35
Okay, I'm doing it. Do you @JoshuaLuckers think a menuindex of "10" should be sufficient?

**Comment by Ruslan-Aleev** [comment] 2019-03-12 10:40
@sebastian-marinescu It seems to me that it is better to reorganize the menu already for MODX3, look, maybe you will have some suggestions yet - https://github.com/modxcms/revolution/issues/14291

**Comment by sebastian-marinescu** [comment] 2019-03-12 11:03
@Ruslan-Aleev Thanks for pointing me to that, I'll check it out. 

Until MODX3 there is still an unforeseeable time, and in this time also new users will come to MODX2, and maybe MODX2 will also be longer around than expected - so in my opinion this is still a valid issue until a new major will be released this should and can be "fixed" at least for new MODX2 installations.

**Comment by Mark-H** [comment] 2019-03-12 13:53
Putting it at the bottom is not very great. :(  

What I'd suggest we try (I haven't looked at the relevant code yet) is to add some extra code into the menu builder that makes sure the installer is always first. 

Something like an `ORDER BY field(modMenu.key, 'installer') ASC` (but in xPDO) before the menuindex sort is applied.

**Comment by ghost** [comment] 2019-03-12 13:56
Or just have the Installer, then add the menu after it. LIke hard-coding an li element into the outerTpl of pdoMenu.

**Comment by sebastian-marinescu** [comment] 2019-03-13 10:58
I agree that it's not ideal, but at least better than always searching inside the list for it. 

Both of your suggestions sound apparently better, if this can be accomplished.

**Comment by sebastian-marinescu** [comment] 2019-03-20 17:29
I've added a new commit to https://github.com/modxcms/revolution/pull/14482 that will put the installer-entry always to the top.

**Comment by Ibochkarev** [comment] 2019-07-31 11:01
Related #14482

**Comment by sebastian-marinescu** [comment] 2019-07-31 12:12
Yeah, it still awaits reviews by @Mark-H and @opengeek

**Comment by jaygilmore** [comment] 2021-02-24 18:17
I'm not sure if anyone's reviewed this lately but this does feel like a quick win fix that could either go in 2 or 3.

**Closed** 2023-08-29 20:01 UTC
Labels: type-frontend, proposal, urgent, pr/port-to-3
