### ISSUE TITLE
(Enhancement + Code) Manager doesn't show users fullname in header

### ISSUE THREAD

**Issue by JensWolff** [modxcms/revolution#12457] opened 2015-05-25 22:33 UTC
Hey guys,
I was wondering why the manager doesn't actually shows the fullname as "Username" of the user who is logged into the manager (next to the gravatar-image), so I solved this issue by myself.

If the fullname-field ist empty, there is a fallback to the actual "username":
![2015-05-26_00h31_23](https://cloud.githubusercontent.com/assets/754205/7802819/a0dc6752-033e-11e5-85ef-8bbec861b869.png)

But if the fullname-field is filled, it gets used, to show the much cleaner fullname:
![2015-05-26_00h31_03](https://cloud.githubusercontent.com/assets/754205/7802832/bff8d3aa-033e-11e5-9ded-1815f6e799d9.png)

Replace the function "setPlaceholders" (starting at line 78) in the file "manager/controllers/default/header.php" with the following to get it work:
==============================================================

    public function setPlaceholders()
    {
        
        $userProfile = $this->modx->user->getOne('Profile');
        $username = $userProfile->get('fullname');
        if(empty($username)) $username = $this->modx->getLoginUserName();
        $placeholders = array(
            'username' => $username,
            'userImage' => $this->getUserImage(),
        );

        $this->controller->setPlaceholders($placeholders);
    }

==============================================================

Many greeting from germany
Jens

**Comment by zaigham** [comment] 2015-05-25 22:35
You should do a Pull Request. :+1:

**Comment by JensWolff** [comment] 2015-05-25 22:38
@zaigham The problem is, that I am still not very familiar with Git to do so :D

**Comment by pixelchutes** [comment] 2015-05-26 17:31
Not sure if it was by design, but my gut says it could be accounting for the already limited space in the navbar (see #11411 and #11430)

That aside, this could be a great candidate for a system setting for more control / consistency.

**Comment by JensWolff** [comment] 2015-05-26 17:51
@pixelchutes A system-setting to enable it would be perfect! :+1:

**Comment by OptimusCrime** [comment] 2015-06-09 22:47
System settings seemst to be the solution for almost everything in Modx. I am negative for the suggested feature too. This does not add anything crutial to Modx.

**Comment by wuschigesetwas** [comment] 2015-07-24 15:37
if anyone needs a patch https://github.com/modxcms/revolution/issues/12457

**Comment by JensWolff** [comment] 2015-07-24 15:38
Thanks, bro :-* :+1: :+1:  :+1:

**Comment by wuschigesetwas** [comment] 2015-07-24 15:48
you're welcome :) :-*

**Comment by Mark-H** [comment] 2015-08-04 12:14
Merged into 2.4

**Closed by Mark-H** 2015-08-04 12:14 UTC
