### ISSUE TITLE
Fatal fread() error when upgrading extras

### ISSUE THREAD

**Issue by davidpede** [modxcms/revolution#16636] opened 2024-10-24 10:08 UTC
### Summary
I am getting a fatal 500 error when upgrading the Fred extra:
`PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /core/xpdo/compression/pclzip.lib.php:2680`

Is caused by empty files in the extra such as: https://github.com/modxcms/fred/blob/main/assets/components/fred/index.html

I believe this is a PHP 8+ compatibility issue as fatal errors can no longer be supressed: https://php.watch/versions/8.0/fatal-error-suppression

### Step to reproduce
Install or upgrade an extra such as Fred that contains zero byte files.

### Observed behavior
Install fails with fatal 500 error:
`PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /core/xpdo/compression/pclzip.lib.php:2680`

Related code:
https://github.com/modxcms/revolution/blob/a296ee3558810fa68df3d62f81f99a7531ff2118/core/xpdo/compression/pclzip.lib.php#L2678

### Expected behavior
Extra should install successfully.

### Environment
MODX 2.8.7-pl, PHP 8.2

**Comment by halftrainedharry** [comment] 2024-10-24 17:05
This seems to be a duplicate of [this issue](https://github.com/modxcms/xpdo/issues/258) in the xPDO repository.

The problem is the PclZip library (that is no longer maintained). PclZip is only used if your PHP installation doesn't have the zip extension (or if the system setting `archive_with` is explicitely set).

**Comment by smg6511** [comment] 2024-11-29 04:53
@davidpede - If this is not the same issue as referenced by @halftrainedharry, please re-post it on the XPDO repo. The XPDO package is maintained separately.

**Closed as completed by smg6511** 2024-11-29 04:53 UTC
Labels: bug
