### ISSUE TITLE
moduser.class.php: Can't programmatically add user to a user group without assigning a role 

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11883] opened 2014-08-07 21:38 UTC
With the current `joinGroup` method of the `moduser.class.php` its not possible to programmatically add a user to a group without assigning a role. Because if you pass 0 as role value the role field in `modx_member_groups` table will always be set to the fields default value 1.

Both of the following method calls will lead to a role 1 (= Member):

```
$user->joinGroup(intval($group), 0);
$user->joinGroup(intval($group));
```

The problem lies here:

https://github.com/modxcms/revolution/blob/master/core/model/modx/moduser.class.php#L668

and here:

https://github.com/modxcms/revolution/blob/master/core/model/modx/moduser.class.php#L688

Its only possible to set the role to 0=NONE in the manager while editing a users access permissions.

**Comment by wshawn** [comment] 2015-08-12 11:51
No. Users should not be allowed to be added to a group without a role. Ever.

It violates ACL understanding: users must have roles (permissions).

The user should simply be assigned role of 9999 (anonymous).

I do this to track new users to membership sites as to their Organization type. This can also be done for mail lists.

Essentially the groups are 9998 and the role is 9999 or 9998 which are effectively copies of the anonymous but with names.

This is the correct method to set up non-permission roles:
```
Create a new Group
Provide a name
Under Permissions - set the minimum role to Member - 9999 (anonymous)
                               - access policy = Resource
                               - context = web
```
If you so desire you could use the wizard and create a companion Resource Group.

This is an effective and simple means to track people groups without complicated ACLs, when you simply want to know their grouping(s).

If I am not mistaken, the suggest to provide the users 0 or none would actually give them  a Super User admin role as it is 0.

The default should be 9999 (anonymous).

ACLs are one of the few places a 0 matters in MODX.

**Comment by OptimusCrime** [comment] 2015-08-12 11:58
Does that mean that this in fact not a bug?

**Comment by wshawn** [comment] 2015-08-12 15:00
I do not believe so. A simple quest to Jason will sort it.

Should ACL's have roles?

**Comment by OptimusCrime** [comment] 2015-08-12 16:10
@opengeek

**Comment by opengeek** [comment] 2015-08-12 16:17
The default should be Member always. @OptimusCrime is correct—no group membership without a role.

**Comment by OptimusCrime** [comment] 2015-08-12 20:26
Thanks @opengeek :)

Does that solve this issue?

**Comment by BobRay** [comment] 2015-08-12 20:26
You can easily add a member to a group in the Manager without specifying a role for the user. The user is automatically assigned the role of member. I think something like this would make sense:

Add around line 658:

if (empty($roleId)' || $roleId === '0') {
$member->set('role',1);
}

**Comment by BobRay** [comment] 2015-08-12 20:28
Never mind. Re-reading the report, I see that's already happening, so no bug.

**Comment by BobRay** [comment] 2015-08-12 20:29
Side note: When you do this in the Manager, no role appears in the grid, so it gives the impression that you've created a user with no role.

**Comment by wshawn** [comment] 2015-08-12 23:19
I  created over a dozen groups today and all of them show 9999 and a 2.3.5 p.l. site. I would whole-hardheartedly agree the ACL area needs work. 

I've been doing it so long it no longer bothers me as much, as I auto pilot through it.

Yes,  @OptimusCrime though I should get at least some of the credit... Just saying ;)

**Comment by OptimusCrime** [comment] 2015-08-13 07:17
Haha, that is only fair.

I'll close it then. Thanks all :)

@modxbot close

**Closed by OptimusCrime** 2015-08-13 07:17 UTC

**Comment by gadgetto** [comment] 2016-02-11 13:21
Sorry to pick an old discussion, but It is still possible (MODX 2.4.2) to assign a user to a MODX group in manager without adding a role. The `modx_member_groups` table shows this user with a role of 0. As I reread this thread this shouldn't be possible. @opengeek @OptimusCrime

**Comment by wshawn** [comment] 2016-02-11 15:13
Users will always have a role: anonymous by default - per the discussion above. Only an appearance of no role is there.

**Comment by gadgetto** [comment] 2016-02-11 16:18
@wshawn sorry I think I don't fully understand (its probably my english).
Reading the discussion above, it seems assigning a user to a group should not lead to a role 0?
But this is exactly what happens when I create a user via manager interface without choosing a specific role.

**Comment by opengeek** [comment] 2016-02-11 16:53
You should not be able to add a user to a group without a role record. The authority level of 0, defined by a role such as Super User, is not the same thing as not having a role defined at all for the membership. Without being at least a Member role in the User Group, you really are not part of the Group.

**Comment by gadgetto** [comment] 2016-02-11 20:25
![jpw41x32e1](https://cloud.githubusercontent.com/assets/876737/12989435/e90623f2-d105-11e5-8d83-36233900ea7f.gif)

**Comment by opengeek** [comment] 2016-02-11 20:29
I am aware the UI currently allows this to happen — I'm just telling you it should **not** be allowing it. It **is** a bug that a UserGroupMembership record gets created without a valid Role.

**Comment by gadgetto** [comment] 2016-02-11 20:32
OK, Jason thanks for making things clear. Is there already a GitHub issue to this problem?

**Comment by wshawn** [comment] 2016-02-11 20:34
@gadgetto  This would be that issue. It is a known issue.

**Comment by gadgetto** [comment] 2016-02-11 20:35
Didn't find one - so I'll go and file one.

**Comment by pixelchutes** [comment] 2016-02-11 23:47
should we just reopen this one?
