### ISSUE TITLE
MODX-Browser: Sessionpath

### ISSUE THREAD

**Issue by Morosko** [modxcms/revolution#12586] opened 2015-08-24 11:45 UTC
If you select an image in the mod-x browser from a sub-directory, it would be great to safe the last path, which was opened (at least for one session).

If you have an article with 50 images and always have to click "asserts->sub-folder->article-folder" (for example) it's really annoying. 

**New workflow:** Open mod-x browser the first time, go in sub-directory, select image, open mod-x browser another time (in another input field), have the last path opened.

**Comment by zaigham** [comment] 2015-08-24 12:00
:+1:

**Comment by jpdevries** [comment] 2015-08-24 12:05
FWIW the Eureka media browser we've been working on at modmore (as seen in Redactor 2.0) works like this. It will fully paint the UI of the last directory before even making a single XHR request. 

It also uses hyper-threading and localStorage for extreme snappiness, is accessible to screen readers, and is mobile friendly. 

I'd like to work on abstracting it to a media browser that can be used outside of Redactor. Mostly just need php connectors for it and a few features found in the native browser that it still lacks. 



—

**Comment by ckburnett** [comment] 2015-12-30 17:16
:+1:

**Comment by Mark-H** [comment] 2017-01-30 23:40
Dupe of #5320

**Closed by Mark-H** 2017-01-30 23:40 UTC
