### ISSUE TITLE
Invalid SQL request when displaying system parameters

### ISSUE THREAD

**Issue by bgillet** [modxcms/revolution#13856] opened 2018-04-10 09:00 UTC
### Summary
When you select [System parameters] from [Settings] menu to access list of parameters, if you check the MODx error log, there is an error message about a failed SQL request.

### Step to reproduce
See summary

### Observed behavior
[2018-04-10 10:55:11] (ERROR @ D:\WWW\modx\core\xpdo\om\xpdoobject.class.php : 240) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 8120
    [2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]La colonne 'modx_system_eventnames.service' n'est pas valide dans la liste de sélection parce qu'elle n'est pas contenue dans une fonction d'agrégation ou dans la clause GROUP BY.
)

### Expected behavior
The SQL request should work

### Environment
MODX 2.6.1-pl, IIS 8.1, MSSQL 2017

**Comment by JoshuaLuckers** [comment] 2019-03-09 18:27
Thanks for taking time to report this issue and help us make MODX better.

I'm unable to reproduce this issue. Is it still present in the most recent release of MODX?

**Comment by alroniks** [comment] 2021-04-03 22:58
No feedback since the last contact, also dropping MSSQL got full support, so closing.

**Closed as completed by alroniks** 2021-04-03 22:58 UTC
