### ISSUE TITLE
No scroll in long dropdown menu in Firefox

### ISSUE THREAD

**Issue by shamarin** [modxcms/revolution#13922] opened 2018-06-06 07:56 UTC
Summary
If you have many addons installed in Applcation menu in MODX then if to press on it in Firefox browser there will be no scroll, so you can't get to last items in dropdown menu. See screenshot for more details. In other browsers it's ok, there will scroll.
![qip shot - screen 425](https://user-images.githubusercontent.com/24771090/41024534-2de1caaa-6978-11e8-915b-a2020abf6f00.jpg)

Environment
MODX version 2.6.3, browser Mozilla Firefox 61b11 or the latest one stable (60 version).

**Comment by JoshuaLuckers** [comment] 2018-06-10 06:52
Duplicate of #11939

**Closed as completed** 2018-06-10 10:42 UTC
