### ISSUE TITLE
modPHPMailer using deprecated __autoload() function - Change to spl_autoload_register() for PHP 7.3

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14594] opened 2019-05-31 00:43 UTC
### Summary
When using modPHPMailer under PHP 7.3 a deprecation warning is given:
```
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /home/vagrant/code/project/public_html/core/model/modx/mail/phpmailer/PHPMailerAutoload.php on line 45
```
### Step to reproduce
Use the MODX mailer functionality in a PHP 7.3 environment.

### Observed behavior
It still works for now. It's just a deprecation warning.

### Expected behavior
We should future proof the mailer and use spl_autoload_register() instead of the deprecated __autoload() function.

### Environment
MODX version 2.7.1
PHP 7.3.x

**Comment by sdrenth** [comment] 2020-02-08 10:02
@JoshuaLuckers This is no longer an issue in MODX 3.0, PHPMailer is now loaded as a composer package which no longer uses `__autoload()`. So I think this issue can be closed.

**Comment by Jako** [comment] 2020-02-08 10:08
MODX 2.x will have to support PHP 7.4, so this has to be fixed for the 2.x branch.

**Comment by sdrenth** [comment] 2020-02-08 10:16
@Jako Thank you for your comment, then see my comment as a FYI for the 3.x branch :)

**Comment by JoshuaLuckers** [comment] 2020-02-16 12:56
> MODX 2.x will have to support PHP 7.4, so this has to be fixed for the 2.x branch.

I don't think we can't fix this in 2.x without breaking BC.

**Comment by kevinamezaga** [comment] 2020-09-29 20:02
@JoshuaLuckers does this mean we just have to live without using modMailer until 3.0 comes out (whenever that even happens)? That's kind of ridiculous.

**Comment by Jako** [comment] 2020-09-29 20:53
You could fix this like I have accidentally committed here: https://github.com/modxcms/revolution/commit/649cccb76efe16782ea54b4ce5e22ecc38e7cc06. Revo 2.7 is PHP 5.3.3+ But it will modify a file, that belongs to PHPMailer 5.2.x.

But why the heck does the PHP_VERSION check goes wrong on your system. I only faced this inside of Composer.

**Comment by kevinamezaga** [comment] 2020-10-02 15:51
No, still giving the error. Not sure when the issue is.

**Comment by Jako** [comment] 2020-10-02 18:50
If you edit that file (core/model/modx/mail/phpmailer/PHPMailerAutoload.php), the error does not get away?

**Closed as completed** 2021-03-09 20:36 UTC
Labels: bug, area-core
