### ISSUE TITLE
Plugin properties not saving since v2.4.0

### ISSUE THREAD

**Issue by Oliver-Meyer** [modxcms/revolution#12695] opened 2015-10-03 09:39 UTC
When I edit a plugin property and click on the save-button I get the message that the saving was successful, but the little red arrow next to the value stays and the property won't be changed.

Same goes for new properties. You can add a new property and save it - again you'll get the message that the saving was successful, but the new property is not added. If you leave the page and then open it again, the property is missing.

**Comment by sottwell** [comment] 2015-10-03 10:19
I've been editing and creating plugin properties in 2.4.0 and 2.4.1 with no problems. Is this an existing plugin? Can you save changes to the plugin without doing anything to its properties?

**Comment by Oliver-Meyer** [comment] 2015-10-03 20:37
I just re-checked it on two fresh installations (both v2.4.1, using PHP 5.5.29). I can edit & save the plugins themselves without problems, but I'm not able to edit / add & save properties - saving doesn't work. No errors in the server logs.

**Comment by whitebyte** [comment] 2015-10-03 22:02
May this be related to #12580?

**Comment by Oliver-Meyer** [comment] 2015-10-03 23:08
I don't think so, because I can not even save a property. And I have absolutely no problems with chunks or snippets.

**Comment by sottwell** [comment] 2015-10-04 00:52
Just installed 2.4.1 fresh on localhost. Can save properties for newly created or installed plugins. Can also do so on several MODX Cloud installations. Both are PHP 5.6-something.

**Comment by sottwell** [comment] 2015-10-04 00:52
Check your permissions, make sure all your Administrator permissions are checked in the policy.

**Comment by whitebyte** [comment] 2015-10-04 11:50
@Oliver-Meyer you should alse check you mod_security settings. This is  a known source of such issues.

**Comment by Oliver-Meyer** [comment] 2015-10-06 20:36
I just logged in into a MODX-Installation with v2.3.5 - I could add / edit plugin properties without any problem. Then I updated this installation to v2.4.1 - and now I'm not longer able to add or edit plugin properties.

So now I have two fresh installations with v2.4.1, one installation (on a different server) that was installed with v2.4.0 and then upgraded to v2.4.1 and one installation that was installed with v2.3.2 and then upgraded to v2.3.3 -> v2.3.5 -> v2.4.1.

I'm not able to add or edit plugin properties on any of these installations now (saving doesn't work / no server response). These installations are on different servers with different php versions and without mod_security. I tried with Google Chrome and Firefox. I checked all permissions - OK.

This must be a bug - caused by whatever.

Please let me know if someone wants access to an installation on my server to test/verify.

**Comment by whitebyte** [comment] 2015-10-06 21:11
I confirm this for 2.4.0 and 2.4.1. It seems to be fixed in 2.4.2, so I still do believe this was caused by #12580. If we examine firebug->network while trying to save plugin properties in 2.4.0 and 2.4.1 we will see that responses for 2 last requests will contain error messages regarding missing property set (although response code is 200). @Oliver-Meyer please try MODX 2.4.2.

**Comment by Oliver-Meyer** [comment] 2015-10-06 21:55
I can confirm that it is fixed in v2.4.2 :+1:

**Comment by whitebyte** [comment] 2015-10-06 21:56
Nice! This issue should be closed then.

**Closed** 2015-10-07 06:53 UTC
