### ISSUE TITLE
[CSS] missing top-padding when using columns layout in complex input-forms

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11987] opened 2014-09-15 18:37 UTC
Revo 2.3+: Using columns layout in complex forms leads to missing top-padding for labels of the first elements in columns. See screenshot:

![screenshot 2014-09-15 20 04 11](https://cloud.githubusercontent.com/assets/876737/4276561/517601b8-3d06-11e4-91e6-323849dbf469.png)

The intention is that the first line in a column should have no top padding. The problem is when using a column layout panel between other form elements the top padding is missing.

I know I could set my own helper classes to add top-padding to these column layout panels but this will be only a workaround. Or do you think this would be the right way?

Here is the "problem":

```
.x-form-label-top .x-form-item:first-of-type label.x-form-item-label {
    padding: 0 0 4px;
}
```

**Comment by whitebyte** [comment] 2015-01-04 01:51
Another issue caused by exactly this style - #12221

**Comment by Ibochkarev** [comment] 2019-01-11 20:18
@Alroniks @JoshuaLuckers The problem does not reproduce. Checked in different components on versions 2.6.5 and 2.7.0.

All work fine.

Please close issue. Thanks

**Comment by alroniks** [comment] 2019-01-12 19:47
I also can not reproduce. Because this bug targeted for 2.3, it seems since that time a lot of changes were done for theming so it was fixed. Feel free to reopen if the issue will appear again.

**Closed by alroniks** 2019-01-12 19:47 UTC
Labels: area-ux/ui, enhancement, state/accepting-pull-request
