### ISSUE TITLE
Language strings missing warning

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12291] opened 2015-01-22 16:53 UTC
```
(DEBUG @ /index.php) Language string not found: "basePath"
(DEBUG @ /index.php) Language string not found: "basePathRelative"
(DEBUG @ /index.php) Language string not found: "baseUrl"
(DEBUG @ /index.php) Language string not found: "baseUrlRelative"
(DEBUG @ /index.php) Language string not found: "allowedFileTypes"
(DEBUG @ /index.php) Language string not found: "imageExtensions"
(DEBUG @ /index.php) Language string not found: "thumbnailType"
(DEBUG @ /index.php) Language string not found: "PNG"
(DEBUG @ /index.php) Language string not found: "JPG"
(DEBUG @ /index.php) Language string not found: "GIF"
(DEBUG @ /index.php) Language string not found: "thumbnailQuality"
(DEBUG @ /index.php) Language string not found: "skipFiles"
```

Should be caused by core/model/modx/sources/modfilemediasource.class.php
modFileMediaSource::getDefaultProperties

There is also another warning:
```
(DEBUG @ /connectors/index.php) An error occurred while trying to cache lexicon/de/core/sources (lexicon/language/namespace/topic)
```

but I did not get located this one.

**Comment by OptimusCrime** [comment] 2015-06-18 14:05
Might be relevant for #12466.

This is either by design and won't be fixed, or this pull request will remove this issue.

**Comment by OptimusCrime** [comment] 2016-04-27 00:00
Pull request merged, not sure why this was not closed.

@modxbot close

**Closed by OptimusCrime** 2016-04-27 00:00 UTC
