### ISSUE TITLE
Duplicate TV has caption "undefined"

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#13302] opened 2017-02-20 09:10 UTC
### Summary
When duplicating a TV (right-click inside the tree) the new caption is always "Duplicate of undefined" (red box), even if the source has a caption (green box):
![modx_issue_duplicate-tv](https://cloud.githubusercontent.com/assets/458619/23118368/28ed7086-f754-11e6-88da-db12eed59dd8.png)
(When using the "Duplicate"-button while editing a TV, the new caption field is empty and the is no "undefined" – but still, there is no duplicate of the caption.)

### Step to reproduce
Right-click on a TV an choose "Duplicate TV".

### Observed behavior
see: summary

### Expected behavior
The new caption should show "Duplicate of <caption_old>" with <caption_old> being the caption of the source TV or it should be empty, when there is nothing to duplicate (caption of source is empty)

### Environment
On any system, as far as I can say, running 2.5.5. I had this issues also on lower versions but can't recall if it was 2.5.4, 2.5.2 or even lower.

**Comment by sottwell** [comment] 2017-02-20 09:18
I can't replicate the issue
![screen shot 2017-02-20 at 11 17 20](https://cloud.githubusercontent.com/assets/1073780/23118842/56ebea3a-f75e-11e6-8d20-a67c1075c92c.png)
![screen shot 2017-02-20 at 11 17 40](https://cloud.githubusercontent.com/assets/1073780/23118846/5b843e30-f75e-11e6-8644-d1a2bb11f68f.png)

**Comment by mindeffects** [comment] 2017-02-20 10:03
That is strange, @sottwell!
I just did a quick check on several 2.5.5 installations. All of them (4) were build from scratch without a boilerplate or so. They all run on different machines and run at different hosters.
But all of them had the same "undefined" in the caption field.
Anybody else in here who an confirm either behavior?

**Comment by sottwell** [comment] 2017-02-20 10:04
What exactly is the full caption of the original TV?

**Comment by Jako** [comment] 2017-02-20 10:09
@mindeffects Please look in the DB entry for this. Is the caption null for some reason?

**Comment by sottwell** [comment] 2017-02-20 10:11
Behavior is different if I use the Duplicate button with the original TV open for editing, or if I use the Duplicate TV context menu option. In the latter case, it does pre-fill the caption field
![screen shot 2017-02-20 at 12 10 29](https://cloud.githubusercontent.com/assets/1073780/23120599/a8ea02c0-f765-11e6-8bd4-fb26006ab222.png)

**Comment by sottwell** [comment] 2017-02-20 10:13
Since the full caption of the original is covered by the form, I was thinking that perhaps there was something unexpected in the full caption text.

**Comment by sottwell** [comment] 2017-02-20 10:18
If the caption is empty, the duplicate will have "Duplicate of " in its caption field. 

Also there is a difference in behavior after saving, using the button redirects to the new copy, using the context menu does not.

**Comment by himurovich** [comment] 2017-02-20 10:45
@mindeffects I can confirm that issue for 2.5.4 http://take.ms/3UEa1 This is happen when TV duplicated via right click on Element tree TV ONLY!

**Comment by mindeffects** [comment] 2017-02-20 11:51
The content is a string, @Jako, with nothing special in it. Tested several "typed in " words.

When I use the "Duplicate"-button when editing a TV, the caption is allways empty, even if the source TV had a caption.

When I use the right-click (forgot to put this in the isse description), I get the "Duplicate of undefined" or a simple "undefined" in the caption field.

**Comment by Alroniks** [comment] 2017-02-20 12:51
@mindeffects Did you use some additional extras like AjaxManager or others? Tried on latest 2.5.5 and can not reproduce.

**Comment by himurovich** [comment] 2017-02-20 12:56
@Alroniks @mindeffects Retested right now with 2.5.5. MODX cloud environment (absolutely pure MODX with single test TV), issue is actual: http://take.ms/P6wX2

**Comment by Alroniks** [comment] 2017-02-21 07:51
@himurovich Caption field not visible on screenshot but looks that it works, no undefined.

**Comment by pixelive** [comment] 2017-03-03 08:13
I'm going to try and fix this today.

**Comment by pixelive** [comment] 2017-03-03 09:45
I could not reproduce the "undefined" message.

But once you clicked on the duplicate button within a TV page itself (not in tree) the caption was not prefilled. With this PR it is: https://github.com/modxcms/revolution/pull/13317

**Comment by Mark-H** [comment] 2017-03-03 12:56
#13317 fixes the issue that the caption isn't pre-filled when duplicating from the edit tv screen, however I'm still seeing undefined when duplicating via the context menu.

**Comment by Flowan** [comment] 2017-07-07 10:18
@Mark-H I tried to reproduce the wrong caption when duplicating from the context menu, but it works just fine. Can you confirm you still have this issue? Thanks

**Comment by gpsietzema** [comment] 2017-07-07 10:33
#modxbughunt #1point to @Flowan

**Comment by wuuti** [comment] 2018-02-11 23:09
@mindeffects @Mark-H @sottwell I can't reproduce that with current 2.x (2.6.1). Was that fixed by #13317? Can you please try to reproduce that with the current version? Have the feeling this issue might no longer be valid. If the issue still occurs, please also tell the browser used to reproduce.

**Comment by sottwell** [comment] 2018-02-12 03:35
Behaves as expected here.

**Comment by sottwell** [comment] 2018-02-12 03:36
![screen shot 2018-02-12 at 5 33 10](https://user-images.githubusercontent.com/1073780/36082949-aee91b74-0fb6-11e8-9bd2-4a55932c5c4d.png)

**Comment by digitalpenguin** [comment] 2018-02-12 08:46
![screenshot-2018-2-12 template variable closeddatefrom](https://user-images.githubusercontent.com/5160368/36088901-2099fc18-1014-11e8-9536-775452d4fcfc.png)

I'm still experiencing the bug.
I created a TV. Saved it. Then with the TV editing form still open I used the context menu in the tree to select duplicate. The result is in the image.

**Comment by wuuti** [comment] 2018-02-12 09:05
Is there anything logged in the javascript console?

**Comment by digitalpenguin** [comment] 2018-02-12 09:07
Nope, nothing.

**Comment by JoshuaLuckers** [comment] 2018-07-10 20:25
~I’m able to reproduce this issue~. 
I'm not able to reproduce this issue. I will try to reproduce and fix this issue somewhere in the upcoming days.

**Comment by alroniks** [comment] 2018-07-19 18:50
Tries on 2.7.0-dev and all works fine. I close the issue as it seems fixed for most people. The issue can be still there if a cache was not updated or something else.
I suggest reopen or open a new one with details in case it will happen again.

**Closed by alroniks** 2018-07-19 18:50 UTC
Labels: area-ux/ui, bug

**Comment by JoshuaLuckers** [comment] 2018-07-31 11:26
I just ran into this issue on a 2.6.5 installation. 
The issue only occurs when you try to duplicate a Template Variable that is assigned to a category. 

@modxbot open

**Comment by ant-tar** [comment] 2018-07-31 11:30
Yes,the same thing on 2.6.5

**Comment by ant-tar** [comment] 2018-07-31 11:43
For those with no category caption  will be partly empty when copying [http://take.ms/K2l84f](http://take.ms/K2l84f)

**Comment by alroniks** [comment] 2018-08-10 10:23
Closing as PR is merged.
