### ISSUE TITLE
MODX 3 alpha1 - Static plugins/snippet are not allowed

### ISSUE THREAD

**Issue by theboxer** [modxcms/revolution#14922] opened 2019-12-20 17:02 UTC
### Summary
You can't create a static snippet or plugin, because `php` extension is not allowed.

### Step to reproduce
Try and create a static snippet/element and link a `php` file.

### Observed behavior
Error will appear.

### Expected behavior
Error shouldn't appear :P

### Environment
MODX Revolution 3.0.0-alpha1

**Comment by JoshuaLuckers** [comment] 2019-12-20 17:27
This is a duplicate of https://github.com/modxcms/revolution/issues/13898

**Closed as completed** 2019-12-20 17:27 UTC
Labels: bug, area-core, urgent
