### ISSUE TITLE
Make scss (css) files in one format

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14751] opened 2019-09-22 22:59 UTC
### Summary
Now the properties of scss (css) files do not have a standard, and because of this, styles can be duplicated, and you can easily make mistakes when working with them.

In the future, if styles have one writing standard - they will be easier to edit.

**I think it would be right to somehow "comb" styles after merging PR, which affected styles.**

There are libraries of this kind, for example, https://github.com/csscomb

**Comment by Mark-H** [comment] 2019-09-22 23:05
Perhaps we should discuss code styles on the forum. When there's consensus (maybe there already is), existing code should be converted and automatically enforced as part of the checks that run for each PR and commit. 

That's not just about SCSS, but also JS and PHP should get that.

**Comment by Jako** [comment] 2019-09-23 06:28
Somehow a duplicate of #14311

**Closed as completed** 2019-09-23 09:28 UTC
