### ISSUE TITLE
File Tree not showing without Resource Tree selected in AC

### ISSUE THREAD

**Issue by Dmitra** [modxcms/revolution#10136] opened 2013-08-27 22:50 UTC
dmitra created Redmine issue ID 10136

Hi there.

Bob Ray suggested I log this as a bug:

In setting up another manager account for my client where the user can only see the filesystem, to upload and download files from a specific media source. The only issue is that in order to see the filesystem the following access control must be selected or else the file list will not display. 

resource_tree - To view the resource tree in the left nav

Attached are two screenshots, one with resource_tree not selected - the file list is cropped where you cannot see files.
Second - where resource_tree is selected in access controls, so you can see both "resources" and the filesystem.

Derrick

**Comment by rtripault** [comment] 2017-03-03 09:14
I was not able to reproduce locally, so closing (about time eh ? :D).

Please feel free to comment/reopen if needed

#modxbughunt

**Closed by rtripault** 2017-03-03 09:14 UTC
Labels: bug
