### ISSUE TITLE
modx 3.x  Setup Fatal error: Uncaught Error: Class 'xPDO' not found 

### ISSUE THREAD

**Issue by alexeyp0708** [modxcms/revolution#14241] opened 2019-01-08 11:50 UTC
### Summary
php 7.2
Quick summary what's this issue about.
```
Fatal error: Uncaught Error: Class 'xPDO' not found in Z:\site\modx30.test\www\setup\includes\drivers\modinstalldriver_mysql.class.php:155 Stack trace: #0 Z:\site\modx30.test\www\setup\processors\database\connection.php(80): modInstallDriver_mysql->verifyServerVersion() #1 Z:\site\modx30.test\www\setup\includes\request\modinstallconnectorrequest.class.php(82): include('Z:\\site\\modx30....') #2 Z:\site\modx30.test\www\setup\processors\connector.php(40): modInstallConnectorRequest->handle() #3 {main} thrown in Z:\site\modx30.test\www\setup\includes\drivers\modinstalldriver_mysql.class.php on line 155
```
### Step to reproduce
How to reproduce the issue, including custom code if needed.
```
$ composer create-project modx/revolution www 3.x-dev
```
next step:  `http://modx30.test/setup/`
next step :  test confirm connect DB server
result : no action
Established where the error is through  chrome console + network

**Comment by Mark-H** [comment] 2019-01-08 12:09
Works fine here. Can you please provide the full output of the `composer create-project`?

**Comment by alexeyp0708** [comment] 2019-01-08 12:13
```  
Z:\site\modx30.test\www>composer create-project modx/revolution www 3.x-dev
Installing modx/revolution (3.x-dev 1f49bc8a048bed4cdd5a40fe875103f95d6d4303)
  - Installing modx/revolution (3.x-dev 1f49bc8): Cloning 1f49bc8a04 from cache
Created project in www
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 59 installs, 0 updates, 0 removals
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.2): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/console (v3.4.21): Downloading (100%)
  - Installing xpdo/xpdo (3.x-dev 45e4813): Cloning 45e481377e from cache
  - Installing mtdowling/jmespath.php (2.4.0): Downloading (100%)
  - Installing ralouphie/getallheaders (2.0.5): Downloading (100%)
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing aws/aws-sdk-php (3.82.6): Downloading (100%)
  - Installing league/flysystem (1.0.49): Downloading (100%)
  - Installing league/flysystem-aws-s3-v3 (1.0.21): Downloading (100%)
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing league/flysystem-cached-adapter (1.0.9): Downloading (100%)
  - Installing phpmailer/phpmailer (v6.0.6): Downloading (100%)
  - Installing smarty/smarty (v3.1.33): Downloading (100%)
  - Installing james-heinrich/phpthumb (v1.7.14): Downloading (100%)
  - Installing erusev/parsedown (1.7.1): Loading from cache
  - Installing symfony/css-selector (v4.2.2): Downloading (100%)
  - Installing pelago/emogrifier (v2.1.1): Downloading (100%)
  - Installing simplepie/simplepie (1.5.2): Downloading (100%)
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.8.1): Loading from cache
  - Installing phpunit/phpunit (6.5.13): Downloading (100%)
  - Installing symfony/yaml (v4.2.2): Downloading (100%)
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Installing symfony/stopwatch (v4.2.2): Downloading (100%)
  - Installing symfony/filesystem (v4.2.2): Downloading (100%)
  - Installing symfony/config (v4.2.2): Downloading (100%)
  - Installing php-coveralls/php-coveralls (v2.1.0): Downloading (100%)
symfony/console suggests installing psr/log-implementation (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
symfony/console suggests installing symfony/process
xpdo/xpdo suggests installing ext-redis (Allows caching using Redis)
aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS noti
fications)
league/flysystem suggests installing ext-ftp (Allows you to use FTP server storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with A
WS SDK v2)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob st
orage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use Eventa
bleFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud F
iles)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage vi
a phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapt
er)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storag
e for PHP 5 applications)
league/flysystem-cached-adapter suggests installing ext-phpredis (Pure C implemented extension for P
HP)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authenticati
on)
phpmailer/phpmailer suggests installing hayageek/oauth2-yahoo (Needed for Yahoo XOAUTH2 authenticati
on)
phpmailer/phpmailer suggests installing stevenmaguire/oauth2-microsoft (Needed for Microsoft XOAUTH2
 authentication)
james-heinrich/phpthumb suggests installing ext-imagick (PHP ImageMagick)
simplepie/simplepie suggests installing mf2/mf2 (Microformat module that allows for parsing HTML for
 microformats)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
symfony/contracts suggests installing symfony/cache-contracts-implementation
symfony/contracts suggests installing symfony/service-contracts-implementation
symfony/contracts suggests installing symfony/translation-contracts-implementation
php-coveralls/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
Writing lock file
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
> @php -r "file_exists('_build/build.properties.php') || copy('_build/build.properties.sample.php',
'_build/build.properties.php');"
> @php -r "file_exists('_build/build.config.php') || copy('_build/build.config.sample.php', '_build/
build.config.php');"
> @php _build/transport.core.php
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Beginning build script processes...
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Removed pre-existing core/ and core.transpo
rt.zip.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Core transport package created.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Core Namespace packaged.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Default workspace packaged.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Packaged modx.com transport provider.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Packaged in 2 modMenus.
[2019-01-08 11:20:15] (INFO @ _build/transport.core.php) Packaged all default modContentTypes.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged all default modClassMap objects.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 190 default events.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 235 default system settings.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 2 default context settings.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 1 default user groups.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 1 default dashboards.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 1 default media sources.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 7 default dashboard widgets.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 2 default roles Member and Supe
rUser.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 6 default Access Policy Templat
e Groups.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 7 default Access Policy Templat
es.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in 12 default Access Policies.
[2019-01-08 11:20:16] (INFO @ _build/transport.core.php) Packaged in web context.
[2019-01-08 11:20:21] (INFO @ _build/transport.core.php) Packaged in mgr context.
[2019-01-08 11:20:21] (INFO @ _build/transport.core.php) Packaged in connectors.
[2019-01-08 11:20:21] (INFO @ _build/transport.core.php) Beginning to zip up transport package...
[2019-01-08 11:20:24] (INFO @ _build/transport.core.php) Transport zip created. Build script finishe
d.
```

**Comment by Mark-H** [comment] 2019-01-08 12:20
Hmm, that seems to be installing all dependencies and building the core package properly. Not sure why it wouldn't work on your end. Your output is pretty much the same as mine, except for the error about not being able of finding xPDO.

**Comment by alexeyp0708** [comment] 2019-01-08 12:29
@Mark-H  I understand that you have no problems with the installation *?

**Comment by Mark-H** [comment] 2019-01-08 12:35
Correct, I have no problems with the setup after the `composer create-project` command (on PHP 7.2.8, MAMP). It installs properly and I can login to the manager too.

**Comment by alexeyp0708** [comment] 2019-01-08 13:47
@Mark-H 
the question is: Why does it work for you?
maybe you are loading another thread.

The reasons why y doesn't work for me:
\setup\includes\drivers\modinstalldriver_mysql.class.php  

before  
```php 
class modInstallDriver_mysql extends modInstallDriver {
//.....
}
```  
after
```php  
 use xPDO\xPDO;
class modInstallDriver_mysql extends modInstallDriver {
//.....
}
```

Mark as a bug and fix it.

**Comment by JoshuaLuckers** [comment] 2019-01-08 13:56
`modInstallDriver` already imports `xPDO\xPDO`

**Comment by Mark-H** [comment] 2019-01-08 13:56
[xPDO is aliased to xPDO\xPDO, so the use statement is not necessary](https://github.com/modxcms/revolution/blob/3.x/core/xpdo/xPDO.php). 

I compared your command output with mine; we're both loading the exact same 3.x commit.

**Comment by alexeyp0708** [comment] 2019-01-08 14:54
@Mark-H
I will not argue.
But it is possible that `Composer` autoloader first looks for the class `xPDO`, and then the file `/core/xpdo/xPDO.php`  is initialized.

Need to check.
Perhaps this order sets Composer
  `composer.json`
```
"autoload": {
       "classmap": [
         "core / xpdo /"
       ]
     }
```
Composer version 1.8.0 2018-12-03 10:31:16.
Composer settings are standard as installed.
I repeated the installation procedure.
Removed in detail and reinstalled through the command
```
$ composer create-project modx / revolution www 3.x-dev
```
Ошибка повторяется. 

In the file `core \ vendor \ composer \ autoload_classmap.php`
file `/core/xpdo/xPDO.php` was not found.
But the file /core/xpdo/xPDO.php does not contain a class definition.

composer.json
```json
{
    "name": "modx/revolution",
    "description": "MODX Revolution is a Content Management System",
    "type": "project",
    "keywords": [
        "content",
        "CMS",
        "routing",
        "templating"
    ],
    "homepage": "https://modx.com/",
    "license": "GPL-2.0+",
    "authors": [
        {
            "name": "Jason Coward",
            "email": "jason@opengeek.com",
            "homepage": "http://jasoncoward.com/",
            "role": "Developer"
        },
        {
            "name": "Shaun McCormick",
            "email": "splittingred@gmail.com",
            "homepage": "http://splittingred.com/",
            "role": "Developer"
        },
        {
            "name": "Jan Peca",
            "email": "pecajan@gmail.com",
            "homepage": "http://www.bxr.cz/",
            "role": "Developer"
        }
    ],
    "support": {
        "docs": "https://rtfm.modx.com/revolution/2.x/",
        "email": "help@modx.com",
        "forum": "https://forums.modx.com/",
        "irc": "irc://irc.freenode.org/modx",
        "issues": "https://github.com/modxcms/revolution/issues/",
        "source": "https://github.com/modxcms/revolution/"
    },
    "config": {
        "vendor-dir": "core/vendor"
    },
    "require": {
        "php": ">=5.6",
        "xpdo/xpdo": "^3.0@dev",
        "league/flysystem": "^1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "league/flysystem-cached-adapter": "^1.0",
        "phpmailer/phpmailer": "^6.0",
        "smarty/smarty": "^3.1",
        "james-heinrich/phpthumb": "^1.7",
        "erusev/parsedown": "^1.7",
        "pelago/emogrifier": "^2.0",
        "simplepie/simplepie": "^1.5"
    },
    "autoload": {
      "classmap": [
        "core/xpdo/"
      ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "@php -r \"file_exists('_build/build.properties.php') || copy('_build/build.properties.sample.php', '_build/build.properties.php');\"",
            "@php -r \"file_exists('_build/build.config.php') || copy('_build/build.config.sample.php', '_build/build.config.php');\"",
            "@php _build/transport.core.php"
        ],
        "phpunit": "vendor/bin/phpunit -c _build/test/phpunit.xml --coverage-text --colors",
        "coverage": "vendor/bin/phpunit -c _build/test/phpunit.xml --colors --coverage-html ./.coverage"
    },
    "scripts-descriptions": {
        "phpunit": "Run PHPUnit test",
        "coverage": "Generating the code coverage report in HTML format"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require-dev": {
        "phpunit/phpunit": "~5.7|~6.5",
        "php-coveralls/php-coveralls": "~2.1"
    }
}
```
Solve the problem. At this point I finished the discussion and even proposed a solution.
otherwise it may happen in the production version.

**Comment by JoshuaLuckers** [comment] 2019-01-08 15:05
Thanks for taking time to submit this issue @ALexeyP0708. Unfortunately we are not able to reproduce this issue therefore we can not test the proposed solution. 

@Mark-H did you test it on a Windows machine? That's the only difference I can see.

**Comment by alexeyp0708** [comment] 2019-01-08 15:21
@JoshuaLuckers
Detail
Windows 8.1 (Administrator) 
Apache 2.4  
PHP 7.1 and PHP 7.2 
Composer version 1.8.0 2018-12-03


In order to have an elegant code, I propose to make corrections
in the files of `setup \ includes \ drivers \ modinstalldriver_mysql.class.php` and  ` setup \ includes \ drivers \ modinstalldriver_sqlsrv.class.php`
write string `use xPDO \ xPDO;`
In the inherited modInstallDriver class, the file `setup \ includes \ drivers \ modinstalldriver.class.php` this line is already present.

**Comment by alroniks** [comment] 2019-01-08 17:31
No need to add the string `use xPDO/xPDO` to `modinstalldriver_sqlsrv.class.php` because of xPDO class never used there, but it should be added to `modinstalldriver_mysql.class.php` because there are two usages of xPDO (usage of class constants). It seems that class aliases and dynamical loading of files have conflicts in this case.

**Comment by JoshuaLuckers** [comment] 2019-01-08 17:32
Isn't that just a bandaid? I think it's better to find the actual problem that is reproducible.

**Comment by alroniks** [comment] 2019-01-08 17:33
Also, could you please say which database did you use? @ALexeyP0708 Mysql or Windows SQL Server?

**Comment by alroniks** [comment] 2019-01-08 17:39
@JoshuaLuckers Probably it is the issue. Usually, when we use namespaces we should write use statements for every class that used in the file. Even when they are loaded via autoloader. Here the same case except that we in the root namespace.

**Comment by Ibochkarev** [comment] 2019-01-08 19:43
Hello!

@JoshuaLuckers @Alroniks @Mark-H  Trying to reproduce the error:

```composer create-project modx/revolution www 3.x-dev
Installing modx/revolution (3.x-dev 1f49bc8a048bed4cdd5a40fe875103f95d6d4303)
  - Installing modx/revolution (3.x-dev 1f49bc8): Cloning 1f49bc8a04 from cache
Created project in www
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 59 installs, 0 updates, 0 removals
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.2): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/console (v3.4.21): Loading from cache
  - Installing xpdo/xpdo (3.x-dev 45e4813): Cloning 45e481377e from cache
  - Installing mtdowling/jmespath.php (2.4.0): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing aws/aws-sdk-php (3.82.6): Loading from cache
  - Installing league/flysystem (1.0.46): Loading from cache
  - Installing league/flysystem-aws-s3-v3 (1.0.21): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing league/flysystem-cached-adapter (1.0.9): Loading from cache
  - Installing phpmailer/phpmailer (v6.0.6): Loading from cache
  - Installing smarty/smarty (v3.1.33): Loading from cache
  - Installing james-heinrich/phpthumb (v1.7.14): Loading from cache
  - Installing erusev/parsedown (1.7.1): Loading from cache
  - Installing symfony/css-selector (v4.2.2): Loading from cache
  - Installing pelago/emogrifier (v2.1.1): Loading from cache
  - Installing simplepie/simplepie (1.5.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.8.1): Loading from cache
  - Installing phpunit/phpunit (6.5.13): Loading from cache
  - Installing symfony/yaml (v4.2.2): Loading from cache
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Installing symfony/stopwatch (v4.2.2): Loading from cache
  - Installing symfony/filesystem (v4.2.2): Loading from cache
  - Installing symfony/config (v4.2.2): Loading from cache
  - Installing php-coveralls/php-coveralls (v2.1.0): Loading from cache
symfony/console suggests installing psr/log-implementation (For using the consol                                                                                e logger)
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
symfony/console suggests installing symfony/process
xpdo/xpdo suggests installing ext-redis (Allows caching using Redis)
aws/aws-sdk-php suggests installing ext-curl (To send requests using cURL)
aws/aws-sdk-php suggests installing ext-sockets (To use client-side monitoring)
aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
league/flysystem suggests installing ext-fileinfo (Required for MimeType)
league/flysystem suggests installing ext-ftp (Allows you to use FTP server storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to useWebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem-cached-adapter suggests installing ext-phpredis (Pure C implemented extension for PHP)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
phpmailer/phpmailer suggests installing hayageek/oauth2-yahoo (Needed for Yahoo XOAUTH2 authentication)
phpmailer/phpmailer suggests installing stevenmaguire/oauth2-microsoft (Needed for Microsoft XOAUTH2 authentication)
james-heinrich/phpthumb suggests installing ext-gd (PHP GD library)
james-heinrich/phpthumb suggests installing ext-imagick (PHP ImageMagick)
simplepie/simplepie suggests installing ext-curl
simplepie/simplepie suggests installing ext-intl
simplepie/simplepie suggests installing mf2/mf2 (Microformat module that allows for parsing HTML for microformats)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
symfony/contracts suggests installing symfony/cache-contracts-implementation
symfony/contracts suggests installing symfony/service-contracts-implementation
symfony/contracts suggests installing symfony/translation-contracts-implementation
php-coveralls/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
Writing lock file
Generating autoload files
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? y
> @php -r "file_exists('_build/build.properties.php') || copy('_build/build.properties.sample.php', '_build/build.properties.php');"
> @php -r "file_exists('_build/build.config.php') || copy('_build/build.config.sample.php', '_build/build.config.php');"
> @php _build/transport.core.php
[2019-01-08 19:27:02] (INFO @ _build/transport.core.php) Beginning build script processes...
[2019-01-08 19:27:02] (INFO @ _build/transport.core.php) Removed pre-existing core/ and core.transport.zip.
[2019-01-08 19:27:03] (INFO @ _build/transport.core.php) Core transport package created.
[2019-01-08 19:27:03] (INFO @ _build/transport.core.php) Core Namespace packaged.
[2019-01-08 19:27:03] (INFO @ _build/transport.core.php) Default workspace packaged.
[2019-01-08 19:27:03] (INFO @ _build/transport.core.php) Packaged modx.com transport provider.
[2019-01-08 19:27:03] (INFO @ _build/transport.core.php) Packaged in 2 modMenus.
[2019-01-08 19:27:04] (INFO @ _build/transport.core.php) Packaged all default modContentTypes.
[2019-01-08 19:27:04] (INFO @ _build/transport.core.php) Packaged all default modClassMap objects.
[2019-01-08 19:27:11] (INFO @ _build/transport.core.php) Packaged in 190 default events.
[2019-01-08 19:27:20] (INFO @ _build/transport.core.php) Packaged in 235 default system settings.
[2019-01-08 19:27:20] (INFO @ _build/transport.core.php) Packaged in 2 default context settings.
[2019-01-08 19:27:20] (INFO @ _build/transport.core.php) Packaged in 1 default user groups.
[2019-01-08 19:27:20] (INFO @ _build/transport.core.php) Packaged in 1 default dashboards.
[2019-01-08 19:27:21] (INFO @ _build/transport.core.php) Packaged in 1 default media sources.
[2019-01-08 19:27:21] (INFO @ _build/transport.core.php) Packaged in 7 default dashboard widgets.
[2019-01-08 19:27:22] (INFO @ _build/transport.core.php) Packaged in 2 default roles Member and SuperUser.
[2019-01-08 19:27:22] (INFO @ _build/transport.core.php) Packaged in 6 default Access Policy Template Groups.
[2019-01-08 19:27:23] (INFO @ _build/transport.core.php) Packaged in 7 default Access Policy Templates.
[2019-01-08 19:27:24] (INFO @ _build/transport.core.php) Packaged in 12 default Access Policies.
[2019-01-08 19:27:24] (INFO @ _build/transport.core.php) Packaged in web context.
[2019-01-08 19:28:01] (INFO @ _build/transport.core.php) Packaged in mgr context.
[2019-01-08 19:28:01] (INFO @ _build/transport.core.php) Packaged in connectors.
[2019-01-08 19:28:01] (INFO @ _build/transport.core.php) Beginning to zip up transport package...
[2019-01-08 19:28:06] (INFO @ _build/transport.core.php) Transport zip created. Build script finished.

Execution time: 64.1917 s
```
Try first install

At the last stage after clicking the Install button, I get an error

```Fatal error: Class 'modAccessibleObject' not found in C:\OSPanel\domains\www\core\model\modx\modnamespace.class.php on line 25```

I do repeated installation with the same data - everything is OK!
Work fine.

Apache 2
PHP-7.2
MySQL-5.6

**Comment by alexeyp0708** [comment] 2019-01-09 12:39
@Alroniks   My DB Server -MySql 5.5 
My installation was successful after I added the line `use xPDO \ xPDO;`

**Comment by Mark-H** [comment] 2019-01-09 12:43
I don't quite understand why that line is needed for your installation to work while it works without it for me and several others in this thread, but as there's no harm in adding it a PR would be welcomed.

**Comment by JoshuaLuckers** [comment] 2019-01-18 19:18
This issue is now fixed in the 3.x branch.

**Closed as completed by JoshuaLuckers** 2019-01-18 19:18 UTC
Labels: bug, area-core
