### ISSUE TITLE
File TV PHP warnings from Smarty templates, PHP 8.0

### ISSUE THREAD

**Issue by deJaya** [modxcms/revolution#15792] opened 2021-08-12 13:33 UTC
### Summary
Under PHP 8.0 a fresh MODX install with no extras will outputs warnings into the Manager Log

https://community.modx.com/t/manager-error-log-lots-of-smarty-errors/4302

### Step to reproduce
Run MODX on PHP8.0 and observe Manager Error Log

### Observed behavior
`[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Undefined array key "showCheckbox"
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Undefined array key "showCheckbox"
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Undefined array key "showCheckbox"
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Undefined array key "showCheckbox"
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Undefined array key "showCheckbox"
[2021-08-12 13:25:21] (ERROR @ /path/core/cache/mgr/smarty/762a9aeb2fd288c8987ceb503f42c3f412fb399e_0.file.tvs.tpl.php : 64) PHP warning: Attempt to read property "value" on null`

### Expected behavior
No warnings

### Environment
MODX 2.8.3 PHP8.0

**Comment by Mark-H** [comment] 2021-08-12 13:41
Changing your error_reporting server configuration to not trigger warnings can help hide them, but the root cause should still be addressed.

**Comment by rthrash** [comment] 2021-08-12 14:34
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/manager-error-log-lots-of-smarty-errors/4302/10

**Comment by Ibochkarev** [comment] 2021-10-22 21:56
Related https://github.com/smarty-php/smarty/releases/tag/v2.6.32

**Comment by rthrash** [comment] 2022-04-30 19:07
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/errors-in-modx2-8-4-php8-in-the-error-log-inside-the-cms/5299/3

**Comment by rthrash** [comment] 2022-11-09 11:28
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/formit-with-php8/6005/11

**Comment by rthrash** [comment] 2023-01-17 21:30
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/multiple-errors-generated-when-updating-resource-or-visiting-dashboard/6289/2

**Comment by rthrash** [comment] 2024-01-25 15:39
This was included in the 2.8.6 release when Mat's PR was merged.

**Closed as completed by rthrash** 2024-01-25 15:39 UTC
Labels: bug
