### ISSUE TITLE
Top menu in manager is not working after clicking on manager's page body

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12296] opened 2015-01-26 12:28 UTC
I'm not sure if this has been asked before, so please close this if this is a duplicate.

Top menu in manager is not working after clicking on manager's page body

Repro:

1. Dashboard
  1. Click on manager's page, anywhere but a field.
  2. Hover/click the top menu.
2. Resource field
  1. Click (eg) pagetitle field
  2. Hover/click the top menu
  3. Move mouse out
  4. Hover/click the top menu

On 2.3.2-pl, sdk distro.

**Comment by rtripault** [comment] 2015-01-28 11:46
Hi Rico!

Which browser(s) were you using when experiencing this issue ?

For what it worth, i was not able to produce using current 2.4.0-dev on Chrome Version 40.0.2214.93 (64-bit)/Linux

Thanks

**Comment by goldsky** [comment] 2015-01-29 12:22
Firefox works fine, but not on webkit browsers.

**Comment by goldsky** [comment] 2015-01-30 17:40
https://www.screenr.com/vbtN

**Comment by goldsky** [comment] 2015-01-30 17:49
On several time trying to access the menu (by clicking any field <-> top menu), the drop down menu became transparent more and more.

![untitled](https://cloud.githubusercontent.com/assets/308524/5980436/f4c5dd78-a8e2-11e4-8260-ce59279058b7.png)

**Comment by rtripault** [comment] 2015-01-31 09:48
Much thanks for providing the video, that's really helpful. The thing is now to find the circumstances causing this...

**Comment by OptimusCrime** [comment] 2016-04-19 21:53
@goldsky Is this still an issue? Is there any way to can post steps to reproduce this? 

I am unable to reproduce this in Chrome 49.

Closing this for now, feel free to reopen if you have more information.

@modxbot close

**Closed by OptimusCrime** 2016-04-19 21:53 UTC
Labels: state/awaiting-feedback
