### ISSUE TITLE
File manager does not show anything on installations upgraded to 2.5.1 (+up to and through 2.5.5)

### ISSUE THREAD

**Issue by FBachofner** [modxcms/revolution#13148] opened 2016-10-15 18:58 UTC
### Summary

File manager does not show anything on installations upgraded to 2.5.1
### Step to reproduce
1. login to MODX manager
2. Switch from "Resources" to "Files" -- i.e. click on the files tab
3. click on "Filesystem"
### Observed behavior

neither the filesystem tree nor any files are displayed

[ the file manager _does_ work as expected on a **_new**_ installation of MODX -- installed on the same environment detailed below]
### Expected behavior

The file manager should show the tree and files
### Environment

MODX: 2.5.1
nginx: 1.11.5
mysql: MariaDB 10.1.18
browser: Firefox 49.0.1, (also tested on Internet Explorer 11.321 and Microsoft Edge 38.14393 -- I tried these on a different computer which had never before accessed this MODX installation's public and manager pages to make sure client side caching was not an issue)
### Additional Details

The database tables (71 tables total -- same as with my new working MODX installation) are using UTF8MB4 / UTF8MB4_unicode_ci.

Previous versions had problems with creating MODX DBs with UTF8MB4 but worked fine when the tables were converted after the fact.  This may be part of the problem.

On the MODX forum, Jako mentioned "Some database fields are not created because of MariaDB strict mode." [ https://forums.modx.com/thread/?thread=100904&page=2 ]

For starters: Could you identify _which_ fields (and in which tables) those might be so I can try to manually fix the problem and validate Jako's theory?

**Comment by OptimusCrime** [comment] 2016-10-16 13:15
I am pretty sure the problem here is realted to utf8mb4. As of right now, MODX does not work with that charset.

**Comment by OptimusCrime** [comment] 2016-10-16 13:18
The issue here is a combination between the utf8mb4 and MariaDB. I don't think the problem right here is that the tables and attributes are not created, but the queries on those incompatible tables are not executed correctly.

**Comment by AndrzejSzmyd** [comment] 2016-10-31 10:09
Similar problem with new created and updated files - I can't see and edit them after that.

**Comment by OptimusCrime** [comment] 2016-10-31 10:11
Do not use MariaDB, do not use utf8mb4, do not use strict mode. Should fix the issue for now.

**Comment by FBachofner** [comment] 2016-10-31 17:43
Hi Optimus Crime:

As to not using MariaDB and utf8mb4, how then do you explain that I have working (including filemanager!!) installations with exactly that "not allowed" platform?

Keep in mind, MariaDB was designed as a drop-in replacement for mySQL and it generally works perfectly in this regard.

The utf8mb4 limitation seems related to index key length(s) and would affect mySQL too, but even in this regard MODX is tremendously inconsistent with new (utf8mb4) installs sometimes working, sometimes not.

This really should be addressed.

And, as a side note, I hope that MODX will soon support PostgreSQL and Firebird databases!  :-)

**Comment by sottwell** [comment] 2016-10-31 17:51
On the same server? It probably depends on the database configuration, certain "strict" modes can cause the problems.

**Comment by Omeryl** [comment] 2016-10-31 17:52
There's no reason you shouldn't be able to use MariaDB. You just need to disable the strict modes that are on by default in the 5.7+ branches.

**Comment by OptimusCrime** [comment] 2016-10-31 18:30
@FBachofner I've never used MariaDB myself, I just know that it is not listed as a supported engine by MODX currently. I also know that is works as a drop-in replacement for MySQL, but there are some changes that could affect MODX.

However, the issue here is most likely the strict mode and/or utf8mb4. And you are right, it should be addressed soon.

However, until that is done, certain parts of the system may or may not work. If the installation is successful, it does not mean that every single query in MODX will run successfully on that platform.

I'll look into what needs to be done when I have the time.

**Comment by Mark-H** [comment] 2016-10-31 18:34
Are we sure this is that same issue? What sort of query is involved in loading the file tree? I'd like to see a bit more technical details before jumping to conclusions on the source here.

**Comment by FBachofner** [comment] 2016-11-22 20:44
@sottwell   **_yes_**, many of these sites are **_on the same server_**.

One site (originally installed with MODX 2.5.1) has a working MODX file manager, the others (**_after_** upgrade to 2.5.1) now have a failing MODX file manager.

The MODX dbs for each site (i.e. on the same server) are being served from the same MariaDB server (with the same configuration for each DB).

**_Strict mode is not enabled._**

Sorry I stepped away from this thread for a bit.  Work/Life got very busy.

**Comment by FBachofner** [comment] 2016-11-22 21:43
I should mention that I upgraded a number of these sites to 2.5.2 earlier today.

1. In the case of the (single) site with a working MODX file manager, it continues to work after upgrade.
2. In all the other the sites with a broken MODX file manager, they remain broken after upgrade to 2.5.2.



**@Mark-H** -- thank you, I agree that it seems this has nothing to do with strict mode anyway.  Presumably just opening the file manager should not involve a write to the DB (that's where strict mode would be affecting things, right?!)

**Comment by FBachofner** [comment] 2016-11-22 22:57
I noticed today that the "Media Browser" on the installations where the file manager does not work also does not work as expected.

The Media Browser **_also shows no files_** in the view in which it opens (the site root) (see **note1**)  and the filesystem can also not be accessed with the "filesystem" browser at the left [which is "separate" from the Files tab and the (presumably same) filesystem browser applet normally displayed there]

**note1** -- I know it is trying to open files in the site root because **_I can create files and folders_** using the relevant icons in the "Media Browser" -- I just can't see them anywhere from within MODX!

**Comment by OptimusCrime** [comment] 2016-11-22 23:05
Can you check the inspector to see that potential requests fail and with what error? Is PHP error logging turned on? It is impossible to recreate this issue as most of us have working media browsers.

**Comment by Mark-H** [comment] 2017-02-09 17:53
There might be a javascript error in the developer tools console. Perhaps caused by a certain extra, or something else that sets your installation apart from all the other ones that do work.

Force clearing the cache via FTP could also help, if the problem would be caused by a broken state that MODX can't clear itself, though that would be rather weird.

**Comment by OptimusCrime** [comment] 2017-03-06 23:40
Its been almost a month since @Mark-H tagged with awaiting feedback. We're unable to investigate this further without more information. I'm closing this now. @FBachofner feel free to comment or reopen if you have more information for us, or if this is still an issue for you.

@modxbot close

**Comment by FBachofner** [comment] 2017-03-07 06:14
Sorry, @Mark-H, your request from 25 days ago slipped through the cracks.

Which "developer tools console" should I be looking at?  Is this something in MODX which I am not aware of or are you talking of something like the web developer "web console" in Firefox (Chrome has something like it too).

Also, I have already tried manually cleaning the cache by deleting all the files in the relevant cache folder.

**Comment by FBachofner** [comment] 2017-03-07 06:20
@OptimusCrime, you say "feel free to comment or reopen if you have more information"

There does not seem to be any way for me to do this.

**Comment by FBachofner** [comment] 2017-03-07 18:09
For kicks, a moment ago I updated 2 of my sites to MODX 2.5.5 advanced (previously on 2.5.2 advanced).

The site where the file manager worked -- still works.
A site where the file manager did NOT work -- **still does not work**.

Everything else about both sites seems fine.

**Comment by Jako** [comment] 2017-03-07 19:02
Could you look in the browser console and check for JavaScript errors in the not working installation.

**Comment by FBachofner** [comment] 2017-04-01 21:34
Hi Jako:

Sorry for the delay, I wanted to try on a variety of computers (and browsers) after the 2.5.5 upgrade and life-complexities have been interfering.

Here's what the browser console shows on a Linux machine I am using at the moment:

```
Self Repair active  selfrepair.e769dcc4d6f0dedd8f82.js:9:8049
Empty string passed to getElementById().  github-cd1f7c97279e009c44357eb19c6bccc6b634a442001c0c5e1a368177c209bf6a.js:6:14139
Empty string passed to getElementById().  github-cd1f7c97279e009c44357eb19c6bccc6b634a442001c0c5e1a368177c209bf6a.js:6:14139
Key event not available on some keyboard layouts: key=“e” modifiers=“alt control” id=“colorfulTabsEnd”  browser.xul
Key event not available on some keyboard layouts: key=“b” modifiers=“alt control” id=“colorfulTabsBegining”  browser.xul
Key event not available on some keyboard layouts: key=“t” modifiers=“alt control” id=“colorfulTabsOpen”  browser.xul
Key event not available on GTK2: key=“u” modifiers=“accel,shift” id=“key_tm_mergeWin”  browser.xul
Key event not available on some keyboard layouts: key=“n” modifiers=“accel, alt” id=“key_tm_detachTab”  browser.xul
Key event not available on some keyboard layouts: key=“t” modifiers=“accel,alt” id=“key_tm_dupTab”  browser.xul
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“toggleReaderMode”  browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
unreachable code after return statement[Learn More]  modx.tree.js:755:16
```

The first 3 and _ESPECIALLY the last line(s) seem like they might be related_ to the problem.

"learn more" in the last error links to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

The errors in the middle lines seem to relate to various Firefox extensions.  The problem with the MODX file manager does **not** (apparently) relate to these as I have the same problem in Firefox with ZERO extensions as well as when trying with other browsers . . .

Your ongoing assistance is appreciated!

**Comment by Jako** [comment] 2017-04-02 09:24
The modx.tree.js message should be no real issue. It is just forgotten code.

Since you have different behaviours in different installations. Please check and disable compress_css and compress_js in the MODX system settings, if they are active. Often parts of the Manager don't work anymore because of those settings. But then JS console errors would be visible.

Or what is 'Self Repair'? Could that cause the problem?

**Comment by FBachofner** [comment] 2017-04-19 04:29
I just checked and compression (CSS and JS) is already disabled.

This is the case both on sites with working and non-working MODX file manager.

Thanks for your continued ideas.

**Comment by royaltyclubvp** [comment] 2017-04-30 20:33
Just in case anyone is still experiencing this issue, or anyone new has come across this issue - especially if they are hosting their MODX site on an Amazon EC2 Linux instance. Using Firefox's console, I discovered the manager's AJAX call upon trying to expand the media sources was receiving a 500 error in return. By combing through the php error_logs, I discovered the following error message:

PHP Fatal error:  Call to undefined function mb_strtolower() in /var/www/html/core/model/modx/sources/modfilemediasource.class.php on line 173

This is due to the lack of the mbstring php module on the linux installation, so installing the correct version for your installed php version and restarting the httpd daemon fixes the issue:

sudo yum install php56-mbstring
sudo service httpd restart

This may not be the fix for everyone above, but it should resolve some.

**Comment by FBachofner** [comment] 2017-04-30 23:54
@royaltyclubvp

**_Lo and behold . . . that was it!_**
I checked my logs and had the same "modfilemediasource.class.php" error you found.

On Ubuntu (and with PHP7), the installation command is:
sudo apt-get install php7.0-mbstring

Somehow when I deleted PHP5.x and installed PHP7 I must have skipped installing the mbstring plugin.

**_What is really weird_**, however, is that my new MODX site installations (on this same server!) did NOT EVER have a problem with FileManager.

It could be useful if someone could shed light on that incongruity.

**Comment by OptimusCrime** [comment] 2017-05-01 18:28
There is a system setting `use_multibyte`. This setting toggles between using the `mb_*` functions or the non-multibyte ones. If your system does not have multibyte support, set this to false.

**Comment by timmayd** [comment] 2017-10-31 16:43
@OptimusCrime we were experiencing the same issue and setting use_multibyte to NO solved this problem. Thank you.

**Comment by OptimusCrime** [comment] 2017-11-01 07:52
I am still pretty sure this problem is related to incorrect server setup, or a mix of utf8mb4 and non-multibyte setups. This is _not_ a core MODX bug.

**Comment by timmayd** [comment] 2017-11-01 13:46
I would agree; this is running on our own server and we continue to check apache logs to troubleshoot, which led me to this thread. In our case, the file manager did not work until we commented out mbstring from our php.ini (did not work using php5.6 or php7) and then set use_multibyte to NO. I don't know why our server has a conflict with mbstring.

**Comment by OptimusCrime** [comment] 2017-11-01 14:07
Do you know if the mbstring extension is in fact installed on your server?

**Comment by timmayd** [comment] 2017-11-01 14:58
It was not active so the question remains, should we enable mbstring and then turn use_multibyte back to TRUE in MODX... Is it better practice to do so?

**Comment by OptimusCrime** [comment] 2017-11-01 15:04
You should _always_ have mbstring enabled. It is almost a wonder that it is not included by default by now. Especially when MODX soon will begin to use utf8mb4 as collation in the database, and newer versions of MySQL uses this as default. Not to mention that almost everything done on the web is usually UTF8 either way. Install it and try to enable multibyte. I really hope that we can phase out support for non-multibyte soon. Would make edge cases like this easier to handle.

**Comment by timmayd** [comment] 2017-11-01 15:07
Very good to know. Will update to be sure it's enabled. Huge thanks for sharing your knowledge here @OptimusCrime

**Comment by Pryadkin** [comment] 2018-07-01 10:42
Sorry for my English.
Twice installed modx on the openserver. Filesystems worked in the first case, in the second case - no. 
File config.inc.php in 1 and in 2 case identical.
File error.log: 
"\core\model\modx\modprocessor.class.php : 256) Processor failed creating output array due to JSON error 5"

Set use_multibyte to NO - didn't help. 

Solution: 
apache-php-7.2
php-7.2
early version did not help

This is a poor solution to the problem, but better I could not. 
Thanks for the help.

**Comment by JoshuaLuckers** [comment] 2019-03-09 18:32
Is this issue still relevant? I'm in favour of closing this issue.

**Closed** 2019-03-13 18:41 UTC
Labels: state/awaiting-feedback
