### ISSUE TITLE
Issue: cannot hide admin menu in V. 2.5

### ISSUE THREAD

**Issue by bbornemann** [modxcms/revolution#13064] opened 2016-07-06 18:58 UTC
### Summary
Admin menu (gear icon) should not be available for non-admin users. Error: cannot deactivate ACL menu_system (or is it menu_tools).

### Step to reproduce
Duplicate access policy "administrator", rename to "content admin". Deactivate all menu settings. Save. Flush permissions. Login as an editor user. 

### Observed behavior
Admin menu (gear icon) is still there.

### Expected behavior
No gear icon should show up.

### Environment
MODX 2.5

**Comment by pixelchutes** [comment] 2016-08-09 22:46
@bbornemann Do your non-admin users have `settings` permissions in their associated Access Policies?

**Comment by pixelchutes** [comment] 2016-08-09 22:53
If so, that may explain why they're seeing the Admin menu in the User Nav.

Otherwise, check the menu has the desired permission associated with the access you want to enforce. 

### Gear icon > Menus:

![top_menu](https://cloud.githubusercontent.com/assets/352182/17536269/3463ffd0-5e51-11e6-98cf-254cabb10819.jpg)

**Comment by pixelchutes** [comment] 2016-08-15 22:39
Closing, cannot reproduce on 2.5.1 (at least not without more specific examples of what permissions were left available in the example "content admin" policy).

**Closed by pixelchutes** 2016-08-15 22:39 UTC
