### ISSUE TITLE
CSS: .x-panel-bwrap 

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12464] opened 2015-06-11 09:42 UTC
In Package Management, when you click on the "Download Extras" button a slide animation occurs and you can see the horizontal scroll-bar appear at the bottom during the animation.

I know it's just a small thing but setting the following in css seems to fix it:
.x-panel-bwrap {
    overflow-x:hidden;
}

**Comment by RinzeVanDerBrug** [comment] 2017-03-03 10:23
I'm going to try and fix this today.

**Comment by RinzeVanDerBrug** [comment] 2017-03-03 10:43
Cannot reproduce this.

Tested this in on macOS Sierra (10.12.3) in:
- Chrome v56.0.2924.87 
- Safari v10.0.3
- Firefox v51.0.1 

The horizontal scrollbar of the slide animation doesn't seem to appear in any of them, so this issue is probably outdated and can be closed. #modxbughunt

**Comment by rtripault** [comment] 2017-03-03 11:23
Also not able to reproduce here (Chrome/Debian Stretch), so closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by digitalpenguin** [comment] 2017-03-03 15:21
Sorry guys, still happening. 
Firefox 52.0a2 on Ubuntu
and 56.0.2924.87 on Ubuntu

I managed to get a screenshot mid-slide.
![screenshot from 2017-03-03 23-17-26](https://cloud.githubusercontent.com/assets/5160368/23556594/128b3dba-0068-11e7-891f-d024c43a2a6c.png)

**Comment by gpsietzema** [comment] 2017-03-03 19:09
Seems to be isolated to ubuntu...

**Comment by rtripault** [comment] 2017-03-03 19:43
Could very well be because of a browser extension (either creating the issue or preventing to confirm it...)

**Comment by OptimusCrime** [comment] 2017-03-03 19:53
Not able to reproduce in neither Opera, Chrome nor Firefox on macOS

**Comment by digitalpenguin** [comment] 2017-03-04 00:24
Just tested on Windows 10. Also happening with latest Edge and Firefox. No add-ons/plugins.
Although due to the way scroll-bars look it's definitely less obvious.

**Comment by Flowan** [comment] 2017-07-07 17:31
Could not reproduce this issue. Mark as fixed? #modxbughunt

**Comment by sonicpunk** [comment] 2017-07-07 18:17
#modxbughunt #1point to @Flowan

**Comment by OptimusCrime** [comment] 2017-07-07 19:18
@Flowan Did you test in the browsers @digitalpenguin reported?

**Comment by digitalpenguin** [comment] 2017-07-08 00:10
It's still occurring for me. Both Linux and Windows. macOS is the only OS I haven't been able to test but from above it sounds fine on that.

**Comment by alroniks** [comment] 2019-02-20 08:56
As it was discussed in other issues (I don't remember exactly which one) it requires to normalize CSS to fix default browsers behavior but also issue not reproducible for most of the people who tried to check it. So I am closing this one. Feel free to reopen if it still should be discussed/investigated.

**Closed by alroniks** 2019-02-20 08:56 UTC
