### ISSUE TITLE
Snippet tags inside code and pre tags no longer ignored

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#14008] opened 2018-07-20 21:36 UTC
### Summary
The parser used to ignore MODX tags inside code and pre tags.  I'm not sure when this started, but now, it tries to process them. For snippet tags, it throws a "snippet not found" error message (and does not show the code when the page is viewed). The code below adds a couple-dozen error message to the MODX Error log on each viewing of the page.

### Step to reproduce

Put these tags on a page and view the page, then check the error log.
```
<code>[[!CodeTagUncached]]</code>
<pre>[[!PreTagUncached]]</pre>
<code>[[CodeTagCached]]</code>
<pre>[[PreTagCached]]</pre>
<pre class="brush:html">[[PreTagSyntaxHighlighter]]</pre>
```

### Observed behavior
Many "snippet not found" error messages. Code is not displayed on page.

### Expected behavior
MODX tags inside code or pre tags displayed and ignored by the parser.

Entifying the brackets solves the problem but the tags really should be ignored, imo.

### Environment
MODX 2.6.5
Apache

**Comment by JoshuaLuckers** [comment] 2018-07-21 14:59
The [FixedPre plugin](
https://bobsguides.com/fixedpre-tutorial.html) enables this behavior. Or am I mistaken?

**Comment by BobRay** [comment] 2018-07-21 22:51
Yes it does, but for HTML 'code' and 'pre' tags, any code inside them is not supposed to be executed. And that used to be the case for modx snippet tags inside 'pre' and 'code' tags.

**Comment by Mark-H** [comment] 2018-07-21 23:21
As far as I know, tags were always processed, no matter what markup they're in. The log message is fairly new though.

**Comment by ghost** [comment] 2018-07-22 01:52
I have to agree with Mark here, MODX has always processed tags irrespective of any HTML tags, thus the FixedPre plugin.

**Comment by OptimusCrime** [comment] 2018-07-22 02:35
I have never experienced that code inside these tags are ignored either. @BobRay can you confirm that the behavior was different in earlier versions?

Edit: Also, I can not see the any reason why these tags should be handled differently. HTML tags and MODX tags are not the same.

I vote for closing this.

**Comment by alroniks** [comment] 2018-07-22 20:57
Yes, closing this as unfixable. I've never seen such behavior in MODX and it shouldn't do that.

**Comment by BobRay** [comment] 2018-07-22 20:57
The new error message exposed  a bunch of these at Bob's Guides.  I'm 99% sure that they were fine at the time they were written, but I have no proof. 

I'll go ahead and close this because we have a workaround in FixedPre and because fixing it would mean messing with the parser.

**Closed as completed by alroniks** 2018-07-22 20:57 UTC

**Comment by OptimusCrime** [comment] 2018-07-22 20:59
They could be caused by some of the new warnings and changes to how the parser works, although the output should be the same, the debug might have changed.

**Comment by BobRay** [comment] 2018-07-22 21:07
As I said, I'm fine with closing it, but it's definitely *not* unfixable.  You'd just do what FixedPre and a number of other utilities do. You'd do it to everything inside code or pre tags instead of inside FixedPre tags. I think just entifying left brackets inside those tags would do it.

**Comment by Mark-H** [comment] 2018-08-13 13:24
The problem implementing such a thing in the core on standard elements like code or pre would be that you are no longer able of processing tags inside code/pre tags if that is what you want to do. I don't think that's an assumption the core should make on standard HTML tags.

**Comment by Jako** [comment] 2018-08-13 17:52
It would be easier to put the tags in the example above in a chunk and create a snippet that just encodes those tag marks in that chunk and returns it afterwards to MODX.

**Comment by BobRay** [comment] 2018-08-13 19:18
@Jako This issue is closed, but I think FixedPre is a better option than having a snippet process a chunk.

@Mark-H The point of a code tag is to *display* code, so semantically, you'd shouldn't be expecting the code to execute.  That said, I don't think it's practical to make this change. I don't think we want the parser spending time fully parsing a page's HTML. which is what it would take to do it reliably.

**Comment by OptimusCrime** [comment] 2018-08-14 07:36
The MODX parser does not care about HTML semantics. 

If you flip this, how would you ever get a snippet to run inside a code block if you one day wanted to do that? The FixedPre, this is rendered impossible, which I think is unfortunate.

**Comment by Jako** [comment] 2018-08-14 07:59
@BobRay If you do that in a snippet, you could control the parsing on your own. But the FixedPre plugin works well in most circumstances.

**Comment by BobRay** [comment] 2018-08-14 20:29
OC: "The MODX parser does not care about HTML semantics."

Yes, that's implied in what I said, and I suggested that this shouldn't change. Why is this argument continuing when we all agree?
