### ISSUE TITLE
Remembering minimise buttons in the resource-edit page

### ISSUE THREAD

**Issue by gpsietzema** [modxcms/revolution#13452] opened 2017-05-11 11:22 UTC
### Summary
The resource-edit page has two blocks in the "Document" tab: the meta data (pagetitle, longtitle, etc) + content. When hitting the minimise button (top-right corner), the meta data block is minimised, but when refreshing the page it resets to the default-state.

### Step to reproduce
Edit page, minimise meta-block, refresh page.

### Observed behavior
Block isn't minimised anymore.

### Expected behavior
Block is still minimised. This should be persistent per page.

### Environment
All versions/environments.

**Comment by Mark-H** [comment] 2017-05-15 07:45
Devil's advocate here: the expected behaviour sounds like incoming "I can't edit the description anymore" tickets to me.. that plus/minus icon is pretty small and easy to miss if you don't know what you're looking for. 

Is the expected behaviour the ideal behaviour for more casual users?

**Comment by OptimusCrime** [comment] 2017-05-15 11:27
I disagree with this issue. Collapse/expand like this should not be persistent across separate requests. The change you do on one page should not reflect how the next page looks. It makes sense for other things, such as collapsed/expanded states in the trees, but in this scenario I feel like the functionality is only there to make it easier to edit a single resource. After that the system should default back to expanding all the sections again.

**Comment by gpsietzema** [comment] 2017-05-17 10:08
From a user-perspective it would make sense. I would like to make this persistent per user-resource-combination, not just per page.

If a user minimises the header, he does it for a reason. If he returns later and has to minimise it again, that wouldn't make sense to me.

**Comment by OptimusCrime** [comment] 2017-05-18 10:37
But minimizing itself has no particular function. It is just the same as scrolling down a page. If the resource in fact has a region that is irrelevant, then it would be better to use manager customizations or something else to always hide that part.

It might be habits and what I'm used to, but I would not expect a collapse/expand widget to remember my state. It would further confuse me if this widget sometimes was collapsed and sometimes not, as this would be stored in a user-resource-basis.

To me it sounds like some resources for some reason has sections that are not used, and there are better ways of dealing with that than a collapse widget. I belive it was added (partially because ExJS just ships those features, but also) so you could "hide" sections so you could focus on a region for a longer period of time. For example if you were to write a long text in the content field, then it perhaps could be useful to remove the pagetitle/longtitle/introtext/description to make the interface less "clustered". However, doing so should not, in my opinion, be reflected in the future.

**Comment by OptimusCrime** [comment] 2018-02-18 22:34
Closing this. Feel free to reopen or comment.

@modxbot close

**Closed** 2018-02-18 22:34 UTC
