### ISSUE TITLE
Output filter isempty doesn't work.

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14021] opened 2018-07-30 15:15 UTC
### Summary
Comment from @opengeek https://github.com/modxcms/revolution/pull/13343#issuecomment-408727380 for PR #13343 
> Are we aware that this completely broke the `isempty` output filter? After months of trying to track down why my sites were no longer working in the 2.6/2.7 releases, I finally tracked the problem down to this commit.
>
> The following returns the value of the placeholder instead of the else when the value is not empty:
> ```[[+placeholder:isempty:then=`foo`:else=`bar`]]```

### Step to reproduce
Use the following code somewhere in your content, chunk or template.
 ```[[+placeholder:isempty:then=`foo`:else=`bar`]]```

### Observed behavior
No output

### Expected behavior
The output `bar`

### Environment
MODX version 2.6.*

**Comment by opengeek** [comment] 2018-07-30 19:40
Thanks for entering this issue @JoshuaLuckers

**Comment by Jako** [comment] 2018-07-30 20:36
Closing this as invalid because of https://github.com/modxcms/revolution/pull/13343#issuecomment-409000698

**Comment by opengeek** [comment] 2018-07-30 20:57
This is absolutely valid and is a bug. It broke backwards compatibility.

**Comment by OptimusCrime** [comment] 2018-07-30 21:22
As far as I can understand, the syntax in this issue is exactly the syntax my guard was supposed to stop. The use of non-conditional output modifiers on PHP7 results in a 500 internal server error.

**Comment by opengeek** [comment] 2018-07-30 21:36
> The use of non-conditional output modifiers on PHP7 results in a 500 internal server error.

All I know is this worked before and is a change in expected behavior. There has to be a way to make it work again. I don't see how `eq` or `ne` is any different than `isempty` or `notempty`. They should all return boolean values. If anything, this is a bigger issue with the implementation of how these conditional expressions are being evaluated.

**Comment by OptimusCrime** [comment] 2018-07-30 21:37
Seems like this case does not cause a 500 error. Here is a comparison between the different uses with todays behavior 2.6.5 and the code just before my PR, using this syntax (running php 7.1.3):

```html
As conditional output modifier:
existing_placeholder_with_content: [[+existing_placeholder_with_content:isempty:then=`foo`:else=`bar`]]
existing_placeholder_without_content: [[+existing_placeholder_without_content:isempty:then=`foo`:else=`bar`]]
nonexisting_placeholder: [[+nonexisting_placeholder:isempty:then=`foo`:else=`bar`]]

String output modifier:
existing_placeholder_with_content: [[+existing_placeholder_with_content:isempty=`foo`]]
existing_placeholder_without_content: [[+existing_placeholder_without_content:isempty=`foo`]]
nonexisting_placeholder: [[+nonexisting_placeholder:isempty=`foo`]]
```

Where `existing_placeholder_with_content` is `OptimusCrime` and `existing_placeholder_without_content` is an empty string.

## Current behavior

### As conditional output modifier

```
existing_placeholder_with_content: OptimusCrime
existing_placeholder_without_content:
nonexisting_placeholder:
```

### String output modifier

```
existing_placeholder_with_content: OptimusCrime
existing_placeholder_without_content: foo
nonexisting_placeholder: foo
```

## Previous behavior

### As conditional output modifier

```
existing_placeholder_with_content: OptimusCrime
existing_placeholder_without_content:
nonexisting_placeholder: bar
```

### String output modifier

```
existing_placeholder_with_content: OptimusCrime
existing_placeholder_without_content: foo
nonexisting_placeholder: foo
```

**Comment by OptimusCrime** [comment] 2018-07-30 21:58
>All I know is this worked before and is a change in expected behavior.

I can not really see how this is expected behavior. According to my tests (above) the `then` condition is never triggered when chained with `isempty`. 

```
[[+existing_placeholder_with_content:isempty:then=`foo`:else=`bar`]]
```

Should have returned `bar`, but it does not. It returns the original string, and this using the code _before_ I changed it. Perhaps PHP7 also introduced some changes that affected this. Either way, the syntax is undocumented, and I would therefore consider it undefined behavior. 

>There has to be a way to make it work again. I don't see how eq or ne is any different than isempty or notempty. They should all return boolean values. 

Then it breaks BC, because `isempty` returns a string in the implementation that has been in MODX for as long as I can remember. The only way we can get it to work again is either to fix the syntax, implement a new modifier, or undo my PR. 

>If anything, this is a bigger issue with the implementation of how these conditional expressions are being evaluated.

The change introduced in my PR does not alter any documented behavior. As far as I can see, using the syntax 

```
:isempty=`foo`
```

works exactly as before.

**Comment by opengeek** [comment] 2018-07-30 22:04
Whatever then. Closing.

**Closed as completed by opengeek** 2018-07-30 22:04 UTC
