### ISSUE TITLE
MODX3: Error report on a single line 

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#14010] opened 2018-07-21 12:47 UTC
### Summary
```
[2018-07-18 16:59:32] (ERROR @ F:\Zend\Apache24\htdocs\core\model\modx\modcachemanager.class.php : 347) Error caching lexicon topic lexicon/en/core/element [2018-07-18 17:41:46] (ERROR @.....
```

**Comment by Jako** [comment] 2018-07-21 13:21
Duplicate of #13946

**Closed as completed by Jako** 2018-07-21 13:21 UTC
