### ISSUE TITLE
Feature Request - Hover info on resource tree?

### ISSUE THREAD

**Issue by terrybarth** [modxcms/revolution#13219] opened 2016-12-15 14:54 UTC
Modx Evo has a really handy feature that provide resource information on hover in the resource tree, e.g. doc id, template, published, etc.

Can this be added to Modx Revo?  

See attached.
![resource-tree-hover](https://cloud.githubusercontent.com/assets/526281/21228579/fc9d5f30-c2a3-11e6-9305-8ea955dbd2d1.png)

Thanks.

**Comment by zaigham** [comment] 2016-12-24 17:54
We have Quick Update in MODX Revolution, which can be helpful.

**Comment by terrybarth** [comment] 2016-12-24 19:14
Where do I find this? I searched for it with installer, nothing came up?

**Comment by sottwell** [comment] 2016-12-24 19:49
Right-click on the resource, select Quick Update.

**Comment by sottwell** [comment] 2016-12-24 20:04
I'm pretty sure this will still work https://forums.modx.com/thread/32581/some-hacks-to-the-document-tree-in-manager#dis-post-178843

**Comment by sottwell** [comment] 2016-12-24 20:15
Ahah! In Revo 2.5.2 at least, there is a System Setting, `resource_tree_node_tooltip`

**Comment by terrybarth** [comment] 2016-12-24 23:02
Zaigham, Yes, the right click quick edit. I knew that, I thought you were referring to an extra. 

Susan, yep, I'm familiar with the setting to change the field used in the resource tree.

I assume the "hack" would have to be redone with each upgrade. Even if not, it would be a lot of messing around for a lot of sites. Not worth the effort for me.

I just find the hover with all the fields is really handy.  It would be cool if it was built in to Modx or at least an extra.

Thanks everyone!

**Comment by sottwell** [comment] 2016-12-25 00:17
It should be possible to modify it with a plugin, to override that $qtipField value.

**Comment by rtripault** [comment] 2016-12-26 09:39
Unfortunately Susan, there is no event to help achieve that.
I too thought that could be fairly easy to do (been intrigued by this feature), but turns out the only way i found is too "hacky" (at least for my taste).

It involves an ExtJS plugin to be added in the resource tree and an extra ajax request for each resource node to build the tooltip (by calling the resource/get processor). While "it works", it's far from being optimal.

**Comment by OptimusCrime** [comment] 2017-02-10 19:05
Is this a yay or nay? There was a choice taken when the qtip field was designed. You can chose what to expose, but you are limited to one value as far as I know.

One option could be to introduce a new event(?)

**Comment by OptimusCrime** [comment] 2017-09-05 19:51
No comments or thoughts posted in 7 months -- closing. This COULD be done by a extra, although it would require some work. It just does not seem to be enough interest around this.

In my opinion is much of the information exposed by Evo redundant too:

- Menu index: irrelevant in most cases.
- Url alias: feel like I never need to look this up for a particular resource.
- Template: identifyable if you set unique icons for the templates.
- Publish date: not often used, better suited for Collections or other extras.
- Unpublish date: same as above.

The rest is also something I have never found myself in dire need of finding out without having the time to click an individual resource.

@modxbot close

**Closed by OptimusCrime** 2017-09-05 19:51 UTC
