### ISSUE TITLE
Searchbar does not react to 'Enter' keypress

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12714] opened 2015-10-12 13:41 UTC
While we able to navigate through Uberbar search results with `up` and `down` arrow keys, the only way to open currently selected entry is a mouseclick. I think it should be opened by hitting `Enter` key as well.

**Comment by pixelchutes** [comment] 2015-10-12 18:37
I cannot reproduce (v2.4.2-pl) -- Perhaps try clearing your local browser cache?

**Comment by whitebyte** [comment] 2015-10-12 18:55
Hmm, it looks like Firefox-specific issue. Tried on both Windows and Linux, 2 different PCs. Chrome works just fine, FF ignores Enter and Ctrl+Enter.
MODX 2.4.0, 2.4.2

**Comment by pixelchutes** [comment] 2015-10-12 22:40
Confirmed.
> TypeError: e is undefined

**Comment by jpdevries** [comment] 2015-11-29 13:07
This is an unfortunate bug but it does bring an accessibility concern to the surface. If the uberbar were an HTML-first semantic `<form>` that posted to a search results landing page then the search feature would still be accessible even in cases of script breakage like this one.

The uberbar is currently an `<input>` inside `<div>` and lacks an associated `<form>`.  
![](http://j4p.us/image/292w3q3N3P1m/Screen%20Shot%202015-11-29%20at%205.03.41%20AM.png)

**Comment by Mark-H** [comment] 2015-12-08 00:55
Looks like firefox simply doesn't have window.event: http://stackoverflow.com/a/9813523

**Comment by EasterPeanut** [comment] 2017-03-03 09:00
I will try to fix this today.

**Comment by Mark-H** [comment] 2017-03-03 20:12
Fixed in 2.5.6

**Closed by Mark-H** 2017-03-03 20:12 UTC
Labels: bug
