### ISSUE TITLE
package manager ext-all.js error

### ISSUE THREAD

**Issue by hvostoblud** [modxcms/revolution#12400] opened 2015-03-28 18:44 UTC
I have a problem with fresh intalled modx site. Package manager stucks at "loading" status.
There is ext-all.js error in browser console says: "SyntaxError: expected expression, got '}' ext-all.js:1:41"

modx version: 2.3.3-pl
win 8.1 sl
xampp local server
curl enabled
timezone UTC+3 Moscow RTZ2

compress_css = no
compress_js = no
js error fires in all browsers

Sniffing packets reveals that data exchange goes well, so there is no curl problem or something.
Searching for similliar issues, resulted this https://github.com/modxcms/revolution/issues/12093
Is it timezone problem? Have no idea how to test if it is, or how to avoid it. (tried to change timezone and reinstall xampp, takes no effect)

**Comment by hvostoblud** [comment] 2015-03-30 21:53
Error fires while handling some kind of XMLHttpRequest in ext-base.js, witch returns response:"{"success":true,"total":"15","results":}" 
just after category in extras category tree click

**Comment by karakum** [comment] 2015-10-28 20:11
same problem
MODX Revolution 2.4.2-pl

ajax POST request to 'http://localhost/connectors/index.php?provider=1&action=workspace%2Fpackages%2Frest%2FgetList ...' return '{"success":true,"total":"95","results":}'

**Comment by amitpatil321** [comment] 2016-01-14 16:50
+1

**Comment by mozzi** [comment] 2016-01-14 18:17
any ideas what is causing it? i have same error, modx Revo 2.4.2

**Comment by amitpatil321** [comment] 2016-01-15 09:32
@mozzi, The problem is extjs expects response data in form of JSON, but the page returns some error like "<br>Fatal error in xyz.php at line 135" thats why it throws error. If you have control over the file which is returning data then you can chek your response to be valid JSON data.

**Comment by Denwebart** [comment] 2016-03-16 23:11
Same problem. XAMPP PHP 5.6.19

**Comment by OptimusCrime** [comment] 2016-08-10 07:12
The actual error has been identified in issue #13079.

Closing in favor of that.

@modxbot close

**Closed by OptimusCrime** 2016-08-10 07:12 UTC
