### ISSUE TITLE
Uncached snippets fails.

### ISSUE THREAD

**Issue by dimonische** [modxcms/revolution#13394] opened 2017-03-23 13:43 UTC
### Summary
When snippet loads from resource by "[[snippet]]", all works normally. "[[!snippet]]" calls nothing, only show itself in the code.

### Environment
MODX Revolution 2.5.2-pl (traditional), CentOS 6, Apache 2.0, PHP 5.4.45,  MySQL 5.5.47

**Comment by wuuti** [comment] 2017-03-23 16:05
What exactly do you mean by "only show itself in the code"? With the information given we won't be able to reproduce your case. 
By the way: you should consider updating your MODX core.

**Comment by OptimusCrime** [comment] 2017-03-23 17:08
You should also consider upgrading your [PHP version 5.4 EOL was in 2015](http://php.net/supported-versions.php).

About your problem, I am not able to reproduce this. Cached and uncached workes just the same here. Is there any more information about the incident you can provide?

**Comment by pixelchutes** [comment] 2017-03-23 21:38
@dimonische Can you elaborate on your Snippet call scenario?

**Example:** Is it being called within a Template, Chunk, or from a TV? Is any _nesting_ involved? If so, you may need to ensure the calling tag is also uncached, but it's hard to say given the lack of complete example.

**Comment by dimonische** [comment] 2017-03-24 07:28
In one case snippet calls from template: http://spb-centre.ru/viki- 
mini. The same with [[!pdoCrumbs?&showHome=`1`]]: http://spb-centre.ru/
In another case snippet calls directly from resource: http://spb- 
centre.ru/kontaktyi (also works without "!").

**Comment by wuuti** [comment] 2017-03-24 09:41
@dimonische unfortunately it does not help much to have the frontend links (despite the fact that they are in russian language). 

- how does your template code look like? 
- what settings are on the failing resource? (e.g. is it cached?) 
- is there something in the error.log?

**Comment by dimonische** [comment] 2017-03-24 12:32
Resource code (settings with unchecked "Cacheable"):

[[*createdon:ago]]
<br>[[!canonical]]
<div id="breadcrumb">[[!pdoCrumbs?&showHome=`1`]]</div>

______
If I change snippet call to "[[pdoCrumbs?&showHome=`1`]]", all works  
normally.


Template code:
<!DOCTYPE html>
[[$head]]
<body id="top">
<div class="wrapper row1">
     <div id="breadcrumb">[[!pdoCrumbs?&showHome=`1`]]</div>
   <header id="header" class="hoc clear">
     <div id="logo">
       <h1><a href="index.html">Онлайн-кассы</a></h1>
       <p>Кассовое оборудование для  
работы по новому закону 54-ФЗ</p>
     </div>
   </header>
</div>

[[$menue_up]]

<div class="wrapper row3">
   <main class="container hoc clear">
     
     <section class="section class="group center">
[[$content]]

     </section>

</div>

[[$slidemodels]]
[[$footer]]

[[$underground]]
</body>
</html>

____
there is nothing in error log, which can be related to our issue.

**Comment by OptimusCrime** [comment] 2017-09-04 21:22
Closing as we are unable to trace this any further. If there were issues with calling (un)cached snippets, there would be many more issues reported on this. There might be a problem in your installation or with the extra (or possibly your code).

Feel free to comment or reopen the issue if you have further information to share.

@modxbot close

**Closed by OptimusCrime** 2017-09-04 21:22 UTC
