### ISSUE TITLE
ExtJS: modx-combo-user doesn't render username but user ID instead when user is preselected

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13267] opened 2017-01-27 14:35 UTC
### Summary
Using an extjs modx-combo-user and trying to preselect a user when combo is loaded doesn't render the username but it's ID instead.

### Step to reproduce
```
{
    xtype: 'modx-combo-user'
    ,fieldLabel: _('resource_createdby')
    ,description: '<b>[[*createdby]]</b><br />'+_('resource_createdby_help')
    ,name: 'created_by'
    ,hiddenName: 'createdby'
    ,id: 'modx-resource-createdby'
    ,anchor: '100%'
    ,value: config.record.createdby || MODx.user.id
}
```

### Observed behavior
Doesn't render the username of preselected user but it's ID instead.

### Expected behavior
Should render username of the preselected user.

### Environment
MODX version: 2.5.4-pl

*Can be fixed by adding the following lines to:*

https://github.com/modxcms/revolution/blob/2.x/core/model/modx/processors/security/user/getlist.class.php#L35

```
$id = $this->getProperty('id');
if (!empty($id)) {
    $c->where(array('id' => $id));
}
```

**Comment by Jako** [comment] 2017-01-30 15:32
It looks like all modx-combo variants should have this issue.

**Comment by gadgetto** [comment] 2017-01-31 13:32
The template-combo works as expected.

**Comment by Jako** [comment] 2017-01-31 14:14
Yes, but it fetches the whole templates with limit:0 for some reason. Seems that the store is filtering the pagination.

**Comment by sdrenth** [comment] 2017-08-31 12:06
@gadgetto Is this issue fixed already? I can't seem to reproduce this issue in branch 2.x.

**Comment by gadgetto** [comment] 2017-09-01 13:44
You need a big user list > 20 users to reproduce this. I still can reproduce this.

**Comment by sdrenth** [comment] 2017-09-01 14:10
@gadgetto Ahh I see, the problem occurs when you have a listbox which has pagination. If you have a value preselected which is being retrieved on page 1 of the listbox options all is fine. However if you have a preselected value which is not being retrieved yet (so its on page 2 or further on in the listbox) the name is not yet retrieved so it is displaying the value instead.

I'm thinking, maybe a render value method should run, which performs an ajax request to retrieve the name for the selected user?

**Comment by Jako** [comment] 2017-09-01 14:44
It could be fixed with the code from @gadgetto at the start of this thread.

**Comment by alroniks** [comment] 2018-11-05 09:36
Solved. PR is merged.

**Closed by alroniks** 2018-11-05 09:36 UTC
Labels: area-core, bug, priority-2-high, state/accepting-pull-request
