### ISSUE TITLE
MODX2.7: Top menu is broken when add new item

### ISSUE THREAD

**Issue by catsmeatman** [modxcms/revolution#14169] opened 2018-11-30 10:21 UTC
### Summary
New menu item not fit in top horizontal menu

### Step to reproduce
1. Add new item in /manager/?a=system/action
2. Reload any manager page
3. ![bug](https://user-images.githubusercontent.com/3153003/49283246-543d8f80-f4a2-11e8-8a5a-80ca7993c245.png)

### Observed behavior
this is caused by #modx-topnav {max-width: 68em;}

### Environment
MODX 2.7-advanced

**Comment by jonleverrier** [comment] 2018-11-30 10:29
~Strange - when I view the `max-width` for `#modx-topnav` it is set in pixels (1200px which equates to 75em).~

![screen shot 2018-11-30 at 11 29 41](https://user-images.githubusercontent.com/2373940/49283893-46344280-f493-11e8-9f2d-3316fe25a582.png)

~Could this be a problem caused by your custom manager theme perhaps?~

**Comment by Ruslan-Aleev** [comment] 2018-11-30 10:39
@jonleverrier I updated the pure MODX 2.6.5 to 2.7 - the problem is in place.
I use Windows 7, checked in last Chrome and Firefox.

**Comment by JoshuaLuckers** [comment] 2018-11-30 10:43
Does clearing the browser cache help?

**Comment by Ruslan-Aleev** [comment] 2018-11-30 10:59
@JoshuaLuckers It did not help me. The problem may be:
1) due to the fact that MODX was updated to 2.7, and not installed cleanly.
2) is Windows OS.

**Comment by jonleverrier** [comment] 2018-11-30 11:16
In fact, after clearing my cache, I can see that `max-width` is set to 68em not 1200px! So ignore my previous comment :)

**Comment by jonleverrier** [comment] 2018-11-30 11:38
looks like the `max-width` of `#modx-topnav` was changed in this commit:
https://github.com/modxcms/revolution/commit/f5840eeba313bda24feafa9cb01874b72243303b#diff-7e2c7fd904a55c9f817302cebbcaf068

Out of interest, why it was changed @Alroniks ?

**Comment by jonleverrier** [comment] 2018-11-30 12:20
I can't quite pin it down. 

Looks like something happened to the generated css during this commit:
https://github.com/modxcms/revolution/commit/f5840eeba313bda24feafa9cb01874b72243303b#diff-7e2c7fd904a55c9f817302cebbcaf068

Any ideas @Jako ?

**Comment by alroniks** [comment] 2018-11-30 12:20
Looks like it comes from some library that was updated.

**Comment by Jako** [comment] 2018-11-30 16:03
Hmm, some grunt process is running mad. It removed the `:not` css rules too.

**Comment by muzzwood** [comment] 2018-12-03 04:08
Does anyone have a quick fix for this issue?

It might cause other issues but for now I've just changed line 2345 in index.css from `max-width:68em;` to `max-width:100%;`.

**Comment by jonleverrier** [comment] 2018-12-03 08:28
I tried to fix over the weekend, but I can’t find any reference to `max-width` on `#modx-topnav` in the SASS files in the 2.x branch. 

Any ideas where that property is coming from @jako ?

**Comment by Ibochkarev** [comment] 2018-12-03 08:30
@jonleverrier 

https://github.com/modxcms/revolution/blob/2.x/_build/templates/default/sass/_navbar.scss

**Comment by jonleverrier** [comment] 2018-12-03 08:33
@ibochkarev - I looked at that file. No reference to `max-width` on `#modx-topnav` !

**Comment by Ibochkarev** [comment] 2018-12-03 08:34
@jonleverrier Sorry, did not finish reading

**Comment by Jako** [comment] 2018-12-03 08:41
The template uses node-neat and bourbon. If I am right it is caused by node-neat.

**Comment by jonleverrier** [comment] 2018-12-03 08:55
Thanks @Jako - that makes sense now. 

Before I try and fix, If I compile the CSS locally, the `max-width` value on `#modx-topnav` is set correctly to the old value of 1200px and not 68em?! Should that be the case?

**Comment by Jako** [comment] 2018-12-03 09:03
Could you look if the missing :not (i.e. in https://github.com/modxcms/revolution/commit/f5840eeba313bda24feafa9cb01874b72243303b#diff-7e2c7fd904a55c9f817302cebbcaf068L4183) rules are there in your compiled css? Then we have to solve a compilation issue on integrator side.

**Comment by jonleverrier** [comment] 2018-12-03 09:18
@Jako They are not missing in my generated CSS! So like you say, looks like it could be a compiling issue.

**Comment by Jako** [comment] 2018-12-03 09:31
If I remember right, then I did not notice a CSS change, when I compiled the CSS on my installation after the bower removement. So it should be a compiling issue.

**Comment by alroniks** [comment] 2018-12-06 13:58
@jonleverrier Which versions of nodejs and npm did you use?

**Comment by jonleverrier** [comment] 2018-12-06 14:26
@Alroniks I'm using:

- node v6.14.4
- npm 3.10.10

I can't remember precisely, but I either had some problems with building the MODX CSS or there was a conflict with my other build tools, so had to down grade.

**Comment by OptimusCrime** [comment] 2018-12-06 15:02
I have the same issue, running more updated versions of node and npm:

```
~/.../templates/default/css  on  2.x  $ node -v
v10.13.0
~/.../templates/default/css  on  2.x  $ npm -v
6.4.1
```

**Comment by jonleverrier** [comment] 2018-12-06 15:18
@Alroniks @Jako 

I've just updated to the latest version of node.js:

- node v10.14.1
- npm v6.4.1

I managed to compile the CSS without any errors (plenty of warnings!). The `max-width` on `#modx-topnav` is still set to 1200px (not 68em which is causing the issue).

However, the missing `:not` (https://github.com/modxcms/revolution/commit/f5840eeba313bda24feafa9cb01874b72243303b#diff-7e2c7fd904a55c9f817302cebbcaf068L4183) are still missing.

**Comment by alroniks** [comment] 2018-12-06 15:32
@OptimusCrime Yes, I have the same versions and recompiling does not give me an any changes (it means that issue still there). So it's a problem.

**Comment by OptimusCrime** [comment] 2018-12-06 15:42
@Alroniks you do properly clean the env before running the build?

```
rm -rf node_modules && npm i && grunt build
```

**Comment by alroniks** [comment] 2018-12-06 15:59
@OptimusCrime Yes, nothing. Weird.

**Comment by Jako** [comment] 2018-12-06 20:38
It is a sass compiling issue (the :not rules are away after grunt sass), but I had no time to locate this.

**Comment by Jako** [comment] 2018-12-06 21:45
The :not rules are removed by libsass: https://github.com/sass/node-sass/issues/2330. So we have to wait for a fix there.

**Closed as completed** 2018-12-14 21:26 UTC
Labels: type-frontend, bug
