### ISSUE TITLE
[3.0.0-rc1] Error: Class 'DocumentUpdateManagerController' not found

### ISSUE THREAD

**Issue by eire69k** [modxcms/revolution#16019] opened 2022-02-01 09:37 UTC
### Summary
Changing to a custom or even an empty template causes allways the same error as soon as I try to save a resource (document).

### Step to reproduce
Just changing the existing start page in a fresh installation to a custom or an empty template and try to save.

### Observed behavior
When I try to change a template of the start page or another resource to a custom or even an empty template, I get allways the following error message:

Errors:

    ResourceManagerController::getInstance(object, string "DocumentUpdateManagerController", Array ( [namespace] => core [namespace_path] => /Users/(my_username)/Sites/(my_folder_name)/manager/ [action] => resource/update [controller] => resource/update ) )
    MODX\Revolution\modManagerResponse->outputContent(Array ( ) )
    MODX\Revolution\modManagerRequest->prepareResponse()
    MODX\Revolution\modManagerRequest->handleRequest()

When I experimentally changed the "resource type" of a resource to "static resource", I was able to change and save the resource with a custom template. But after changing the resource type back to "document", I get the same issue again when I try to change and save another or an empty/base template.

### Expected behavior
Normally, it should be possible to assign any template to a resource (document).

### Environment
- fresh installation of MODx Revolution [3.0.0-rc1] (german)
- MAMP PRO 6.6
- MySQL 5.7.34
- Apache 2.4.46
- PHP 7.4.21
- Firefox 96.0.3

**Comment by Mark-H** [comment] 2022-02-01 09:38
Duplicate of #16004 #16010 and fixed in #15997.

**Closed as completed by Mark-H** 2022-02-01 09:38 UTC
Labels: bug

**Comment by eire69k** [comment] 2022-02-01 10:12
> Duplicate of #16004 #16010 and fixed in #15997.

Oops, I had not found that. I'm sorry Mark. I apologise for my post. I could fix this now with your link. Many thanks for your answer!

**Comment by Mark-H** [comment] 2022-02-01 10:15
No worries. :)
