### ISSUE TITLE
MODX 3.0 error

### ISSUE THREAD

**Issue by Oetzie** [modxcms/revolution#13873] opened 2018-04-19 17:34 UTC
### Summary
While testing MODX 3 I get a 500 error when I open the media browser during creating elements. When I create an element and I open the media browser I get the follow error:
```
[19-Apr-2018 17:28:30 UTC] PHP Fatal error:  Uncaught League\Flysystem\FileNotFoundException: File not found at path:  in /Users/oenetjeerddebruin/Desktop/www/revolution/core/vendor/league/flysystem/src/Filesystem.php:388
Stack trace:
#0 /Users/oenetjeerddebruin/Desktop/www/revolution/core/vendor/league/flysystem/src/Filesystem.php(353): League\Flysystem\Filesystem->assertPresent('')
#1 /Users/oenetjeerddebruin/Desktop/www/revolution/core/model/modx/sources/modmediasource.class.php(404): League\Flysystem\Filesystem->getMetadata('')
#2 /Users/oenetjeerddebruin/Desktop/www/revolution/core/model/modx/processors/browser/directory/getfiles.class.php(56): modMediaSource->getObjectsInContainer('/')
#3 /Users/oenetjeerddebruin/Desktop/www/revolution/core/model/modx/modprocessor.class.php(176): modBrowserFolderGetFilesProcessor->process()
#4 /Users/oenetjeerddebruin/Desktop/www/revolution/core/model/modx/modx.class.php(1735): modProcessor->run()
#5 /Users/oenetjeerddebruin/Desktop/www/revolution/core/model/modx/modconnectorresponse.class.php(140): modX->runProce in /Users/oenetjeerddebruin/Desktop/www/revolution/core/vendor/league/flysystem/src/Filesystem.php on line 388
```

### Step to reproduce
- Create an element (don't save it).
- Select a static file (the processor will give a 500 error);

### Observed behavior
-

### Expected behavior
-

### Environment
MODX 3.0
PHP Version 7.2.1

@bezumkin maybe you can check this because you implemented this?

**Comment by bezumkin** [comment] 2018-04-19 17:37
@Oetzie You need to test it [with my PR](https://github.com/modxcms/revolution/pull/13811), because it fixes a lot of problems in current media sources.

**Comment by Oetzie** [comment] 2018-04-19 17:46
@bezumkin Oke :-)

**Comment by pbowyer** [comment] 2018-05-12 08:35
Hi @Oetzie, was this issue resolved with the PR (or the latest version of MODX in Git)?

**Comment by Oetzie** [comment] 2018-05-14 19:13
@pbowyer didn't find time to test it with the PR from @bezumkin

**Comment by Ibochkarev** [comment] 2019-02-12 18:04
The error does not reproduce. Fixed earlier.
Tested on MODX 3.0 pl - set through a composer.

I vote for closing.

**Comment by JoshuaLuckers** [comment] 2019-02-12 18:16
I'm closing this since it seems to be fixed. If that's not the case feel free to open a new issue.

**Closed as completed by JoshuaLuckers** 2019-02-12 18:16 UTC
