### ISSUE TITLE
Error message: "Property set not found with ID Default."

### ISSUE THREAD

**Issue by randomdave** [modxcms/revolution#13123] opened 2016-09-09 13:41 UTC
### Summary

Error message: "Property set not found with ID Default."
This happens when I save any TV and "Property set not found with ID 0." error when I select the default property of an element.
I found it came in when I upgraded to 2.4.2pl and not fixed by installing 2.5.0 or 2.5.1 sequentially upgraded.
### Environment

MODX version 2.4.2pl

**Comment by alroniks** [comment] 2018-07-23 13:43
Looks like only one version was affected and now all works fine. I am closing it, could not reproduce on 2.7.0-dev

**Closed by alroniks** 2018-07-23 13:43 UTC
