### ISSUE TITLE
2.3.1-pl Autocomplete for form fields on by default, can't override

### ISSUE THREAD

**Issue by lmignot** [modxcms/revolution#11895] opened 2014-08-14 09:58 UTC
Form fields in Manager have autocomplete to 'on' by default, i traced it to:

manager/assets/modext/core/modx.js:42

``Ext.override(Ext.form.Field,{
        defaultAutoCreate: {tag: "input", type: "text", size: "20", autocomplete: "on", msgTarget: 'under' }
});``

This sets all form fields in CMPs to have autocomplete turned on. In the case of say a password field, this is often not desirable. 

Suggest adding a field-level override for this.

**Comment by OptimusCrime** [comment] 2016-04-19 21:56
Duplicate of #6703

@modxbot close

**Closed by OptimusCrime** 2016-04-19 21:56 UTC
