### ISSUE TITLE
Do not install. Do not reply on DB connection test. 

### ISSUE THREAD

**Issue by guelu63** [modxcms/revolution#14988] opened 2020-02-01 22:16 UTC
Error on console:
```
SyntaxError: expected expression, got '<' 17 ext-core.js:1:1
    decode                 https://modx3.local/setup/assets/js/ext-core.js:9
    success                 https://modx3.local/setup/assets/js/sections/database.js:22
    b                           https://modx3.local/setup/assets/js/ext-core.js:9
    e                           https://modx3.local/setup/assets/js/ext-core.js:9
    n/s[v]<                 https://modx3.local/setup/assets/js/ext-core.js:9
    (Asíncrono: setInterval handler)
    n                           https://modx3.local/setup/assets/js/ext-core.js:9
    j                            https://modx3.local/setup/assets/js/ext-core.js:9
    request                 https://modx3.local/setup/assets/js/ext-core.js:9
    request                 https://modx3.local/setup/assets/js/ext-core.js:9
    testConnection     https://modx3.local/setup/assets/js/sections/database.js:19
    z                            https://modx3.local/setup/assets/js/ext-core.js:9
    (Asíncrono: EventListener.handleEvent)
    I                             https://modx3.local/setup/assets/js/ext-core.js:9
    addListener           https://modx3.local/setup/assets/js/ext-core.js:9
    l                             https://modx3.local/setup/assets/js/ext-core.js:9
    j                             https://modx3.local/setup/assets/js/ext-core.js:9
    addListener           https://modx3.local/setup/assets/js/ext-core.js:9
    addListener           https://modx3.local/setup/assets/js/ext-core.js:9
    each                      https://modx3.local/setup/assets/js/ext-core.js:9
    addListener           https://modx3.local/setup/assets/js/ext-core.js:9
    <anonymous>      https://modx3.local/setup/assets/js/sections/database.js:2
    b                            https://modx3.local/setup/assets/js/ext-core.js:9
    createDelegate      https://modx3.local/setup/assets/js/ext-core.js:9
    (Asíncrono: setTimeout handler)
    defer                      https://modx3.local/setup/assets/js/ext-core.js:9
    b                            https://modx3.local/setup/assets/js/ext-core.js:9
    fire                         https://modx3.local/setup/assets/js/ext-core.js:9
    each                       https://modx3.local/setup/assets/js/ext-core.js:9
    fire                         https://modx3.local/setup/assets/js/ext-core.js:9
    c                            https://modx3.local/setup/assets/js/ext-core.js:9
    (Asíncrono: EventListener.handleEvent)
    a                            https://modx3.local/setup/assets/js/ext-core.js:9
    onDocumentReady https://modx3.local/setup/assets/js/ext-core.js:9
    <anonymous>      https://modx3.local/setup/assets/js/modx.setup.js:1
```

**Comment by CrazyBoy49z** [comment] 2020-02-02 01:51
Please clear browser cache for setup MODX.

**Comment by JoshuaLuckers** [comment] 2020-02-03 21:28
Thanks for taking time to report this issue. Are you able to reproduce this error? If yes please share the steps to reproduce.

**Comment by CrazyBoy49z** [comment] 2020-03-05 13:44
> Thanks for taking time to report this issue. Are you able to reproduce this error? If yes please share the steps to reproduce.

Hi  @JoshuaLuckers, in admin dashboard (2.7+) I got this problem when, I did not have a working connector, i.e. the folder "connectors" was blocked by rights (403) maybe the problem is related?

**Comment by alroniks** [comment] 2021-04-10 20:38
Sorry, but I tend to close it dues to the age of the issue, as well because of lack of steps to reproduce and detailed description, also no feedback for a long time. Feel free to reopen, if needed.

**Closed as completed by alroniks** 2021-04-10 20:38 UTC
Labels: blocked
