### ISSUE TITLE
Delete user database error

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12661] opened 2015-09-22 06:54 UTC
### Summary
Deleting a user in the Manager interface causes a database error

### Step to reproduce
Delete a user in the Manager interface

### Observed behavior
User is deleted but following error is generated

```
[2015-09-22 06:29:34] (ERROR @ /connectors/index.php) Could not get table class for class: modAccess
[2015-09-22 06:29:34] (ERROR @ /connectors/index.php) Could not get table name for class: modAccess
[2015-09-22 06:29:34] (ERROR @ /connectors/index.php) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `modAccess` WHERE `modAccess`.`principal` = 7' at line 1
)
```

### Expected behavior
Delete user without errors.

### Environment
Revolution 2.4.0 - MODX Cloud, SkyToaster and localhost installations.

**Comment by pixelchutes** [comment] 2015-09-22 15:17
Duplicate of #11276

**Closed by pixelchutes** 2015-09-22 15:17 UTC

**Comment by sottwell** [comment] 2015-09-22 15:19
I thought I remembered something about it, but couldn't find anything.
