### ISSUE TITLE
Sticking headers in the top of left side

### ISSUE THREAD

**Issue by LitvK** [modxcms/revolution#13074] opened 2016-07-18 21:43 UTC
It would be great to have possibility to stick header with "Resources", "Elements", "Files" at the top of the left side of admin panel. Too often I scroll down left side with Resources for example and need to take a look at Elements. I need to scroll back all the panel for this, change type of the panel, then scroll again to the middle, then scroll again to the top, then restore type of the panel back, then scroll down to previous place.

Too many annoying scrolls. :(

**Comment by achterbahn** [comment] 2017-01-07 11:20
Is this kind of a duplicate to the discussion in #10703 ?

**Comment by OptimusCrime** [comment] 2017-02-10 19:14
Closing as duplicate of #10703. It is older and has more details.

@modxbot close

**Closed by OptimusCrime** 2017-02-10 19:14 UTC
