### ISSUE TITLE
Error while editing resource, if the resource name contains "" (quotation marks)

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#13696] opened 2017-11-16 12:42 UTC
MODX Revo 2.6
If the resource name contains "" (quotation marks), then after saving the resource it can not be changed - the resource editing form does not open.
You can change the resource only in the form resource quick update.

**Comment by rthrash** [comment] 2017-11-16 13:02
Duplicate of #13695

**Comment by sottwell** [comment] 2017-11-16 13:03
Fixed already; see #13669

**Closed by rthrash** 2017-11-16 13:02 UTC
