### ISSUE TITLE
FileManager doesn't display csv files anymore

### ISSUE THREAD

**Issue by squarou** [modxcms/revolution#13702] opened 2017-11-20 15:59 UTC
### Summary
Since 2.6.0, I can see csv anymore, neither in the tree or in the Media views

### Step to reproduce
Upgrade to 2.6.0

### Observed behavior
Files with .csv aren't visible

### Expected behavior
Files with .csv should be visible as they're allowed file type in the media source and upload_file in the general settings

### Environment
Modx 2.6.0, php 7.1, apache

**Comment by mrhaw** [comment] 2017-11-20 16:41
Maybe related to https://github.com/modxcms/revolution/pull/13096

**Comment by labr1005** [comment] 2017-11-20 20:31
I can't reproduce this neither on an upgrade nor on a fresh install.

Do they show up when you clear allowedFileTypes for that media source?

**Comment by beko1997** [comment] 2017-11-20 21:16
I can confirm that 'allowedFileTypes' is related to this issue (as @labr1005 pointed out). The csv file will not be shown when 'allowedFileTypes' is filled. After clearing the option the csv file is visible again. 

**Steps to reproduce:**
- Add a .csv file to the location of a media source.
- Confirm that it is visible for the media source.
- Set 'allowedFileTypes' for that media source to 'csv'.
- The csv file is not visible anymore.

**Comment by squarou** [comment] 2017-11-30 14:27
OK my bad : space in string seems to create some trouble.

Tried this allowedFileType in the media source :
`doc,gif,jpg,pdf,png,txt,zip,gz,bz2,xls,psd,css,tgz,odt,tpl,rtf,xml,docx,xlsx,ppt,tpl,php,thml,js,css, csv, php, json`
Not OK. 

With:
`doc,gif,jpg,pdf,png,txt,zip,gz,bz2,xls,psd,css,tgz,odt,tpl,rtf,xml,docx,xlsx,ppt,tpl,php,thml,js,css,csv,php,json`

OK.

I'm closing. Thanks.

**Comment by Jako** [comment] 2017-11-30 20:37
Maybe that could be fixed with a trim.

**Comment by Mark-H** [comment] 2018-01-29 23:23
Per #13721 this is fixed in 2.7.

**Closed by Mark-H** 2018-01-29 23:23 UTC
Labels: area-core, bug, priority-3-low
