### ISSUE TITLE
Cannot download file from Amazon S3 bucket in manager.

### ISSUE THREAD

**Issue by suasti** [modxcms/revolution#13061] opened 2016-07-05 09:09 UTC
### Summary

I created Amazon S3 bucket, uploaded files, created in manager media source Amazon S3 without any problems. But when I want to download my file http://nimb.ws/PlTQ0W I obtain an error 500. 

I think it happend because the source refers to the property "fileHandler"
path to file: core/model/modx/processors/browser/file/download.class.php

```
public function download() {
        $fileobj = $this->source->fileHandler->make($this->source->getBasePath() . $this->getProperty('file'));

        $fileobj->download();
    }
```

but mods3mediasource.class.php does't have this property 
### Environment

MODX Revolution 2.4.2-pl, apache 2.4 on Ubuntu 14.04.3 LTS.
### Why is it needed?

Because it doesn't work otherwise :)

**Comment by rthrash** [comment] 2016-07-07 13:24
Does your bucket have a period in its name? If so that is a known issue that has been fixed in later versions.

**Comment by rthrash** [comment] 2016-07-07 13:24
Related: #12730

**Comment by suasti** [comment] 2016-07-07 13:41
No it doesn't. It has a dash, like "blabla-demo" But the error is the same as described in  #12730 (Sorry, I didn't see this issue). But a fact is a fact, the download doesn't work.

**Comment by Mark-H** [comment] 2016-07-07 13:44
That `$this->source->fileHandler` sure looks like the culprit... that should be media source agnostic, whereas fileHandler is specific to the file media source :/

**Comment by Mark-H** [comment] 2017-02-09 18:46
Closing as dupe of #12730

**Closed by Mark-H** 2017-02-09 18:46 UTC
