### ISSUE TITLE
Package installer mixes up packages during updates

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#13569] opened 2017-08-01 19:29 UTC
The package installer (upgrade) sometimes installs a different package from the package that was clicked on.

Visit package management, upgrade a package then attempt to upgrade another package.  One will upgrade fine but the next one you do sometimes will download the correct package but then install a different package which shows in the console.  After installing is completed the intended package shows as not installed.  Only occurs when the package manager page is not refreshed, if you reload the page between upgrades it does not occur.

Initially I thought it was packages from the same developer but I just attempted to upgrade pdoTools after updating MIGX and it reinstalled MIGX and set PDOtools to show as not installed.  Also experienced with Batcher and Formit installs.

Effects Multiple 2.5.7 MODX installations on cPanel server running PHP 5.6.

**Comment by Mark-H** [comment] 2017-08-01 19:33
I believe this is a duplicate of #13169, which was fixed in #13557 which will be fixed in 2.5.8.

**Closed by Mark-H** 2017-08-01 19:33 UTC
