### ISSUE TITLE
MODX 2.7.0 is modifying urls

### ISSUE THREAD

**Issue by AlexandreInsua** [modxcms/revolution#14404] opened 2019-02-18 15:55 UTC
### Summary
The system modifies the URLs. Adds a resource name to all URLs.

### The behavior observed
I have a simple application that consists of an index, a login and a private panel.
The problem appeared when I upgraded to version 2.7.0. The application modifies the url when I'm connected to the private panel.
For example, if the url to an avatar is "_myapp.local/assets/component/myapp/images/site/avatar.png_" the system is changing the URL to "_myapp.com**/controlpanel/**assets/component/myapp/images/site/avatar.png_ ".
I remark the change with **bold** font. 

This also happens with css and js scripts in style style, like this:
"_myapp.local/assets/component/myapp/css/boostrap.css_" changes to "_myapp.local/**controlpanel**/assets/ component/myapp/css/boostrap.css_"
e
"_myapp.local/assets/component/myapp/js/jquery-1.11.0.js_" changes to "_myapp.local/**controlpanel**/assets/component/myapp/js/jquery-1.11.0.js_"
Notice that the system is adding the name of the control panel, whose url is "_myapp.local/controlpanel/_"
to the url of the asset.

This prevents the loading of features, such as images, stylesheets, and js scripts, so the application does not work.
As far as I was able to investigate, it is making the requests get and post to urls that do not exist and it breaks the operation.
These URL are not stored in the database but only rendered in the browser. 
The _**Base href**_ is _http://myapp.local/_.

### Expected behavior
The expected behavior is that you direct the petitions to the right place.

### Environment
I'm checking the application locally, so I'm using MODX 2.7.0, Wampserver 3.1.3 64-bit (Apache 2.4.33, MySQL 5.7.21, PHP 7.2.4) and Chrome 72.0.3626.109 64-bit.
I'm using relative urls.

**Comment by Mark-H** [comment] 2019-02-18 16:00
Are these URLs stored with /controlpanel/ in the database or only rendered as such in the brower? Are you using relative urls? Base href? Adding these URLs in a rich text editor?

**Comment by AlexandreInsua** [comment] 2019-02-18 22:29
Thanks, @Mark-H, I edit the issue. The URLs are not stored in the database. I'm using relative urls. The base href is http://myapp.local/.  I put the change in rich format in order to be clean.

**Comment by JoshuaLuckers** [comment] 2019-02-20 20:12
Is the private panel something you made yourself or are you referring to the manager?

**Comment by AlexandreInsua** [comment] 2019-02-22 13:22
@JoshuaLuckers the private panel is made by me, it's not the manager.

**Comment by JoshuaLuckers** [comment] 2019-02-22 15:50
How do you generate the URLs?

**Comment by OptimusCrime** [comment] 2019-02-25 15:27
I can not understand how this is caused by 2.7.0 alone.

**Comment by JoshuaLuckers** [comment] 2019-02-25 19:11
I'm closing this issue. Feel free to open a new issue providing more info to re-create this issue.

**Closed as completed by JoshuaLuckers** 2019-02-25 19:11 UTC
