### ISSUE TITLE
Not upload files .jps in 50% of cases

### ISSUE THREAD

**Issue by themaltsev** [modxcms/revolution#16141] opened 2022-04-12 22:12 UTC
### Summary

Not upload files .jps in 50% of cases

![Desktop Screenshot 2022 04 13 - 00 53 15 58](https://user-images.githubusercontent.com/47543995/163063277-fbed50a2-8f61-40a6-a092-aa20a5d924b7.png)

### Environment
MODX version 3.0.0. , nginx and version, mysql mysql  Ver 15.1 Distrib 10.1.45-MariaDB, browser, etc. Any relevant information.

**Comment by themaltsev** [comment] 2022-04-12 22:13
[2022-04-13 00:47:55] (ERROR @ /var/www/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 1267) Problem getting service fileHandler, instance of class modFileHandler, from path

**Comment by JoshuaLuckers** [comment] 2022-04-16 07:53
@themaltsev I'm unable to reproduce this issue. Can you provide the steps to reproduce the issue? Does it happen to certain files only? What's the file size?

**Comment by halftrainedharry** [comment] 2022-04-16 09:31
The error message in the printscreen you posted ("Этот файл не является обычным файлом и не может быть удален."). Does it show when the upload fails?

This error message ("The file is not a regular file and cannot be deleted." in english) is only used in the `renameObject()` function of the media source. Why is the file renamed?

Are there any plugins from installed extras/packages that run on the events "OnFileManagerBeforeUpload" or "OnFileManagerUpload"?

**Comment by themaltsev** [comment] 2022-04-17 10:04
Data base was defended type utf8 unicode vs utf8 general ci, i make changes and all become work

**Comment by JoshuaLuckers** [comment] 2022-04-18 12:20
@themaltsev did that solve your issue? If yes, feel free to close this issue. Thanks for taking time to help improve MODX!

**Closed as completed** 2022-05-17 07:10 UTC
Labels: bug

**Comment by MisterPaddo** [comment] 2022-10-14 09:42
For people who are still running in this problem: FileSluggy seems to cause these error messages as well. I uninstalled it since MODX 3 sanitises the filenames when uploading.
