### ISSUE TITLE
users management

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#13466] opened 2017-06-05 17:30 UTC
I think this should be with prior in one of the next versions.

When you have for example a site with a login for visitors you want to give your client, who has editor permissions in the backend, access to the user management in the backend. The big problem with this is that the user also can manage the other profiles like the admin and/or he can give himself sudo-rights. I always restrict in what the editor can do in the backend, some stuff (like elements) are only for the administrator. But I don't understand why the user management is all or nothing. It should be possible to restrict to see f.e. only users from a certain group. At least make sure the admin-account (superuser) is kept save!

With the upcoming new Commerce and other login-stuff this should be looked at in the near future.

**Comment by pixelchutes** [comment] 2017-06-05 21:07
Thank you for opening this. I've opted to close this as a duplicate of #11208. Please continue all relevant discussion there.

**Closed by pixelchutes** 2017-06-05 21:07 UTC
