### ISSUE TITLE
User country

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#12189] opened 2014-12-01 10:07 UTC
On the Country field of a User, typing in a country not within the select list will result in error:

Code: 200 OK
{"success":false,"message":"","total":0,"data":[],"object":[]}

Same erre message results for a typo. 

It's not an error as such but a more descriptive message could be displayed.

**Comment by rtripault** [comment] 2015-01-11 15:57
Confirmed, because of

https://github.com/modxcms/revolution/blob/master/core/model/modx/processors/system/country/getlist.class.php#L15

We should either : 

* pass a message to the `failure()`
* just return an empty array using `$this->outputArray(array()))` to prevent the error display

**Comment by OptimusCrime** [comment] 2015-01-12 09:09
I can take a look at this :)

**Comment by Flowan** [comment] 2017-07-07 16:49
Confirmed this works in 2.5.x #modxbughunt

**Comment by sonicpunk** [comment] 2017-07-07 18:23
#modxbughunt #1point to @Flowan

**Comment by gpsietzema** [comment] 2017-07-07 18:23
#modxbughunt #1point to @Flowan

**Comment by OptimusCrime** [comment] 2017-07-07 19:22
@rtripault Arrrgg, why did you not post a link with the latest commit? I am unable to find the correct line in the master branch right now. Do you know what happened with this?

**Comment by rtripault** [comment] 2017-07-07 19:39
I guess the code chunk is no more. FWIW i also wasn't able to reproduce the issue

**Comment by OptimusCrime** [comment] 2017-07-07 21:46
Awesome. Then we'll close this.

@modxbot close

**Closed by OptimusCrime** 2017-07-07 21:46 UTC
Labels: area-core, state/accepting-pull-request, state/confirmed
