### ISSUE TITLE
New dependencies installation fails for some Extras (MIGX, SEO tab, SEO Pro)

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/revolution#12666] opened 2015-09-23 08:00 UTC
When using the new dependencies feature in MODX 2.4.0-pl to install MIGX, SEO Pro or SEO Tab, The extra's get listed but when you click install they do not get installed.

The only way to install them is via the 'normal' way, after this they get listed correctly as installed under dependencies tab.

I tried different names, but no go for these three extras. Others do work fine...

**Comment by joeke** [comment] 2016-01-06 22:24
I've tested this with Modx 2.4.2 and I've got the same issue. I've dug into the problem and the issue seems to be with spaces in the dependency package name. See issue #55 at the SEO Tab repo for more info: https://github.com/Sterc/SEOTab/issues/55

**Comment by joeke** [comment] 2016-10-10 12:27
@opengeek I've had a talk with you (on Slack) about this, and as you pointed it seems to be an issue in the modx extras repository when using dependencies with a space in the package name.. Are there any plans / ideas on fixing this? Would love to help out, but I don't think the Extras repository code is publicly available, is it?

**Comment by Mark-H** [comment] 2017-02-09 19:00
Closing as this likely needs to be resolved in the provider/extras site.

**Comment by opengeek** [comment] 2017-02-09 21:39
Package names never have spaces in them; if you submit them that way, they are cleansed. They have to match the transport filename. I'm a little confused as to what the problem really is here.

**Comment by opengeek** [comment] 2017-02-09 21:50
@joeke I recall the conversation but, unfortunately, I don't recall the conversation details. If you can provide more details here that might help. But again, packages should *never* contain a space in the name. They *should* always be lowercase and not contain a dash character, just like the transport filename rules.

**Comment by joeke** [comment] 2017-02-10 09:51
@opengeek I've managed to reproduce the issue, here are the steps:
1. Build new transport zip for any extra, but add SEO Pro to 'requires' array (key: 'SEO Pro', value: '>=1.0.4'). (please note that I use the package name here, because that's how the `checkDependencies` and `checkDownloadedDependencies` functions in `modtransportpackage.class.php` handle the dependencies.)
2. Install the newly created transport zip in a clean modx install (at least without SEO Pro installed).
3. The installer screen shows the Dependencies tab, and it shows SEO Pro, with a download button.
4. Click on the download button, the request fails with following error message:
`{"success":true,"message":"Could not download and create transport package with signature: ","total":0,"data":[],"object":[]}`.

My request URL is 
`/connectors/index.php?_dc=1486719097990&action=workspace%2Fpackages%2Fdependency%2Fdownload&signature=stercseo-2.0.0-alpha&name=SEO%20Pro&constraints=%3E%3D1.0.4&HTTP_MODAUTH=modx587f83ab408533.79723877_1589d854ac0eda2.61248522`

Note that when I install SEO Pro before installing my created transport zip (in my clean modx install), the installation works fine. So the issue only occurs when using dependencies that are not installed.

**Comment by Jako** [comment] 2017-02-10 09:59
Could you try the package name (seopro) instead of the extra name (SEO Pro)?

**Comment by joeke** [comment] 2017-02-10 10:11
@Jako No that won't work. The checkDependencies function uses the `package_name`, which in this case is 'SEO Pro' (see screenshot).
<img width="420" alt="screen shot 2017-02-10 at 11 08 38" src="https://cloud.githubusercontent.com/assets/2332231/22822839/5265ddca-ef81-11e6-9c66-7838dba70bd2.png">

The checkDependencies function is here: https://github.com/modxcms/revolution/blob/2.x/core/model/modx/transport/modtransportpackage.class.php#L468

**Comment by Jako** [comment] 2017-02-10 10:39
Stupid design decision then.

The query should be expanded with an `or` condition that checks the string before the first `-` sign in the signature column in that table.

**Comment by joeke** [comment] 2017-02-10 10:58
@Jako I don't think the problem is with the checkDepencies functions, I believe those are only used when building the package.. and that works fine. I think the problem is somewhere in the dependency download class https://github.com/modxcms/revolution/blob/2.x/core/model/modx/processors/workspace/packages/dependency/download.class.php
or in the extras repository.

**Comment by Jako** [comment] 2019-01-11 21:43
It was maybe a combination of several issues: 
- The modTransportProvider findResolution method checked only the current Provider because of a bug #14260. If you tested the dependency download with an own provider (or maybe with a local downloaded package - have not checked that), it won't get further and can't download the dependency package.
- The package could only be downloaded from the MODX Extras package provider with the signature before the version number. After that it is successful downloaded, the package is searched in the `package_name` column as you stated above. Both values are different i.e. `SEO Pro` vs `seopro`. That has to be fixed in the where clause in https://github.com/modxcms/revolution/blob/2.x/core/model/modx/transport/modtransportpackage.class.php#L475

**Comment by alroniks** [comment] 2019-02-13 16:18
@Jako Did you fixed described issue or some point still actual? If all fixed could close the issue as your confirmation?

**Comment by Jako** [comment] 2019-02-13 20:22
It is fixed with that query change.

**Closed** 2019-02-13 20:22 UTC
