### ISSUE TITLE
[3.x] Unable to download any extras 

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15872] opened 2021-10-28 07:38 UTC
### Summary
Unable to download any extras in latest MODX 3 git.

![Screenshot 2021-10-28 at 15-26-50 Package Management MODX Revolution](https://user-images.githubusercontent.com/5160368/139207634-25ef66b9-ab3a-46dc-9552-8cc0fe26d1ff.png)

### Step to reproduce
Install MODX 3 via git and attempt to download an extra via the package manager.

### Observed behavior
Error message:
```
Could not download and create transport package with signature: [any package name here]
```

The issue appears to be the `location` url in the `$locationArgs` array here:
https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Transport/modTransportProvider.php#L305

The URL is prefixed with `http://` instead of `https://` and causes the `downloadUrl()` method to return an empty string.

If I add `$locationArgs['location'] = str_replace( 'http://', 'https://', $locationArgs['location']);` to line 306 it works as it's now a `https://` url.

### Expected behavior
It should download.

### Environment
MODX 3 from git, nginx, mysql 8, PHP 8

**Comment by opengeek** [comment] 2021-10-28 14:23
I am unable to reproduce this.

**Comment by opengeek** [comment] 2021-10-28 14:25
I can, however, see that the location being requested is indeed using HTTP instead of HTTPS, which is not correct.

**Comment by opengeek** [comment] 2021-10-28 14:29
Actually—this has nothing to do with the CMS. This is how the URLs are returned by the provider and this is the same as it has always been.

**Comment by Mark-H** [comment] 2021-10-28 14:30
It's working fine here as well, but we have received a bunch of tickets over the past week or two at modmore about people having trouble downloading packages which also seems to be due to http instead of https. For the life of me I've not been able to find out why that's happening. Maybe the transferPackage method (which was untouched in 3.x) has some issue that cause it to revert to http somehow?

**Comment by opengeek** [comment] 2021-10-28 14:31
> It's working fine here as well, but we have received a bunch of tickets over the past week or two at modmore about people having trouble downloading packages which also seems to be due to http instead of https. For the life of me I've not been able to find out why that's happening. Maybe the transferPackage method (which was untouched in 3.x) has some issue that cause it to revert to http somehow?

Nope. This has always returned an HTTP URL, which then gets converted to the https URL for the actual file from S3.

**Comment by opengeek** [comment] 2021-10-28 14:32
I'm guessing this must have something to do with the certificate issues recently…

**Comment by opengeek** [comment] 2021-10-28 15:26
Actually, this should have nothing to do with certs. I am going to modify the provider to just send https for those links and we'll see if the world ends. 😅

**Comment by Jako** [comment] 2021-10-28 15:28
Post requests can't be redirected. Maybe that's the issue.

**Comment by opengeek** [comment] 2021-10-28 15:29
There is no redirection involved.

**Comment by opengeek** [comment] 2021-10-28 15:29
My guess is some networks are simply preventing HTTP traffic.

**Comment by Jako** [comment] 2021-10-28 15:36
Rewrite rules to https are technically a redirect to https. So if you removed or changed the http access to the provider lately this will be the cause of that and not the alpha3.

**Comment by opengeek** [comment] 2021-10-28 15:38
> Rewrite rules to https are technically a redirect to https. So if you removed or changed the http access to the provider lately this will be the cause of that and not the alpha3.

Nothing has changed at the provider. There is no rewrite or redirect involved. These old http download links proxy_pass the request/response and return the AWS link. End of story.

**Comment by opengeek** [comment] 2021-10-28 15:43
@muzzwood — I have updated the provider to return HTTPS instead of HTTP URLs. Can you confirm this resolves your issue?

**Comment by valokammi** [comment] 2021-10-28 16:41
Confirm that https causes blank installer download page in local (Laragon) fresh (trad) install. Switch to http download page ok! And when trying to save with https got warning below url field "This Provider could not be verified, and therefore cannot be used as a MODX Provider. Please check the service URL and try again." and it don`t save if https is value.

Attached error log file
[errorlog.txt](https://github.com/modxcms/revolution/files/7435902/errorlog.txt)
.

**Comment by opengeek** [comment] 2021-10-28 16:43
> Confirm that https causes blank installer download page in local (Laragon) fresh (trad) install. Switch to http download page ok! And when trying to save with https got warning below url field "This Provider could not be verified, and therefore cannot be used as a MODX Provider. Please check the service URL and try again." and it don`t save if https is value.
> 
> Attached error log file [errorlog.txt](https://github.com/modxcms/revolution/files/7435902/errorlog.txt) .

The provider has been https by default since 2018. This is not about the provider, just the download URL. It sounds like your local environment needs some updates. What version of PHP? What version of CURL?

**Comment by muzzwood** [comment] 2021-10-29 01:20
Hi @opengeek, thanks for looking into this so quickly. I can confirm it's now working.
The odd thing is though, it was working fine with v2.8.3 - I checked that after it failed in v3 to make sure it wasn't a provider/network issue. 🤔

**Comment by Jako** [comment] 2021-10-29 07:57
2.8.3 works with the old modRest transport, there was a switch from modRest to guzzle v1 before alpha 3 and the alpha 3 uses the new guzzle v2 http factory (https://github.com/modxcms/revolution/pull/15856). Maybe there was some change between v1 and v2.

**Comment by smg6511** [comment] 2021-10-29 17:59
I had this same problem recently and it turned out that an update to my local dev environment (MAMP Pro) fixed the issue for me. Oddly enough, It also worked to change `https` to `http` in the provider URL setting (something I tried on a whim before updating MAMP). It seems that there's something about the newer guzzle and some dev environments not playing nice that might need attention.

**Comment by opengeek** [comment] 2021-10-29 18:40
> I had this same problem recently and it turned out that an update to my local dev environment (MAMP Pro) fixed the issue for me. Oddly enough, It also worked to change `https` to `http` in the provider URL setting (something I tried on a whim before updating MAMP). It seems that there's something about the newer guzzle and some dev environments not playing nice that might need attention.

FWIW, that was a slightly different issue dealing with certificate chains, which we solved by serving a different one from the provider domain. The problem here is ONLY with the download link, which, until this report, was always returned as HTTP rather than HTTPS. Now it is always returned as HTTPS. This is regardless of how you access the provider itself.

**Comment by JoshuaLuckers** [comment] 2021-10-31 09:37
@opengeek can we close this issue or do we still need to take any action?

**Closed as completed** 2022-01-06 11:37 UTC
Labels: bug
