### ISSUE TITLE
hidemenu label doesn't change using Form Customization. 

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/revolution#13063] opened 2016-07-05 15:04 UTC
### Summary
`hidemenu` label doesn't change using Form Customization. 

### Step to reproduce

1. Create Form Customization Rule Set for Create Resource or Update Resource
2. Change the label value for `hidemenu`
3. Go create or update (depending on which you picked in step 1)
4. Note the label is still set for the default lexicon value of *Hide From Menus*

### Observed behavior
The `hidemenu` label is still set for the default lexicon value of *Hide From Menus*

### Expected behavior
Label should reflect updated Form Customization setting

### Environment
Revo 2.5.0 nginx, percona. MODX Cloud

**Comment by Mark-H** [comment] 2016-07-05 15:19
Duplicate of #13053 and #12890 and fixed in #13025 in 2.5.1.

**Closed by Mark-H** 2016-07-05 15:19 UTC

**Comment by theboxer** [comment] 2016-07-05 15:22
@Mark-H Changelog entry is missing for this fix

**Comment by jaygilmore** [comment] 2016-07-05 19:54
Bah. I searched issues but I must have left the filters on. Thanks.
