### ISSUE TITLE
Empty pakage history in manager

### ISSUE THREAD

**Issue by fortunto2** [modxcms/revolution#13181] opened 2016-11-17 17:24 UTC
### Summary

After upgrade 2.3.3 to 2.5.2 empty pakage history 

### Observed behavior
```
[2016-11-17 20:15:10] (ERROR @ /var/www/******/www/core/xpdo/om/xpdoobject.class.php : 240) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ASC, modTransportPackage.release_index DESC LIMIT 20' at line 1
)

```
### Expected behavior
No package version history   list - is empty

### Environment
modx 2.5.2, php5.6-fpm

![2016-11-17 22-23-23](https://cloud.githubusercontent.com/assets/1236751/20399879/7f752b22-ad14-11e6-9984-ea8dd27d1d38.png)

**Comment by Mark-H** [comment] 2016-11-17 17:26
Duplicate of #13179

**Closed by Mark-H** 2016-11-17 17:26 UTC
