### ISSUE TITLE
Error creating/saving resource in Firefox

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#14603] opened 2019-06-11 09:22 UTC
### Summary
Updated modx from 2.6.5 to 2.7.1. When you create/edit resources through the firefox browser, the page freezes and only shows " saving...". If you refresh the page, you can see that the changes were successfully saved.

### Step to reproduce
Create a new resource, click save

### Observed behavior
The page hangs with the inscription "save...". An error is displayed in the browser console:
`SyntaxError: missing ) in parenthetical                      ext-all.js:1:75`

### Expected behavior
When you click save, the page should be saved and available for further editing

### Environment
MODX version: 2.7.1
browser: firefox

**Comment by JoshuaLuckers** [comment] 2019-06-11 12:26
Thanks for taking time to report this issue.

Does it help if you clear the browser cache (to refresh the cached JS files)?

**Comment by alexsoin** [comment] 2019-06-12 19:33
Cleared the cache, did not help. Checked on several devices the problem is actual. Also now deployed pure modx 2.7.1 on modhost hosting, the same error is issued.

OS Windows 10, firefox 67.0.2 64x

**Comment by Ruslan-Aleev** [comment] 2019-06-12 19:54
I can not reproduce this error.
MODX 2.7.1, OS Windows 7, Firefox 67.0.2 64x.

Maybe some component conflicts with MODX 2.7.1?

**Comment by JoshuaLuckers** [comment] 2019-06-13 05:13
Do you have any browser extensions installed?

**Comment by alexsoin** [comment] 2019-06-13 05:25
Yes! I've found it. This error was caused by the addition of [SimpleTranslate](https://addons.mozilla.org/ru/firefox/addon/simple-translate/), after its shutdown everything began to work correctly.

**Comment by JoshuaLuckers** [comment] 2019-06-13 10:32
Thanks for sharing the cause and solution for the problem.

Because this is an issue caused by a third party browser extension I'm closing this issue.

It would be great to [create an issue](https://github.com/sienori/simple-translate/issues) for this problem over at the [SimpleTranslate repository](https://github.com/sienori/simple-translate/).

**Closed as completed by JoshuaLuckers** 2019-06-13 10:32 UTC
