### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by konstantinj** [modxcms/revolution#12242] opened 2015-01-02 15:28 UTC
Hi there,

> PHP Warning:  PDOStatement::execute(): SQLSTATE[HY000]: General                                                                                                                                                        error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8_general_ci,IMPLICIT) for operation '=' in /var/www/public/core/model/modx/modcachemanager.class.php on line 450

I see this error all the time, basically on every request. Have changed all tables to "utf8_unicode_ci" but still errors. Any ideas?

**Comment by OptimusCrime** [comment] 2015-01-05 00:40
I am pretty sure this is a problem with the system/setup, not Modx itself. The exception comes from PDO, so not directly caused by Modx the way I see it.

**Comment by rtripault** [comment] 2015-01-05 10:42
Agreed here, seems like an environment issue (according to Google search results, most likely due to different tables collations), so i'm closing this.

@konstantinj since you wrote you changed the collations (and still encounter the issue), any chance you cached the DB ? (not sure if that may be related, but might be a lead)

**Closed by rtripault** 2015-01-05 10:42 UTC
