### ISSUE TITLE
New Documents not shown in Resource Browser

### ISSUE THREAD

**Issue by gocedoko** [modxcms/revolution#13172] opened 2016-11-10 09:30 UTC
### Summary
Newly created Documents are not shown in the Resource Browser. They exist however and can be opened in browser.

### Step to reproduce
1) Fresh Modx Installation on WAMP with MS SQL.
2) Create and save a new Document.

### Observed behavior
Document is not shown in the resource browser menu on the left.

### Expected behavior
Document should be immediately seen in the resource browser.

### Environment
Modx 2.5.1 installed on WAMP, Apache 2.4.23, PHP 7.0.10, MS SQL Server 2012 and ODBC Driver 11
pdo_sqlsrv support: enabled,  ExtensionVer: 4.0.8629.2

**Comment by gocedoko** [comment] 2016-11-10 09:32
This is the error from the log:
![image](https://cloud.githubusercontent.com/assets/11044633/20171431/e4fd074c-a730-11e6-9d60-b1420b6ad16f.png)

**Comment by gocedoko** [comment] 2016-11-10 09:34
I have solved this by editing core\model\modx\processors\resource\getnodes.class.php
Line 169: $c->leftJoin('modResource', 'Child', array('modResource.id = Child.parent AND Child.show_in_tree = true'));
to
$c->leftJoin('modResource', 'Child', array('modResource.id = Child.parent AND Child.show_in_tree = 1'));

Seems like a problem with the MSSQL sintax for the reserved word True, I don't know if it's due to the MSSQL driver, and maybe it should be corrected on other places in the code.

**Comment by gocedoko** [comment] 2016-11-10 13:14
And another small MS SQL bug
in file core\model\modx\moduser.class.php
replace line 519
`$query->innerJoin('modUserGroup', 'UserGroup', array('UserGroup.id = modUserGroupSetting.group'));`
with
`$query->innerJoin('modUserGroup', 'UserGroup', array('UserGroup.id = modUserGroupSetting.[group]'));`

**Comment by pixelchutes** [comment] 2016-11-10 13:55
The first issie is addressed by #13162 and is waiting to be merged.

**Comment by Jako** [comment] 2016-11-10 20:22
@gocedoko Could you check if the following code works?
```
$query->innerJoin('modUserGroup', 'UserGroup', array('`UserGroup`.`id` = `modUserGroupSetting`.`group`'));`
```

Then the innerJoin method could be extended and we don't have to check the whole MODX code for those missing escapes.

**Comment by gocedoko** [comment] 2016-11-11 08:43
@Jako  unfortunately not working.
`[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near '`'`

Probably the innerJoin should insert braces [ ].

This is the erroneous SQL query that is generated (it has braces on other places anyways)
There are backticks in the sql, but I don't know how to escape them here in the comnment :)

<code>SELECT [modUserGroupSetting].[group] AS [modUserGroupSetting_group], [modUserGroupSetting].[key] AS [modUserGroupSetting_key], [modUserGroupSetting].[value] AS [modUserGroupSetting_value], [modUserGroupSetting].[xtype] AS [modUserGroupSetting_xtype], [modUserGroupSetting].[namespace] AS [modUserGroupSetting_namespace], [modUserGroupSetting].[area] AS [modUserGroupSetting_area], [modUserGroupSetting].[editedon] AS [modUserGroupSetting_editedon] FROM [modx_user_group_settings] AS [modUserGroupSetting] JOIN [modx_membergroup_names] AS [UserGroup] ON ` UserGroup ` . ` id ` = `modUserGroupSetting`.`group` JOIN [modx_member_groups] AS [Member] ON  ( [Member].[member] = ? AND UserGroup.id = Member.user_group )  ORDER BY UserGroup.rank DESC, Member.rank DESC </code>

**Comment by Jako** [comment] 2016-11-11 09:49
Ok, I never worked with MS SQL. It uses a different escape sign than MySQL. 

Adding a [] around the group field name is a very special solution for MS SQL. It should be added more general in the innerJoin method of MS SQL driver. But there seems not to be one in https://github.com/modxcms/revolution/tree/2.x/core/xpdo/om

**Comment by OptimusCrime** [comment] 2016-12-03 02:49
Is this a duplicate of #12845? I am not sure what the last queries were related to, is it the same? Can this be closed?

**Comment by Jako** [comment] 2016-12-03 11:53
The [second issue](https://github.com/modxcms/revolution/issues/13172#issuecomment-259686786) of @gocedoko is not a duplicate of #12845.

@gocedoko Maybe you should open another issue next time.

**Comment by JoshuaLuckers** [comment] 2019-05-05 10:45
> The [second issue](https://github.com/modxcms/revolution/issues/13172#issuecomment-259686786) of @gocedoko is not a duplicate of #12845.

If the second issue is still relevant please open a new issue for it. Thanks!

**Closed by JoshuaLuckers** 2019-05-05 10:45 UTC
