### ISSUE TITLE
refresh of resource tree inserts at wrong position

### ISSUE THREAD

**Issue by Gallenkamp** [modxcms/revolution#12346] opened 2015-02-08 09:49 UTC
I just added a category to my site. rightclick on a snippet, "add category here", enter name. Then -> tree is refreshing the current item, inserting the entire tree (all snippets).
See attached image - double entries present.
![refresh](https://cloud.githubusercontent.com/assets/2450164/6096088/2824d5c2-af80-11e4-83f2-3e9281e9f3fd.png)

**Comment by OptimusCrime** [comment] 2015-02-08 22:17
What MODx version? And what browser? This might be a random fuckup that is nearly impossible to reproduce.

**Comment by Gallenkamp** [comment] 2015-02-09 10:43
FireFox 35.0.1, MODX 2.3.3-pl traditional

**Comment by frogabog** [comment] 2015-02-11 03:28
I've seen this before, at least once if not more.  Recently, about 4 weeks ago actually in I believe that site was running 2.3.2-pl traditional.  The site did have database collation issues, which have been repaired using Bob Ray's CDC script but I haven't had occasion to add categories since then.

**Comment by OptimusCrime** [comment] 2017-03-03 15:56
I am not able to reproduce this myself. If this was a widespread problem there would be more reports about this problem. I'm closing this due to age and lack of further information we can investigate on.

If this is still an issue, or you can shed some light on what happens, feel free to comment or reopen this issue.

@modxbot close

#modxbughunt

**Closed by OptimusCrime** 2017-03-03 15:56 UTC
