### ISSUE TITLE
Remove locks on open resource does not change manager UI

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#12028] opened 2014-10-08 14:46 UTC
The "remove locks" does not change the state of the currently open page if it is locked. If you try to edit a page which is locked, unfortunately you can do so (see #11929), but the save button is disabled and there is the only information for you that this resource is locked ("locked by...."). Fine, you may remove the locks from the menu, but that does not change the state of your open manager page - it will still show "locked by..." and you cannot save. So your only chance is to reload the whole page (and loose all your changes). 
The user interface _should_ change if you remove lock on the current, because that is what you want to do in that moment.: to remove the lock and keep editing the resource....

**Comment by sebastian-marinescu** [comment] 2016-02-26 12:29
:+1: 

I just had that issue yesterday, but I was lucky enough I hadn't changed too much. 
My end-users might not be so lucky, so this has somehow priority in my opinion, because it is unexpected behaviour and also it is hindering your creative freedom...

**Comment by Oetzie** [comment] 2017-03-03 13:03
I'm going to try and fix this today. #modxbughunt

**Comment by Mark-H** [comment] 2017-06-15 20:52
Fixed in 2.6

**Closed by Mark-H** 2017-06-15 20:52 UTC
Labels: area-ux/ui
