### ISSUE TITLE
No preview for .webp, .jpg, and .jpeg image files in 3.0.2

### ISSUE THREAD

**Issue by PeterBcreates** [modxcms/revolution#16305] opened 2022-11-23 14:45 UTC
### Summary
No preview for .webp, .jpg, and .jpeg image files in 3.0.2

### Step to reproduce
Upgraded from 3.0.1 to 3.0.2 in MODXcloud

### Observed behavior
all of the .webp, .jpg, and .jpeg images no longer have a preview. SVGs files do.

### Expected behavior
.webp, .jpg, and .jpeg is an uploadable file type, so I don't know upgrading to 3.0.2 would affect the preview. The actual images display on the front end but not in the image browser nor Resource editing.

### Environment
MODXcloud, none of the browsers I've tried display a preview. Safari displays a question mark while Firefox displays the file name in the Preview area.
<img width="880" alt="Screenshot 2022-11-23 at 7 44 47 AM" src="https://user-images.githubusercontent.com/102907654/203575610-4a22ba47-5eeb-4461-890a-f9c79968d8f4.png">

**Comment by halftrainedharry** [comment] 2022-11-25 09:33
I can't reproduce this problem.

Did you only upgrade MODX or also change the PHP version?

With PHP 8.1 and `display_errors` enabled, I get a deprecation warning in the response (`Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated`) that prevents the thumbnail image from being rendered correctly.
Maybe open the image source (`/connectors/system/phpthumb.php?src=something.jpg&...`) directly in a new browser tab and check if that is the problem.

**Comment by PeterBcreates** [comment] 2022-11-25 14:49
I upgraded to PHP 8.0 based on the EOL of 7.4. from this article:
https://support.modx.com/hc/en-us/articles/115002415427-Switching-or-Changing-PHP-Versions-in-Clouds

I Figured it wouldn't hurt and wasn't sure if this was something I should do or if upgrading to 3.0.2 would automatically do that before the 28th.

I downgraded back to 7.4  All is working again.

Marked this as closed.

**Comment by Maef** [comment] 2022-11-28 20:08
@PeterBcreates 

Could you try replacing the file core/vendor/james-heinrich/phpthumb/phpthumb.class.php with the latest version of https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php

We had the same situation on PHP 8.0 and Modx 3.0.2

**Comment by JoshuaLuckers** [comment] 2022-12-26 12:23
@PeterBcreates would it be possible for you to try if @Maef's suggestion works for you?

**Comment by PeterBcreates** [comment] 2022-12-31 14:48
Hi Joshua,

I’m embarrassed to admit that I don’t remember exactly what the issue was. The cloud instance is 3.0.2 and the PHP version is 8.1

Nevertheless I tried @Maef’s suggestion and everything seems fine.

That said I’m moving the 5 active domains on that cloud because it’s a hot mess. It’s 10 years old, like one of the original MODXclouds and has seen a bunch of extras installed, removed, deleted, and reinstalled again. It has been the same since the upgrade from 2.x to 3.x.

Peter
-------------------------
Peter Bockenthien
***@***.***
https://peterbcreates.com/
720-999-4169 text message only

This E-mail (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521 in addition to private party non-disclosure agreements and is confidential. This E-mail should be considered to be legally privileged. If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution or copying of this communication is strictly prohibited. Please reply to the sender that you have received the message in error, and then please delete it. 

￼

@PeterBcreates <https://github.com/PeterBcreates>
Could you try replacing the file core/vendor/james-heinrich/phpthumb/phpthumb.class.php with the latest version of https://github.com/JamesHeinrich/phpThumb/blob/master/phpthumb.class.php

We had the same situation op PHP 8.0 and Modx 3.0.2

**Comment by OsnielT** [comment] 2023-01-05 23:07
@halftrainedharry I used @Maef suggestion to replace phpthumb.class.php with the latest version and it worked, thus also resolving pThumb front-end fatal error issue.

**Comment by JoshuaLuckers** [comment] 2023-01-08 11:25
@opengeek if you publish a new 3.x release will it automatically include the newer phpThumb release?

**Comment by smg6511** [comment] 2023-01-09 04:30
@JoshuaLuckers - The referenced fix is actually not in the current phpthumb release. There were a few merges to fix problems (including this one) just a few days after the most recent release but they've not been incorporated into a new release yet.

**Comment by JoshuaLuckers** [comment] 2023-01-09 08:31
@smg6511 ah good to know, we could ask if they are willing to create a new release.

**Comment by Maef** [comment] 2023-01-09 14:45
I've contacted the author of phpThumb. There is a new release [1.17.20](https://github.com/JamesHeinrich/phpThumb/releases/tag/v1.7.20) with the latest changes

**Comment by opengeek** [comment] 2023-01-09 15:57
> @opengeek if you publish a new 3.x release will it automatically include the newer phpThumb release?

Yes, now that there is an actual release.

**Comment by smg6511** [comment] 2023-01-09 16:09
Confirmed. The author's new release became available this morning and it's available via composer.

So, to help those out there with a live install, what's the best way for them to update the composer packages (particularly if they have limited access to their server)?

**Comment by Mark-H** [comment] 2023-01-14 21:40
Closing as fixed in 3.0.3, planned for release this week.

> So, to help those out there with a live install, what's the best way for them to update the composer packages (particularly if they have limited access to their server)?

Don't.

**Closed as completed by Mark-H** 2023-01-14 21:40 UTC
Labels: bug
