### ISSUE TITLE
Two PDF files return different right click options

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#14013] opened 2018-07-25 14:34 UTC
### Summary
Firstly I've noticed this issue here, https://forums.modx.com/thread/104115/file-source-permission-options-displaying-different-options#dis-post-559910 after tried myself and got the same result - there are different menu options for different PDF files.

### Step to reproduce
You should have some PDF files, open File manager tab, go through all of them and bring up the context menu by right click, compare with the previous results  This works only for some files, not for all(don't know why and how....). 

### Observed behavior
Two different context menu options, please  see screenshots. Almost all PDF files provide extended menu with ("Edit", "Quick update")

![edit file_ lunchmenu-2017-yarmouth-stellarton pdf google chrome 2018-07-25 17 25 51](https://user-images.githubusercontent.com/2815640/43207264-5bd21fda-9030-11e8-902b-802996a8c6a1.png)

and **only one** returns correct shorter menu:

![edit file_ lunchmenu-2017-yarmouth-stellarton pdf - google chrome 2018-07-25 17 27 35](https://user-images.githubusercontent.com/2815640/43207262-5ba039b6-9030-11e8-99d7-930f75a1f164.png)

### Expected behavior
As for me the same options set should be displayed for all PDF's - "Rename", "Download", "Delete" only.
Like it works for other types, f.e. for .xls.

### Environment
MODX 2.6.5 on MODXCloud

**Comment by ghost** [comment] 2018-07-25 15:00
Possibly a different media source with the same paths and urls but different permissions?

**Comment by ant-tar** [comment] 2018-07-25 15:21
Hi Susan,
well, the only default media source is there. And as far as I can see the same user added these files

**Comment by SnowCreative** [comment] 2018-07-25 15:22
Any difference in file size?

**Comment by SnowCreative** [comment] 2018-07-25 15:23
Can you use FTP and check the server permissions for these files?

**Comment by smashstack-kris** [comment] 2018-07-25 15:26
@sottwell thanks for responding.  I'll have one of our team members review the scenarios being posted above and respond shortly.

**Comment by JoshuaLuckers** [comment] 2018-07-27 10:10
I can confirm this bug. It's fixed in MODX 3.0. I think this should also be solved in 2.x.

**Comment by alroniks** [comment] 2018-07-27 10:18
@JoshuaLuckers Do you know details about fix in 3.x?

**Comment by JoshuaLuckers** [comment] 2018-07-27 10:46
@Alroniks A lot has changed in 3.x (see PR #13709).  I have a good idea where to look to fix the issue here (a better way to check if we can edit the file).

**Comment by alroniks** [comment] 2018-08-27 12:23
Closing as PR is merged, but feel free to reopen if the issue is still there.

**Closed as completed by alroniks** 2018-08-27 12:23 UTC
Labels: bug, area-core
