### ISSUE TITLE
Error Update from 2.6.5 to 2.7: Call to a member function deprecated()

### ISSUE THREAD

**Issue by winformatic** [modxcms/revolution#14139] opened 2018-11-15 08:17 UTC
### Summary
Could not update a 2.6.5 Modx website. During the setup the following error appeared.
```
Error updating table for class modResource
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'alias_visible'
)
```

Log says:
```

[2018-11-15 09:09:41] (ERROR in xPDOManager_mysql::addField @ /page/core/xpdo/om/mysql/xpdomanager.class.php : 302) Error adding field modResource->alias_visible: Array
(
    [0] => 42S21
    [1] => 1060
    [2] => Duplicate column name 'alias_visible'
)
```

### Step to reproduce
Updated the files on webspace and run setup. All checks were ok. On install the error appeared:

### Observed behavior
After setup the manager page is a white page. Things I've tried:
1. Clear core/cache multiple times.
2. Check that compress_js/css are turned off.
3. Re-ran setup.
4. Cleared browser cache and checked in Incognito Mode (Chrome) or Private Mode (Firefox).
5. Nothing in server error log having to do with MODx.

### Installed Extensions
ace-1.6.5-pl
batcher-2.0.0-pl
ckeditor-1.4.0-pl
cmpgenerator-1.1.3-pl
formit-4.0.1-pl
formit2db-1.1.4-pl
getresources-1.6.1-pl
login-1.9.5-pl
migx-2.12.0-pl
orphans-1.1.1-pl
pdotools-2.11.0-pl
simpleupdater-2.1.2-rc
uicmpgenerator-1.0.1-beta
upgrademodx-1.5.5-pl
versionx-2.1.3-pl
wayfinder-2.3.3-pl

### Environment
MODX version 2.6.5, apache and PHP version 7.1.23 , mysql version 5.6.42,

**Comment by Jako** [comment] 2018-11-15 08:22
That install error message could not cause an error 500 in the manager.

Just for the records: The white page occurs after log in into the mangager?

Maybe it is caused by an old version of TinyMCE.

**Comment by winformatic** [comment] 2018-11-15 08:24
Hey, updated the description. 

Yes error accured after login.

**Comment by Jako** [comment] 2018-11-15 08:25
Could you get an apache or php error log? Normally php fatal errors are logged there.

**Comment by winformatic** [comment] 2018-11-15 08:28
```
[2018-11-15 09:09:41] (ERROR in xPDOManager_mysql::addField @ /pagee/core/xpdo/om/mysql/xpdomanager.class.php : 302) Error adding field modResource->alias_visible: Array
(
    [0] => 42S21
    [1] => 1060
    [2] => Duplicate column name 'alias_visible'
)


```


and the apache Log:

`
[Thu Nov 15 09:15:17.338976 2018] [proxy_fcgi:error] [pid 28649:tid 140242136848128] [client 90.187.63.109:58788] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function deprecated() on null in /page/core/model/modx/modmenu.class.php:119\nStack trace:\n#0 /page/core/model/modx/modmenu.class.php(145): modMenu->getSubMenus('components')\n#1 /page/core/model/modx/modmenu.class.php(66): modMenu->getSubMenus('topnav')\n#2 /page/manager/controllers/default/header.php(242): modMenu->rebuildCache('topnav')\n#3 /page/manager/controllers/default/header.php(150): TopMenu->getCache('topnav')\n#4 /page/manager/controllers/default/header.php(81): TopMenu->buildMenu('topnav', 'navb')\n#5 /page/manager/c...\n', referer: https://www.url.de/manager/?cultureKey=de
`

**Comment by Jako** [comment] 2018-11-15 08:33
Thats the real issue: 
`
PHP Fatal error: Uncaught Error: Call to a member function deprecated() on null in /page/core/model/modx/modmenu.class.php:119
`

**Comment by winformatic** [comment] 2018-11-15 08:35
OK, thanks. It's my first bug report, something else I have to do?

**Comment by Jako** [comment] 2018-11-15 08:42
Thanks a lot for reporting the bug! It should be fixed with the commit above.

**Comment by winformatic** [comment] 2018-11-15 09:09
Tried your commit and it works! Thank you very much!

**Comment by Jako** [comment] 2018-11-15 09:25
It will be closed when the PR is merged.

**Comment by alroniks** [comment] 2018-11-15 13:47
PR is merged.

**Closed as completed** 2018-11-15 13:47 UTC
Labels: bug, area-setup
