### ISSUE TITLE
Error 500 + installer fails when MYSQL Strict SQL Mode is ON

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/revolution#12838] opened 2016-01-01 18:58 UTC
## Summary
MODX installer fails and produces a `500 error` when `STRICT_TRANS_TABLES` is enabled in MYSQL. This issue was previously discussed here: #2085.

## Step to reproduce
Enable `Strict SQL Mode` in MYSQL's `/etc/my.cnf` file => `global sqlmode='STRICT_TRANS_TABLES'` . OS X users may also need to check `/usr/local/mysql/my.cnf` and `/usr/local/Cellar/mysql/5.x.xx/my.cnf` (if installed with Homebrew).

## Observed behaviour
On localhost, the installer stops immediately and outputs : ` Fatal error: Class 'xPDODriver_' not found in <core_path>/xpdo/xpdo.class.php on line 1880`. On a Virtual Host, the installer proceeds until the summary step and produces a `500 error` on the next. In the latter case, some tables are created and others are not. 
### A few errors found in the installer logs:
```
[2015-12-31 03:51:27] (ERROR @ /setup/index.php) Could not create table `modx_system_settings`
SQL: CREATE TABLE `modx_system_settings` (`key` VARCHAR(50) NOT NULL DEFAULT '', `value` TEXT NOT NULL, `xtype` VARCHAR(75) NOT NULL DEFAULT 'textfield', `namespace` VARCHAR(40) NOT NULL DEFAULT 'core', `area` VARCHAR(255) NOT NULL DEFAULT '', `editedon` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`key`)) ENGINE=MyISAM
ERROR: Array
(
    [0] => 42000
    [1] => 1067
    [2] => Invalid default value for 'editedon'
)

[2015-12-31 03:51:28] (ERROR @ /setup/index.php) Error 42S02 executing statement: 
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'modx.modx_system_settings' doesn't exist
)

[2015-12-31 03:51:28] (ERROR @ /setup/index.php) Error saving vehicle object of class modSystemSetting; criteria: Array
(
    [key] => access_context_enabled
)
...
```
### A few errors found in the server log:
```
[Wed Dec 30 12:28:47.365884 2015] [:error] [pid 24378] [client 127.0.0.1:53329] PHP   7. xPDOManager_mysql->createObjectContainer() <modx_path>/setup/includes/tables_create.php:116, referer: http://modx.kleverr.dev/setup/index.php?action=summary

[Thu Dec 31 03:51:27.227113 2015] [:error] [pid 32129] [client 127.0.0.1:63055] PHP Notice:  Undefined index: primary in /<core_path>/xpdo/om/mysql/xpdomanager.class.php on line 462, referer: http://modx.kleverr.dev/setup/index.php?action=summary

[Thu Dec 31 03:51:27.232336 2015] [:error] [pid 32129] [client 127.0.0.1:63055] PHP Notice:  Undefined index: unique in <core_path>/xpdo/om/mysql/xpdomanager.class.php on line 462, referer: http://modx.kleverr.dev/setup/index.php?action=summary
```
## Expected behaviour
MODX should be installable when MYSQL `Strict SQL Mode` is ON

## Environment
MODX 2.4.x, Apache 2.4.16, PHP 5.5.X, 5.6.16, MYSQL 5.7.10 Homebrew, OS X El Capitan

**Comment by Ibochkarev** [comment] 2016-01-30 02:56
when you install and get the error:
`PHP Notice:  Undefined index: primary in /var/www/consalger/www/core/xpdo/om/mysql/xpdomanager.class.php on line 462
PHP Notice:  Undefined index: unique in /var/www/consalger/www/core/xpdo/om/mysql/xpdomanager.class.php on line 462
Installation finished in 3.0856 s`

**Comment by sottwell** [comment] 2016-04-28 06:53
Didn't notice that #12987 was closed. Pull request #12990 for fix and comments applied to #12987, sorry.

**Comment by sottwell** [comment] 2016-04-28 07:00
Did a pull request #12990, needs testing by somebody with STRICT_TRANS_TABLES enabled.

**Comment by Jako** [comment] 2016-05-02 20:19
#12990 was merged. Could someone test this commit https://github.com/modxcms/revolution/commit/ec222bad0a094fa4d526088593fb79c50e352180 with STRICT_TRANS_TABLES enabled

**Comment by pixelchutes** [comment] 2016-05-02 23:03
Why was this submitted / merged without being tested against MySQL Strict Mode being enabled _first_?

**Comment by thewhiterabbit** [comment] 2016-05-03 22:40
I'll test it now. How do I download this commit? I'll do it now.

**Comment by OptimusCrime** [comment] 2016-05-03 23:21
That would be:

```
git clone git@github.com:modxcms/revolution.git
git checkout -b 2.5.x
git pull origin 2.5.x
```

**Comment by thewhiterabbit** [comment] 2016-05-04 00:05
I suppose I don't have access. 
:( 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by thewhiterabbit** [comment] 2016-05-04 00:08
I know how to clone the repository, but how do I get access to it? I should have made that clearer, sorry.

**Comment by Omeryl** [comment] 2016-05-04 00:16
Hey @thewhiterabbit, more than likely you just didn't have an SSH key added to GitHub. So do this instead:

```sh
git clone https://github.com/modxcms/revolution.git
git checkout -b 2.5.x
git pull origin 2.5.x
```

**Comment by thewhiterabbit** [comment] 2016-05-04 00:36
It's been a long day. Thank you for pointing that out @Omeryl, I appreciate it!

As soon as the clone finishes I'll do my testing!

**Comment by thewhiterabbit** [comment] 2016-05-04 00:56
OK, this is really weird. The installer isn't allowing me to tick the option for "Core Package has been manually unpacked" nor the option for "Files are already in-place".

I would assume that because I cloned the git repo, those options should be ticked. I must be doing something wrong. It fails install because it can't extract the core.transport.zip.

Have I completely done it wrong?

**Comment by thewhiterabbit** [comment] 2016-05-04 01:08
Also, upon further examination, the tables in question:

modx_context_setting
modx_lexicon_entries
modx_system_settings
modx_user_group_settings
modx_user_settings

are still failing to be created.

**Comment by thewhiterabbit** [comment] 2016-05-04 01:21
Just to be absolutely sure that I did it correctly, I copied the repo again, wiped the database, deleted the cache folder, then went to the setup page. This is what it looks like. The option "Core Package has been manually unpacked" is still disabled. So, I just continued with the install to test the table creation again. Still failing to create the aforementioned tables, and failing to extract the transport package for core.
![screen shot 2016-05-03 at 6 18 16 pm](https://cloud.githubusercontent.com/assets/5334222/15002955/8b6f75fe-115b-11e6-84f4-d98b24c63025.png)

![screen shot 2016-05-03 at 6 14 41 pm](https://cloud.githubusercontent.com/assets/5334222/15002886/fc15e2da-115a-11e6-97f1-b2f7b0fada03.png)

**Comment by sottwell** [comment] 2016-05-04 03:02
You need to build it. http://modxcookbook.com/installation/files/build.html

**Comment by Jako** [comment] 2016-05-04 05:40
See the discussion on #12990

**Comment by thewhiterabbit** [comment] 2016-05-04 05:43
Thank you for pointing that out @sottwell! I've eliminated the error regarding the transport, but the tables in question are still not being created. Using mySQL v5.7.10. I'm still getting the 500 error at the end of the installation and I've looked to verify that the missing tables are the cause.

**Comment by OptimusCrime** [comment] 2016-05-04 09:06
What are the errors?

**Comment by thewhiterabbit** [comment] 2016-05-04 21:26
@OptimusCrime see comment [216715450](https://github.com/modxcms/revolution/issues/12838#issuecomment-216715450)

**Comment by thewhiterabbit** [comment] 2016-05-04 23:36
I just initiated a pull request for the true fix after much research, editing, and testing. Let me know if I can ever help with anything else! Turns out that the best practice is using NULL default values for any time based fields in mySQL.

**Comment by Jako** [comment] 2016-05-05 04:55
Thanks a lot.

**Comment by thewhiterabbit** [comment] 2016-05-05 05:43
You guys and gals are all very welcome! Glad to help.

**Comment by Jako** [comment] 2016-05-05 07:24
#13001 is merged, hope the issue is gone now. Thanks for all the comments, tests etc.

**Closed by Jako** 2016-05-05 07:24 UTC
Labels: area-core, bug, priority-1-urgent, state/in-progress
