### ISSUE TITLE
Form Customization: Ability to move standard Resource Fields

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#13244] opened 2017-01-06 18:26 UTC
### Summary
FC is powerful and awesome. Resource fields can be renamed, set default, hidden, etc but they cannot be moved to different regions like TVs can. 

A user @funkyduke submitted an FR to the Collections repo but actually it's more suitable for this to be handled in FC rather than Collections, IMO.

### Step to reproduce
Try to move a standard Resource field with FC.

### Observed behavior
Confusion at the fact that it's not supported.

### Expected behavior
Given everything else FC can do, it seems like it "should" be supported.

### Environment
All MODX versions up to 2.5.4 so far...

**Comment by Mark-H** [comment] 2017-01-13 15:19
Dupe of #12313 (among others, probably).

**Closed by Mark-H** 2017-01-13 15:19 UTC
Labels: feature
