### ISSUE TITLE
modx 2.3.5 "target not set" on drag and drop in manager resource tree.

### ISSUE THREAD

**Issue by BigBlockStudios** [modxcms/revolution#12511] opened 2015-07-13 17:11 UTC
after an update to 2.3.4 I'm getting a  "target not set" on drag and drop in manager resource tree.

no errors logged. any idea what is causing that?

**Comment by phantomphondler** [comment] 2015-07-30 13:56
same issue here

**Comment by phantomphondler** [comment] 2015-07-30 13:58
had same issue must be cache see http://forums.modx.com/thread/97558/2-3-5-drag-n-039-drop-in-resource-tree

**Comment by pixelchutes** [comment] 2015-07-31 14:49
In the title, you reference `v2.3.5`, but in the comment it states `v2.3.4`

Can you please confirm if on v2.3.5, as I believe there was a D&D issue fixed for this patch release. The steps in the post above could also prove helpful.

**Comment by siteleas** [comment] 2015-08-22 04:03
I am getting this same problem in MODx 2.3.5-pl (traditional). I get this message when I attempt to drag any document to a different location in the resource tree. Is there a fix for this?

**Comment by ahaller** [comment] 2015-08-28 18:49
I've been having this issue since 2.3.5 as well. Today I updated to 2.4, but that did not fix it. 

I also:
- I cleared MODX cache
- Flushed sessions
- Delete all files and folders in core/cache
- Cleared all browsercache
- Re-installed 2.4

But am still having this issue.

Is there any solution?

**Comment by sbrin** [comment] 2015-09-18 09:59
I've got same issue as @ahaller described.

**Comment by ahaller** [comment] 2015-09-18 12:16
I was able to resolve my issue. See here: http://forums.modx.com/thread/98164/target-not-set

**Comment by OptimusCrime** [comment] 2016-04-19 21:49
Bumping old issue. Can anyone post steps to reproduce this? I am unable to do so in newly installed version from GitHub.

Closing because lack of feedback. Feel free to reopen.

@modxbot close

**Closed by OptimusCrime** 2016-04-19 21:49 UTC
Labels: state/awaiting-feedback

**Comment by randomdave** [comment] 2016-09-01 13:23
This issue has been plaguing me for months now:
https://forums.modx.com/thread/?thread=98164&page=3

It came in with my install when upgrading to 2.3.4pl and is not fixed in any versions I've tried updating to after that.

I've tried all sorts of cache clearing etc, but still no joy.
