### ISSUE TITLE
Float TV input_properties are converted to int

### ISSUE THREAD

**Issue by argnist** [modxcms/revolution#12226] opened 2014-12-22 07:09 UTC
TV input properties can't be float because of next lines https://github.com/modxcms/revolution/blob/master/core/model/modx/modtemplatevar.class.php#L1132

**Comment by Alroniks** [comment] 2017-06-16 21:42
Closing as duplicate of #12451 and it's already fixed.

**Closed by Alroniks** 2017-06-16 21:42 UTC
