### ISSUE TITLE
Error updating from version 2.7.0 to version 2.7.1 Error updating table for class modResource - Duplicate column name 'alias_visible'

### ISSUE THREAD

**Issue by auditor8880** [modxcms/revolution#14585] opened 2019-05-14 22:52 UTC
Error updating from version **2.7.0** to version **2.7.1** Error updating table for class modResource - Duplicate column name 'alias_visible'

During the installation, when checking everything is OK - everything is green.
After installation, click "Show warnings" and here is the error:

> Table update error for class modResource
> Array
> (
> [0] => 42S21
> [1] => 1060
> [2] => Duplicate column name 'alias_visible'
> )
> 
> 

The change indicated below is in my file.
> core / model / modx / modmenu.class.php
 [https://github.com/modxcms/revolution/pull/14140/files/349fb106a24c62702a64f8c08d25890e7caf6fd1](https://github.com/modxcms/revolution/pull/14140/files/349fb106a24c62702a64f8c08d25890e7caf6fd1)

However, these fixes do not help and the error is still there.

Apache version 2.4.39
PHP version 7.1.27
MySQL Version 10.2.24-MariaDB
X86_64 architecture
Linux operating system
Perl Version 5.16.3
Kernel version 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64

**Comment by Ibochkarev** [comment] 2019-05-15 02:21
Fixed in https://github.com/modxcms/revolution/pull/14396

**Comment by alroniks** [comment] 2019-05-15 07:11
Thank you for reporting, but it also fixed as @Ibochkarev mentioned and it is a duplicate of https://github.com/modxcms/revolution/issues/14382
So I have to close it.

**Closed as completed by alroniks** 2019-05-15 07:11 UTC

**Comment by auditor8880** [comment] 2019-05-15 09:04
Thank you, that is, this problem is in the installation package itself.

**Comment by Ibochkarev** [comment] 2019-05-15 09:20
@auditor8880 That's right. Fix will be included in 2.7.2
