### ISSUE TITLE
Increase modx_site_content.description to 300 characters for Google Search Snippet

### ISSUE THREAD

**Issue by gpsietzema** [modxcms/revolution#13801] opened 2018-03-02 11:04 UTC
### Summary
Google changed the length of Search Snippets to ~300 characters in December 2017: https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596 

It is the snippet below the title in this example:
![google-snippet](https://user-images.githubusercontent.com/381017/36895176-424bbc86-1e0e-11e8-8ccd-0de2632cab49.png)

The Search Snippet is based on the following HTML tag:
```<meta name="description" content="revolution - MODX Revolution - Content Management Framework">```

In MODX this usually looks something like this:
```[[*description:notempty=`<meta name="description" content="[[*description]]">`]]```

The only issue is, MODX doesn't allow more than 255 characters. We should increase it to 300.

### Step to reproduce
Try to save a description of more than 255 characters.

### Observed behavior
Error message stating that 255 is the max.

### Expected behavior
No message and saving to db.

**Comment by Mark-H** [comment] 2018-03-02 11:05
Duplicate of #13738 (which you've also commented on, interestingly)

**Closed as completed by Mark-H** 2018-03-02 11:05 UTC
