### ISSUE TITLE
Elements category combox should have pagination / refresh buttons

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#11992] opened 2014-09-19 13:46 UTC
When you create a new category when you're already on the elements form, you cannot refresh te list.

Also a "Create new" option in the combobox would be great and then the list should auto-refresh. ;-)

**Comment by OptimusCrime** [comment] 2015-08-11 21:40
Duplicate of referenced issue. The dropdown does refresh fully when clicked and can be refreshed more by clicking the combobox refresh button. Create new category can be done via quick create.

@modxbot close

**Closed by OptimusCrime** 2015-08-11 21:40 UTC
Labels: enhancement, feature
