### ISSUE TITLE
Moving Resources between contexts causes missing pages

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12167] opened 2014-11-21 19:27 UTC
In Revo 2.3.2, I created a resource under a parent in the web context, drag-and-drop moved it to a second context then back to the web context under the same parent.  Once I did this, it was no longer viewable in the resource tree.  Search does bring up the pages that were moved however once I removed the second context it was removed from Search along with it.  I suspect drag-and-drop between contexts does not always update the context keys correctly.

**Comment by RinzeVanDerBrug** [comment] 2017-03-03 13:29
Going to check this today.

**Comment by RinzeVanDerBrug** [comment] 2017-03-03 13:35
Can not reproduce this.

Tested this in MODX 2.5.5 on macOS Sierra (10.12.3) in:
- Chrome v56.0.2924.87
- Firefox v51.0.1
- Safari v10.0.3

Dragged resources back and forth between contexts and parent pages, but none of the resources disappeared. This issue seems to be outdated and can be closed. #modxbughunt

**Comment by rtripault** [comment] 2017-03-03 14:00
So closing.

Feel free to comment/reopen if needed.
Thanks

**Closed by rtripault** 2017-03-03 14:00 UTC
